### PR TITLE
LPD-22288 Release Feature Flag for Calendar Events 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Release FF at Instance Level: 

Screenshot 2024-04-04 at 13 04 12

New Calendar Events available when release FF is enabled: 
Screenshot 2024-04-04 at 13 02 34

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
Hi,

Now that this failed 
maybe : 
`if (!FeatureFlagManagerUtil.isEnabled("LPD-10945")) {`
Should be company oriented

**Comment by ambrinchaudhary** [comment]
Current failure:  

> Portal log assert failure, see above log for more information:  Feature flag LPD-10945 is not available for company 0

**Comment by ambrinchaudhary** [comment]
Hi @adolfopa, could you help with this failure? @jkappler mentioned me that maybe the FF needs to be set somewhere else, not in the CapabilityProvider

**Comment by jkappler** [comment]
From the logs in https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/892878/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/:

`Feature flag LPD-10945 is not available for company 0
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:162)`

since it's registered when starting, it seems that the company is not set in CompanyThreadLocal, and that's why it's shown in the logs

**Comment by adolfopa** [comment]
@ambrinchaudhary @jkappler If the company ID is not set in the thread local, then this cannot be an instance level feature flag (the method does not receive the company ID as argument). We'll have to keep this as a system one.

**Comment by ambrinchaudhary** [comment]
@adolfopa we have this [comment](https://liferay.atlassian.net/browse/LPD-8009?focusedCommentId=2553433) on the original task by Luiz Jardim: 

> When this is ready we should move to release or directly remove the feature flag, I don’t see this with many impacts in the UI that users need to adapt to and I don’t see a architectural risk to change, which would categorize as beta.


If we cannot set this as release FF, should we just remove it, o better keep it at system level?

**Comment by ambrinchaudhary** [comment]
New pull where I remove the FF https://github.com/liferay-content-management/liferay-portal/pull/5315

**Pull request closed without merging**
