### PR TITLE
LPD-18323 Custom user rank labels in Message Boards do not work correctly

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPD-18323](https://liferay.atlassian.net/browse/LPD-18323)

We passed down the whole entity instead of just the value, which we ended up rendering here: https://github.com/liferay-echo/liferay-portal/blob/master/modules/dxp/apps/akismet/akismet-web/src/main/resources/META-INF/resources/view_thread_message.jsp#L91-L95

Please review my change,

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
