### PR TITLE
LPD-22957 Hide/show Meta or Content fields according with the selected filter

### PR DESCRIPTION
**Pull request by DiegoHu97**
\[Link to ticket\](https://liferay.atlassian.net/browse/LPD-22957)

## Steps

*   Go to Content & Data > Web Content > Create a Web Content
*   Fill the title and content fields
*   Change the language to one different from the default one
*   See "All fields" picker > Select the different options and see Metadata and Contenn field are hide/shown according to which filter is selected

https://github.com/liferay-content-management/liferay-portal/assets/91208451/5b362b39-46b4-422f-ac84-05789828dee2

### CODE REVIEW

**Comment by NemethNorbert** [comment]
Great job @DiegoHu97 !

I approve this pull request

**Comment by NemethNorbert** [comment]
ci:forward

**Review by NemethNorbert — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
