### PR TITLE
LPD-32890 Journal UndoRedo - Add all steps to the history dropdown

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[Link to ticket](https://liferay.atlassian.net/browse/LPD-32890)

Some screenshots while tested with data engine fields: 

Moved to step 3: 
Screenshot 2024-08-21 at 13 34 48

Back to the last step:
Screenshot 2024-08-21 at 13 35 11

**Note:**
Test will be added in a different subtask https://liferay.atlassian.net/browse/LPD-31063 once the rest of the task are completed

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by DiegoHu97 — CHANGES_REQUESTED** [review]
Hello @ambrinchaudhary , the PR looks great. i found some issues that we may look at:
- The first one is that the Undo All button does not reset changes in ddm fields
- If we click in undo all > then we redo the changes > I think that the history should point to the last step that we have, now it stays always in the first step as we are passing always `step + 1` to the handleRedo function, maybe we should store something like `previousStep` for this case
- The last issue is that when we edit a text field and after we edit a Single Selection, it creates two steps in the history, this happens with Multiple Selection too, maybe this is a bug of ddm, we can ask them, what do you think?
That's all, we can talk in Slack if you need more info :smile:

**Comment by ambrinchaudhary** [comment]
Thank you very much for your tests. I fixed the first issue. The second one, as we discussed, it is expected the way it is, and also for the Page Editor it behaves the same way. 

For the third point, I am going to create a different bug, as it is not related to this pull (I think, steps on the history were created before), and will debug if it is ours or DDM. We may be triggering two different events (blur + change?) or maybe is a different thing. Is it ok for you?

**Comment by DiegoHu97** [comment]
@ambrinchaudhary Perfect then! I will forward the pr, thank you :heart:

**Comment by DiegoHu97** [comment]
ci:forward

**Pull request closed without merging**
