### PR TITLE
Lpd 21161 followup

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1257401_5186

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Failures are not related. This can be forwarded manually.

**Comment by robertoDiaz** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
@robertoDiaz I think you'll need to forward this manually to bchan.

**Comment by robertoDiaz** [comment]
Closed in favour of https://github.com/brianchandotcom/liferay-portal/pull/149316

**Pull request closed without merging**
