### PR TITLE
LPD-39367 add getPropertiesTab for different languages of Properties

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi,

I would like to kindly ask to review this PR? 

The subtask is https://liferay.atlassian.net/browse/LPD-39367.
**Root cause**: The title is not handled properly, probably because the page not yet loaded.
**Solution**: Change to use filledTitle, but the locator was using language dependant "properties" value, so I created a method to get the value for the language of the site.

Thanks!

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:content-management

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:content-management

**Comment by boton** [comment]
See #6008

**Pull request closed without merging**
