### PR TITLE
LPD-31199 fix for ItemSelector#CanUploadImageInWikiPage

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
# Motivation
https://liferay.atlassian.net/browse/LPD-31194

This test is consistently failing in CI, but it is passing in local. 

# How did I solve it

From the poshi report my guess is that Click is not being triggered, so I added a` AssertElementPresent()` function to assure there is a wiki page, and when clicked, we view the page. 

This is just my guess, so I will check in CI if it passes.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:item-selector

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
Code looks good. Waiting for the tests passing to do the forward.

**Comment by ambrinchaudhary** [comment]
Fix didn't solve the problem, [LocalFile.ItemSelector#CanUploadImageInWikiPage](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/683813//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ItemSelector_CanUploadImageInWikiPage_) is still failing on CI.I am looking for a different solution....

**Comment by ambrinchaudhary** [comment]
ci:test:item-selector

**Comment by ambrinchaudhary** [comment]
It passes successfully this [last time](https://testray.liferay.com/#/project/34754/routines/34756/build/35843830/case-result/35851766), so I'm going to forward and check tomorrow's build to be sure before closing the jira ticket.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
