### PR TITLE
LPD-22499 Add functional testing

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: https://liferay.atlassian.net/browse/LPD-22499

Description
---------
Add test for https://liferay.atlassian.net/browse/LPD-22497 bug

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:playwright

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:playwright

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
