### PR TITLE
LPD-27779 LPD-27787 LPD-27790 Use ctCollectionId in upgrade queries

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-27790

Some queries should restrict updates by ctCollectionId, but they're not taking that column into account.

# How am I fixing it?

By adding the ctCollectionId as an additional filter to the queries.

# How can you verify that it works?

This PR includes three integration tests, one per upgrade process.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:upgrade

**Comment by adolfopa** [comment]
ci:test:upgrade

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
@adolfopa, changes look good. I will run a report jic

**Comment by jkappler** [comment]
ci:report:67545935

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@adolfopa, errors don't seem to be related, so I'm forwarding it

**Comment by adolfopa** [comment]
ci:report:68870768

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by marianoalvarosaiz** [comment]
@jkappler, @adolfopa I had to send a pull to revert this because is breaking the upgrade test suite, see https://github.com/brianchandotcom/liferay-portal/pull/153693

**Pull request closed without merging**
