### PR TITLE
LPD-16650 Check if permission checker exists

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:report:2534918935

**Comment by robertoDiaz** [comment]
Seems that errors are not unique to this PR

**Comment by robertoDiaz** [comment]
ci:forward:force

**Comment by robertoDiaz** [comment]
ci:forward:force

**Comment by robertoDiaz** [comment]
ci:forward:force

**Pull request closed without merging**
