### PR TITLE
LPD-39505 Add playwright test to View Selected Web Content With Geolocation Field

### PR DESCRIPTION
**Pull request by gergelyszalay**
Cannot edit structure key when disabling configuration

What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-39805, 
https://liferay.atlassian.net/browse/LPD-39805

The geolocation field properly displayed in a web content display

How am I fixing it?

moved the test to the playwright, the 2 tests could be merged into one.

How can you verify that it works?
Run the tests locally

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@gergelyszalay, seems failures are related : 

[View Selected Web Content With Geolocation Field](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/767351//testReport/journal-web_journalArticle.spec/ts/View_Selected_Web_Content_With_Geolocation_Field)

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
Closing this, currently is failing on ci because of https

**Pull request closed without merging**
