### PR TITLE
LPD-22611 Changing jmatio version to 1.5

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi,

I would like to kindly ask to review my PR:

Issue:
[https://liferay.atlassian.net/browse/LPD-22611](LPD-22611) when uploading a matlab file it throws: java.lang.NoClassDefFoundError: sun/misc/Cleaner

root cause: 

This class (sun.misc.Cleaner) has been moved to another pckg in JDK9 (https://bugs.openjdk.org/browse/JDK-8148117), see https://hg.openjdk.org/jdk9/jdk9/jdk/rev/07dcdd5d9401. Tika should be updated as it uses outdated dependency (JMatIO) which has this issue when parsing MatLab files: https://github.com/diffplug/JMatIO/issues/4

Solution is to update jmatio to 1.5. 

Thank you in advance!

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:report:2559279143

**Comment by adolfopa** [comment]
Failures not related. Forcing.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
