### PR TITLE
LPD-21190 Correct individual scope to check TranslationPortlet permissio

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi Team,

May I ask if you could review my PR?

Issue https://liferay.atlassian.net/browse/LPD-21190, that even if I set view permission for translation, I could not see the translations in Content & Data -> Translation Processes. 

Root cause,  this is always false: [TranslationEntryResourcePermissionLocalServiceWrapper.java](https://github.com/liferay/liferay-portal/blame/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/translation/translation-service/src/main/java/com/liferay/translation/internal/service/TranslationEntryResourcePermissionLocalServiceWrapper.java#L83) as we never check with individual scope.

solution: If I remove the if (scope != ResourceConstants.SCOPE_INDIVIDUAL), it does not work as this is not an entry check, so after it can not fetch translation entry, and can not check hasResourcePermission() as we dont have permission saved in the database as TranslationEntry. The solution is to check permission neme="TranslationPortlet", because it is saved with that name in the table.

It was tested locally.

Thank you in advance!

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Comment by gergelyszalay** [comment]
ci:stop

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
I do not know if [LocalFile.TranslationsWorkflow#CanResubmitImportedEntryFromZipFile](https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/365393//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_TranslationsWorkflow_CanResubmitImportedEntryFromZipFile_) is relevant on the changes

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
