### PR TITLE
LPD-6962 update status and show info on the file #5152

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Same code as https://github.com/liferay-content-management/liferay-portal/pull/5152 but with poshi changes to see if this solves some poshi test or breaks more

- **LPD-6962 add validation for the display date - expiration date relation**
- **LPD-6962 update status taking into account the display date**
- **LPD-6962 create method to obtain only the last version by status**
- **LPD-6962 create method on displayContext to know if a file has an approved version**
- **LPD-6962 show labels if is not approved but hasApprovedVersion**
- **LPD-6962 create method to publish document every interval check**
- **LPD-6962 create isScheduled method on fileVersion class**
- **LPD-6962 implement isScheduled methods**
- **LPD-6962 show info with the display date**
- **LPD-6962 Allow generate new version on scheduled status**
- **LPD-6962 Show labels with avoiding duplicated labels and deprecated tags**
- **LPD-6962 Add missing cases**
- **LPD-6962 semantic version**
- **LPD-6962 baseline**
- **LPD-6962 buildService**
- **LPD-17557 When there is an existing published version and then a new scheduled version is created**
- **LPD-6962 fix poshi test**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2543342477

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2543337369

**Review by robertoDiaz — APPROVED** [review]
Good to go!!

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2544076073

**Comment by AliciaGarciaGarcia** [comment]
semver error was relevant with this PR.

fixed and rebased with master

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2544466366

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
