### PR TITLE
LPD-44904 Web Content Schedule Publication Feature Flag is only in UTC and wrong time is displayed after scheduled

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPP-57156

# How am I fixing it?

Change the creation of the new date taking into account the timezone in the date time validation.

# How can you verify that it works?

Run the included test.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:content-management-playwright

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:test:relevant

**Review by DiegoHu97 — APPROVED** [review]
LGTM! We have to take a look in the future to the test to simplify it, but as this is a fire LPP we will forward it

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
