### PR TITLE
LPD-29516 Is not possible to upload images to the Blog repository while having Workflow activated

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-29516

A security fix was added with https://liferay.atlassian.net/browse/LPD-2816, but we still want to maintain same old functionality to be able to upload an image inside a blog if we have a workflow activated, so, we are adding a beta FF to do not apply that security fix. For more context see this comment : https://liferay.atlassian.net/browse/LPP-54591?focusedCommentId=2683135

# How am I fixing it?

Adding a FF.

# How can you verify that it works?

Run included tests and follow the steps to reproduce the LPD bug.

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:28105360

**Comment by jkappler** [comment]
@Mikellorza, BlogsItemSelectorViewDisplayContextTest failure seems to be related

**Comment by Mikellorza** [comment]
Hi @jkappler ,

finally we have had to change from deprecated FF to beta FF because deprecated FF has the following behavior:

- A new company (instance) will have the current declared deprecation feature flags status set as false (this is done by this CompanyModelListener);

- For an existing company, the value for the current declared deprecation feature flags will be true (ensured by this source format rule).

And we need to keep actual behavior and disable it when we need, so we have to perform this through beta FF.

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:29310690

**Comment by Mikellorza** [comment]
ci:report:29442085

**Comment by Mikellorza** [comment]
ci:report:29442085

**Comment by Mikellorza** [comment]
Failing tests are not related with the changes of this PR and also I tested it on my local environment and everything went well but for double check I run the ci:test:relevant again.

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:report:29486859

**Comment by Mikellorza** [comment]
Failing tests are not related with the changes of this PR and furthermore are nor consistent with the unique failures of the last test relevant execution, so, I am going to move forward to brian.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
