### PR TITLE
LPD-33132 Posting a Document to Forums

### PR DESCRIPTION
**Pull request by Mikellorza**
Coming from https://github.com/liferay-content-management/liferay-portal/pull/5737 and resending again because I forgot a change about getting the parameter from the request as you can see in the commit.

https://liferay.atlassian.net/browse/LPD-33132
# What is this trying to solve?

Allow to upload files with comma when we are creating a thread on message board.

# How am I fixing it?

Using another parameter to know the filenames associated with thread instead of the used one.

# How can I test it?

Run included functional test.

https://github.com/user-attachments/assets/32423aac-cb4f-4c5d-99f1-bdf84f442237

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@Mikellorza The code looks good, but how did the test pass if the action was splitting on comma? Or did it fail but we didn't see it?

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
Believe me I don know what happened here because I tested it in a functionally way and also I run the playwright tests many times but I see that this is separated  by commas when the CS tested it. I have no answer to give you :(. Maybe the test failed but I didn't see it..I have to investigate what happened here because I'm worried about it

**Comment by Mikellorza** [comment]
I think the ci is stuck, so let's stop and run again because the run is taking more time that expected.

**Comment by Mikellorza** [comment]
ci:stop

**Comment by Mikellorza** [comment]
ci:help

**Comment by Mikellorza** [comment]
ci:close

**Comment by Mikellorza** [comment]
ci:open

**Comment by Mikellorza** [comment]
ci:reopen

**Comment by Mikellorza** [comment]
ci:stop

**Comment by Mikellorza** [comment]
ci:forward

**Pull request closed without merging**
