### PR TITLE
LPD-22374 Remove processConcurrently to simplify and avoid the race c…

### PR DESCRIPTION
**Pull request by SamZiemer**
https://liferay.atlassian.net/browse/LPD-22374

This LPD has been committed already, but I am sending an additional commit for this LPD based on a slack message I received from Brian Chan. He requested that I remove the processConcurrently logic instead of using a synchronizedList.

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by SamZiemer** [comment]
ci:reevaluate:1297401_9566

**Comment by SamZiemer** [comment]
None of the failures look to be related to the changes in this PR, most are errors on the start up of the tests. I'll try to run the upgrade tests again, but if the same failures occur I think they can be safely ignored.

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by adolfopa** [comment]
ci:report:2560300965

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
