### PR TITLE
LPD-20520 call the FF method with the companyId

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1367401_5467

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2550750260

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
