### PR TITLE
LPD-28154 Fix the KBFolder#CorrectActionsAppearInToolbarAfterSelectingFolder test

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-27915 > [LPD-28154](https://liferay.atlassian.net/browse/LPD-28154)

Fix the poshi test (selector issue related to header changes).

# How am I fixing it?

I updated a selector avoiding the headers updated here https://github.com/liferay-platform-experience/liferay-portal/pull/604

# How can you verify that it works?

I'm not sure because it isn't working in my local but in theory, running the test in local should work.

```sh
ant -f build-test.xml run-selenium-test -Dtest.class=KBFolder#CorrectActionsAppearInToolbarAfterSelectingFolder
```

### CODE REVIEW

**Comment by boton** [comment]
ci:test:knowledge-base:nocompile

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
Updated to use a subtask [LPD-28154](https://liferay.atlassian.net/browse/LPD-28154) instead of a task [LPD-27915](https://liferay.atlassian.net/browse/LPD-27915)

**Comment by boton** [comment]
ci:test:knowledge-base:nocompile

**Comment by boton** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:report:13710176

**Comment by adolfopa** [comment]
Failures look unrelated.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
