### PR TITLE
LPD-32072 Technical Task | Add ExternalReferenceCode to Document Types (Part 1)

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LPD-32072

# What is this trying to solve?

Add external reference code to dl file entry type to internal api.

# How am I fixing it?

Add external reference code to dl file entry type to internal api.

# How can you verify that it works?

Run the included tests

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:45371580

**Comment by Mikellorza** [comment]
Too much failures. It seems that CI is working fine. Let's go to run suites again.

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
I forgot baseline of the portal kernel. So , I adding a commit with the baseline and running suites again.

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:report:46061169

**Comment by Mikellorza** [comment]
ci:report:46061169

**Comment by Mikellorza** [comment]
I reviewed the failures and It seems that are not related. Checking again running test suite.

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:report:47266215

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:48810099

**Comment by Mikellorza** [comment]
There is a conflict and also a compilation error in the test for the upgrade, so, I am working on fix for these things.

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:49562406

**Comment by Mikellorza** [comment]
It seems that unique failures are not related because there is an error related to tika and another error related to segment. So, lets run relevant suite again.

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:49879906

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:50831307

**Comment by Mikellorza** [comment]
ci:forward:force

**Comment by Mikellorza** [comment]
Unique failures tests are not related with the changes of the PR. So lets move forward to Brian.

**Pull request closed without merging**
