### PR TITLE
LPD-20274 avoid NPE on structures view

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Steps to Reproduce 

1) Go to Web content
2) Go to kebab menu (three dots)
3) Click on Configure

- **LPD-20274 move getHighlightedDDMStructuresJSONArray to the JournalConfigurationDisplayContext file because is only used there.**
- **LPD-20274 move move common code to an util file to be accessible by both files without have to create them**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
I opted to create the new Util because the creation of the journalDisplayContext is very expensive and the use of the JournalConfigurationDisplayContext on the view has no sense.

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1257401_4959

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
