### PR TITLE
LPD-31285 Adds unit tests for orderByCol and orderByType methods in JournalDDMStructuresDisplayContext

### PR DESCRIPTION
**Pull request by jkappler**
Adds unit tests for orderByCol and orderByType methods in JournalDDMStructuresDisplayContext

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-31285)

This PR adds tests for methods in JournalDDMStructuresDisplayContext to cover LPP-53599

# How can you verify that it works?

Run the provided tests

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:38495866

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
