### PR TITLE
LPD-42641 When selecting web contents to display in the Web Content Display widget expired content is also displayed

### PR DESCRIPTION
**Pull request by jkappler**
What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-42641

How am I fixing it?

The issue is that the selector also lists expired content. To avoid performance issues I created a new finder with the possibility to filter out the status that we want.

How can you verify that it works?

To test run:
gw testIntegration --tests JournalFolderFinderTest

### CODE REVIEW

**Comment by Mikellorza** [comment]
Starting to review it.

**Comment by Mikellorza** [comment]
LGTM!

**Comment by jkappler** [comment]
@Mikellorza, test is a known failing test, so I will move forward

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
