### PR TITLE
LPD-19960 404 if the url is not valid

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1407401_8948

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2548818415

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
