### PR TITLE
LPD-24051  Show icon in the Editor Screen of Document.

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi,

May I ask to review my PR?

This includes:

https://liferay.atlassian.net/browse/LPD-20352
https://liferay.atlassian.net/browse/LPD-20363
https://liferay.atlassian.net/browse/LPD-24051

And also includes fix for https://liferay.atlassian.net/browse/LPD-24311

The link for [figma](https://www.figma.com/file/YMcgShbEYvN2XMPPpc154t/LPD-16311-Define-and-manage-Site-default-D%26M-permissions?type=design&node-id=47-7787&mode=design)

Thank you!

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@gergelyszalay, @DiegoHu97, code looks good, but I will review after fixing the SF 😢

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:report:2565249676

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
