### PR TITLE
LPD-18057 The translation of the title, description and friendly url is not saved correctly after publishing

### PR DESCRIPTION
**Pull request by veroglez**
impedibug: https://liferay.atlassian.net/browse/LPD-18057

cc @DiegoHu97

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:report:2541289563

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
