### PR TITLE
LPD-31063 Journal history tests

### PR DESCRIPTION
**Pull request by DiegoHu97**
LPD-31063 Journal history tests

# What is this trying to solve?

- Create test for history button in Web Content

[Link to ticket](https://liferay.atlassian.net/browse/LPD-31063)

# How am I fixing it?

- Create Playwright test

# How can I test it?

- Execute the test

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
Hey @DiegoHu97, this LGTM! 
I wanted to take advantage and ask you to include the fix for https://liferay.atlassian.net/browse/LPD-35330 in this pull, so we can change the test at the same time. 

We only need to change this [condition](https://github.com/ambrinchaudhary/liferay-portal/blame/master/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/UndoRedo.js#L457) by: 
`disabled={history.length < 1}`
So the History button is not disabled when clicked on `Undo All `option. Thus, this line is not needed anymore. 
This is thee correct behaviour described in the story

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
### ci:test:content-management-playwright

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Comment by DiegoHu97** [comment]
Hey @ambrinchaudhary I just included the change you mentioned, the condition should be `history.length <= 1` :smile:

**Comment by DiegoHu97** [comment]
ci:forward

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
Those playwright failures are currently failing in testray, so they are not unique to this pull.

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
