### PR TITLE
LPS-21161 Staging for categories of friendly URLs

### PR DESCRIPTION
**Pull request by jkappler**
Sending on top of https://github.com/liferay-content-management/liferay-portal/pull/5264

It should be on hold until the other PR is merged

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
Looks great @jkappler :+1:

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:report:2559438839

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:report:2559583281

**Comment by robertoDiaz** [comment]
Checking if com.liferay.change.tracking.internal.test.LayoutCTTest failures are related

**Comment by robertoDiaz** [comment]
> Checking if com.liferay.change.tracking.internal.test.LayoutCTTest failures are related

Tests are not failing in local with current code.

@jkappler I think we could forward this

**Review by robertoDiaz — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2559795473

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2559938093

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
@robertoDiaz, @adolfopa, no unique failures, so moving it forward

**Pull request closed without merging**
