### PR TITLE
LPD-39841 AssetPublisher entries are not visible when published to Remote Live

### PR DESCRIPTION
**Pull request by jkappler**
AssetPublisher entries are not visible when published to Remote Live

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-39841)

Collections connected to the site are not published correctly to remote site

# How am I fixing it?

For sites (groupes), external reference code is different between local and remote staging. For this, if we are publishing, search the correct ERC in the group type settings and replace it accordingly.

# How can you verify that it works?

There are several tests that already cover this:

DepotCollections#CanBePublishedViaRemoteStaging
DMRemoteStaging#CanViewImageInManualCollectionViaAPAfterPublish
DepotRemoteStagingDM#CanViewImageInDynamicCollectionViaAPAfterFriendlyURLIsUpdated

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@AliciaGarciaGarcia, changes applied as we talked about

**Comment by AliciaGarciaGarcia** [comment]
ci:test:staging

**Comment by AliciaGarciaGarcia** [comment]
ci:test:headless-staging

**Comment by jkappler** [comment]
ci:report:61344610

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
