### PR TITLE
LPD 28315 revert

### PR DESCRIPTION
**Pull request by jkappler**
Original reverted PR #5555 

@ambrinchaudhary, @boton, @Mikellorza

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:report:22824827

**Comment by Mikellorza** [comment]
This PR reverts the remove FF of LPD-15596 that enabled the functionality to publish the content with permission appearing a modal when the user clicked on publish button, so, the errors are not related with the PR but it values to know how many errors are failing in order to help fixing errors in this other [PR](https://github.com/liferay-content-management/liferay-portal/pull/5596). So, let's test stable suite in order to move forward.

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
