### PR TITLE
LPD-28898

### PR DESCRIPTION
**Pull request by Mikellorza**
Sending PR again because of https://github.com/brianchandotcom/liferay-portal/pull/151780#issuecomment-2192471426 

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28898

There is an error when we are adding an image using copy paste and we should take into account when we are parsing it using creole parser. So, this PR include the necessary  code to perform it. 

# How am I fixing it?

1. Take into account when we are parsing xhtml for image nodes that including images content in base64.
2. Take into account in creole ckeditor when we are parsing images in base64. I sent a [PR to frontent infra team](https://github.com/liferay-frontend/liferay-portal/pull/4272) to review that part of code but I also included here in order to do a functional test. 

# How can you verify that it works?

Run included tests and follow the steps to reproduce the LPD bug.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:wiki

**Comment by Mikellorza** [comment]
ci:test:wiki

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@Mikellorza Can you do the forward if wiki the test failures are unrelated?

**Comment by Mikellorza** [comment]
ci:report:27331537

**Comment by Mikellorza** [comment]
ci:report:27331537

**Comment by Mikellorza** [comment]
ci:test:wiki

**Review by ambrinchaudhary — APPROVED** [review]
Frontend changes were previously approved.

**Comment by Mikellorza** [comment]
ci:report:27495530

**Comment by Mikellorza** [comment]
After seeing report there are not unique failures for this PR. So let's move to Brian.

**Comment by Mikellorza** [comment]
ci:forward

**Pull request closed without merging**
