### PR TITLE
LPD-37583 Hide wiki  from custom fields, export import and staging, and workflow

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-37583

# How am I fixing it?

Hide wiki  from custom fields, export import and staging, and workflow

# How can you verify that it works?

Run included tests

### CODE REVIEW

**Review by jkappler — CHANGES_REQUESTED** [review]
@Mikellorza, what we talked about. Tests + companyId

**Comment by Mikellorza** [comment]
Hi @jkappler ,

I' ve already changed the test in order to enable FF each test in setUp and teardown method in order do do not affect to other tests. 

For the other hand, we have to wait for the headless [PR](https://github.com/liferay-headless/liferay-portal/pull/2328#issuecomment-2459737990) in order to change the isEnabled method to add the companyId, since it makes more sense for it to be like this.

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
@Mikellorza, ready to be forwarded when you see fit :heart_eyes_cat:

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:65766656

**Comment by Mikellorza** [comment]
There are some failing tests related to this PR but it does not make sense, so let's run relevant suite again.

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:68004889

**Comment by Mikellorza** [comment]
There is no unique failures on relevant suite execution. So, we are ready to move forward to brian.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
