### PR TITLE
LPD-19082 Index Asset Vocabulary Ids for assets

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPD-19082)

Index vocabularyIds just as we do with categories

## Notes:

* We cannot do an early return when there are no categories, because otherwise the property won't be set and searching will fail
* It's not behind a feature flag since it's only adding information to the index
* There will be a follow up PR with logic for searching the vocabularies and the related test

## Change summary:

* Refactor AssetCategoryDocumentContributor so that we call the database only once instead of 3 times when retrieving the vocabularies
* Add assetVocabularyIds and assetInternalVocabularyIds to the index
* New field for assetInternalVocabularyIds
* Adapt existing test

## Test Scenario 1

* Create a new site
* Create a new internal vocabulary and add a category to it
* Create a new public vocabulary and add a category to it
* Create a new web content and assign the categories to it
* Query the index, you will see the two new properties indexed

## Test Scenario 2

* Run the provided integration test

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
I just realized that maybe a semver/baselane on portal-kernel is needed

**Comment by jkappler** [comment]
another one 😢

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
@AliciaGarciaGarcia there have been changes since yesterday, will push and forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@AliciaGarciaGarcia, done, thanks again ❤️

**Comment by jkappler** [comment]
ci:report:2545356524

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Test don't seem to be related, will run relevant again to compare results

**Comment by jkappler** [comment]
ci:report:2546076031

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
@AliciaGarciaGarcia, no unique failures were found the second time, so forwarding it

**Pull request closed without merging**
