### PR TITLE
LPD-27779 Add ctCollectionId to query filters

### PR DESCRIPTION
**Pull request by adolfopa**
https://liferay.atlassian.net/browse/LPD-27779
https://liferay.atlassian.net/browse/LPD-27790

Some queries should restrict updates by ctCollectionId, but they're not taking that column into account.

# How am I fixing it?

By adding the ctCollectionId as an additional filter to the queries.

# How can you verify that it works?

This PR includes two integration tests, one per upgrade process.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:upgrade

**Comment by adolfopa** [comment]
No unique failures.

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:upgrade

**Comment by adolfopa** [comment]
ci:report:79117669

**Comment by adolfopa** [comment]
No unique failures in the upgrade suite.

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
