### PR TITLE
LPD-30376 Unable to delete more than one selected translations of a Web Content

### PR DESCRIPTION
**Pull request by balazssk**
# What is this trying to solve?
https://liferay.atlassian.net/browse/LPD-30376
Delete translation Web Content action can't delete more than 1 translation at once

# How am I fixing it?
By fixing the format of languageIds submitted in the form

# How can you verify that it works?
You can run the [playwright test](https://liferay.atlassian.net/wiki/spaces/ENGR/pages/2729705766/Writing+tests+with+Playwright#How-to-run-tests) from <source-root>/modules/test/playwright via
```npm run playwright -- test -g 'LPD-30412: This is a test for deleting multiple translations from a web content'```

You can find the manual steps described in https://liferay.atlassian.net/browse/LPD-30376.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:playwright

**Comment by balazssk** [comment]
checking [this](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1154460/testReport/journal-web_journalArticle.spec/ts/LPD_30412__This_is_a_test_for_deleting_multiple_translations_from_a_web_content/) failure

**Comment by balazssk** [comment]
The [new test](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/632238/testReport/journal-web_journalArticle.spec/ts/LPD_30412__This_is_a_test_for_deleting_multiple_translations_from_a_web_content/) no longer fails

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:playwright

**Comment by adolfopa** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Seem unrelated.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
