### PR TITLE
LPD-44952 Update paths to not be dependent on text as this will fail in different locales (LocalizationWithSites#ViewPortletInteractWithLocalization)

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-44952

# How am I fixing it?

The paths for the updated publish button in Web Content are hard coded to use English text. This fails if the test changes the locale and tries to publish an article. These changes update the paths to find the buttons despite the locale.

I would assume the other macros would need to be updated as well (eg publishExistingWCArticleWithPermissions, scheduleExistingWCArticleWithPermissions) but my failing test didn't go through these methods so I didn't have a good way to test to ensure they were working properly.

# How can you verify that it works?

In the root folder run `ant -f build-test.xml run-selenium-test -Dtest.class=LocalizationWithSites#ViewPortletInteractWithLocalization`

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:site-management

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
Hi @jonathanmccann, 
thank you very much for this fix! Changes looks good, but I want to review carefully the `ci:test:content-management` failures (it could be just that they point to our current failures, we have several...), so I will do that on Monday. 

> I would assume the other macros would need to be updated as well (eg publishExistingWCArticleWithPermissions, scheduleExistingWCArticleWithPermissions) but my failing test didn't go through these methods so I didn't have a good way to test to ensure they were working properly.

I will also check and fix those, thanks!

**Comment by jonathanmccann** [comment]
@ambrinchaudhary Thank you for reviewing this! The Site Management suite looks good, those are known failures. No rush on this one, I know you all are busy.

**Comment by ambrinchaudhary** [comment]
Hey @jonathanmccann, 

It turns out that this test is finally fixed by https://github.com/liferay-content-management/liferay-portal/pull/6205/files (that is why there are conflicts) and it is [passing now on CI](https://testray.liferay.com/#/project/35392/cases/157753). 

The solution implemented is not that bad (although there is a new macro), because I feel that relying on texts is more eligible and could be more robust than checking for icons and classes. What do you think?

**Comment by jonathanmccann** [comment]
@ambrinchaudhary That's great! Thanks @marcogalluzzi for your work on it.

I'll go ahead and close this one out.

**Pull request closed without merging**
