### PR TITLE
LPD-28315 and LPD-29163 - FF removal and poshi fixes

### PR DESCRIPTION
**Pull request by gergelyszalay**
This is the rebased version of https://github.com/liferay-content-management/liferay-portal/pull/5634.

Also included fix for: https://liferay.atlassian.net/browse/LPD-29191 (Tests are already existing, for this issue. that is how discovered ).

Added an extra check for the save button, to check if it is editing the default values of a structure.

To check if its working: 
Create a structure, edit default values, save (only should be there save button, not a dropdown with publish with permission)

Thanks!

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Comment by gergelyszalay** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
Playwright errors seem to be related.

**Comment by gergelyszalay** [comment]
@adolfopa thanks for checking, I fixed the pw tests(found 2 not related failing in it)

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1327401_5517

**Comment by adolfopa** [comment]
ci:reevaluate:1327401_5517

**Comment by ambrinchaudhary** [comment]
There are still many failures in the last run for `ci:test:content-management` (2 days ago), see https://testray.liferay.com/#/project/35392/routines/45357/build/59461786 

Let's try again to see the last results

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by gergelyszalay** [comment]
ci:test

**Comment by gergelyszalay** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_14170

**Comment by gergelyszalay** [comment]
ci:test:

**Comment by gergelyszalay** [comment]
ci:test:

**Comment by gergelyszalay** [comment]
ci:test:

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
@gergelyszalay Sorry, rebase errors :-(

**Comment by gergelyszalay** [comment]
ci:test:content-management

**Comment by gergelyszalay** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:data-engine

**Comment by jkappler** [comment]
ci:test:headless-staging

**Comment by gergelyszalay** [comment]
ci:test:page-management

**Comment by gergelyszalay** [comment]
ci:test:headless-staging

**Comment by gergelyszalay** [comment]
ci:test:headless-staging

**Comment by gergelyszalay** [comment]
ci:test:page-management

**Comment by gergelyszalay** [comment]
ci:test:page-management

**Comment by gergelyszalay** [comment]
ci:test:headless-staging

**Comment by gergelyszalay** [comment]
ci:test:page-management

**Comment by gergelyszalay** [comment]
ci:test:page-management

**Comment by gergelyszalay** [comment]
ci:test:data-engine

**Comment by gergelyszalay** [comment]
ci:test:content-management

**Comment by gergelyszalay** [comment]
Closing this PR and opening a new one, for better visibility

**Pull request closed without merging**
