### PR TITLE
LPD-37869 change friendlyUrlToggle locator for href

### PR DESCRIPTION
**Pull request by gergelyszalay**
This PR is from:
https://github.com/brianchandotcom/liferay-portal/pull/154828

Rebased ✔️ 

Thanks!

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Review by boton — CHANGES_REQUESTED** [review]
@gergelyszalay we have some rebase problem here, can you rebase it?

---

image

And please note the unique failure in the report. Is it related to the change, or is it flaky test?

**Review by boton — APPROVED** [review]
I'm going to forward this but we need to take a look at [Check alert message of duplicated friendly URL in french](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1019753//testReport/journal-web_journalArticle.spec/ts/Check_alert_message_of_duplicated_friendly_URL_in_french)


image

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
