### PR TITLE
LPD-37193 fix POSHI test after removal of title on problem message

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-37193 fix POSHI test after removal of title on problem message

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-37193

After https://liferay.atlassian.net/browse/LPD-35339 some changes were made, one of them is that now the exceptions do not have the title. On some cases we are checking that the title (exception message) were the correct.

# How am I fixing it?

Changing what we check on the assert, the status, no the title

# How can you verify that it works?

Run the included automated tests.

# Commits
- **LPD-37193 actually there is no title on the response message because NotFoundExceptionMapper return null on the title**
- **LPD-37193 reuse method**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management-headless

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:headless

**Comment by AliciaGarciaGarcia** [comment]
ci:report:20069106

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia I'll let you do the forward when the tests finish.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
