### PR TITLE
LPD-19549 doAsUserId param is included in document URL when selected from Repository Browser

### PR DESCRIPTION
**Pull request by marcogalluzzi**
https://liferay.atlassian.net/browse/LPD-19549

Upon impersonation, when using an Item Selector to retrieve the URL of a DM file, the parameter `doAsUserId` is also returned. I could not analyze all places where an Item Selector is used, but it seems to be incorrect in most cases.

This problem started after the fix done back in [August, 2023](https://liferay.atlassian.net/browse/LPS-193614) where the `doAsUserId` parameter was added to all DM links, see PR #4598 . After some discussion about its correctness I believe it is correct in most cases. For cases where the `doAsUserId` parameter is not needed, like the current problem with the Item Selector, I've created a new method with an additional parameter.

### CODE REVIEW

**Review by robertoDiaz — CHANGES_REQUESTED** [review]
As we have been talking I do not like this solution very much:

1. Seems to be inconsistent. Other class methods do not use the `addPreservedParameters`.
2. Forces a major version change
3. Requires modify the API
4. Other use cases could also be silently broken and we'll have to fix them anyway

From my perspective the best solution is rollback the offending logic and use the addPreservedParameters in upper layers (for example, in the original case that caused this regression in the method client). I know that we could also left broken cases that require this parameters, but current solution seems a little bit overkill to me.

**Comment by marcogalluzzi** [comment]
Thanks for your feedback @robertoDiaz

> 1. Seems to be inconsistent. Other class methods do not use the `addPreservedParameters`.

What do you mean? What other class methods use instead? `addPreservedParameters` is not correct?

> 2. Forces a major version change

I don't understand why a major version change is forced when I'm just adding a new method to the API, I'm not breaking an existing one.

> 3. Requires modify the API

I'm just adding a new method

> 4. Other use cases could also be silently broken and we'll have to fix them anyway

The use cases I've tested need the `doAsUserId` parameter.  I haven't found other uses cases that don't need this parameter. This is why I would prefer not to revert the initial change, and fix it whenever new related bugs appear.

If I revert the initial change we have the opposite situation, where the current bug is fixed, however I've to fix at least 3 places (upper layer) where the parameter `doAsUserId` is needed, and finally we have to fix other places as related bugs appear.

I would like to have more opinions (@adolfopa) on this matter to take a final decision.

> 
> From my perspective the best solution is rollback the offending logic and use the addPreservedParameters in upper layers (for example, in the original case that caused this regression in the method client). I know that we could also left broken cases that require this parameters, but current solution seems a little bit overkill to me.

**Comment by robertoDiaz** [comment]
Hi @marcogalluzzi 

> What do you mean? What other class methods use instead? addPreservedParameters is not correct?

In this class we are generating urls for DL, but this it the only method that is using "addPreservedParameters". It makes me wonder why do others URL doesn't require this parameters at this API level.

> I don't understand why a major version change is forced when I'm just adding a new method to the API, I'm not breaking an existing one.

I only had to check the baseline: https://github.com/liferay-content-management/liferay-portal/pull/5227/commits/21430c87f8977f72fd6687032c78de8803be10e3 to see the major change.

> I'm just adding a new method

This is an API modification (addition), and as seem in the previous point forces the version bump.

> > The use cases I've tested need the doAsUserId parameter. I haven't found other uses cases that don't need this parameter. This is why I would prefer not to revert the initial change, and fix it whenever new related bugs appear.
> 
> If I revert the initial change we have the opposite situation, where the current bug is fixed, however I've to fix at least 3 places (upper layer) where the parameter doAsUserId is needed, and finally we have to fix other places as related bugs appear.

I feel than adding a code and force fixing single cases is the same as not adding it an fix other single cases. In any case we'll have to fix that in multiple places.

From my perspective it also mean that a common and general solution could not be done (or is not worthy), so force a new version and having to modify (potentially) the client api calls seems overkill to me.

At this point due the behavior change, we have broken at least one of our features, and POTENTIALLY customers customizations forcing them to change their implementations. Remember that this is the recommended method to generate urls to documents.

> I would like to have more opinions

Agree, I've also consult @jkappler before adding my first comment as second opinion about this and we both agree about the revision. He didn't add any comment since he didn't want to add more noise.

I've asked him to do so.

Regards.

**Comment by robertoDiaz** [comment]
Hey @jkappler 

We had a call together with @adolfopa and agreed a solution.

You opinion is not needed anymore ( :D )

**Comment by jkappler** [comment]
@robertoDiaz 😢

**Pull request closed without merging**
