### PR TITLE
LPD-18328 Arabic localization causes issue with Web Content filtering on date with API

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPD-18328)

There are issues when filtering with dates when using the headless API

## Change summary:

* Don't use DateFormatFactoryUtil since it will expect a locale, use SimpleDateFormat

## Test Scenario

* Follow the steps in the ticket

### CODE REVIEW

**Comment by NemethNorbert** [comment]
I tested the solution and now we return the article created in both US and Arabic locale

**Comment by 4lejandrito** [comment]
Much better!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:report:2542348248

**Comment by jkappler** [comment]
There's no unique failure from what I see in the test run

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
