### PR TITLE
LPD-38011 Refactor BlogsPostingImageResourceImpl (2nd try)

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38011

This [suggestion](https://github.com/brianchandotcom/liferay-portal/pull/154293#issuecomment-2359233798) comes from Brian Chan.

I'm refactoring the class `BlogsPostingImageResourceImpl` to avoid duplicated logic related to the access of `_portletFileRepository` that already exists in `BlogsEntryLocalServiceImpl`. 

:hot_pepper:   **NEW**: There are 2 additional commits requested by bchan, this is removing one `addAttachmentFileEntry` method in LocalService - _if an existing method exists, just change it_ -

# How am I fixing it?

Now all the logic is stored in one place: `BlogsEntryLocalServiceImpl`.

# How can you verify that it works?

`cd modules/apps/headless/headless-delivery/headless-delivery-test`
`gw tI --tests BlogPostingImageResourceTest`

`cd modules/apps/blogs/blogs-test`
`gw tI --tests "*testAddAttachmentFileEntryWith*"`

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
