### PR TITLE
LPD-17296 Adds bulk permission action for web content admin

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPD-17296)

The goal behind the changes is to allow to have bulk permission changes in web content admin view

## Change summary:

* Adds a new action command in the toolbar to change permissions in bulk
* Adds resource command to change articleIds to resourcePrimKeys and redirect to permissions taglib
* Adapt props transformer to show the required modals

## Test Scenario

* Enable Feature Flag for LPD-16469
* Go to Content & Data
* Create several Web Contents
* Select the required Web Contents and press permissions in the toolbar
* Change some permissions

When selecting individual permissions, the previous selected ones will be shown

## Notes

* It works with pagination
* A warning is shown when selecting more than 200 articles

Bulk

### CODE REVIEW

**Comment by jkappler** [comment]
@Mikellorza moved here

**Comment by jkappler** [comment]
@ambrinchaudhary, frontend changes were reviewed by @victorg1991, still, feel free if you want to take a look ❤️. I will apply his suggestion to the bulk upload from DM in the follow up PR

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Review by adolfopa — APPROVED** [review]

**Review by Mikellorza — CHANGES_REQUESTED** [review]
Hey @jkappler ,

I have seen that it is not working when paginating, I am seeing a javascript error when I select some content of a page and then go to another page and select some more.

image

Please if you can take a look, thanks mate

**Comment by jkappler** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Review by Mikellorza — APPROVED** [review]
LGTM!!!

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by jkappler** [comment]
ci:report:2538515293

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
Tests failures are not related to the changes

**Pull request closed without merging**
