### PR TITLE
LPD-35730 Fix A non-localizabled field is disabled in journalArticle...

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi,

May I ask to review this PR.

It is an additional formatting for https://github.com/liferay-content-management/liferay-portal/pull/5840, missed the @ from before the tag for the fix.

Thank you in advance!

BR,

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
Playwright errors seem to be unrelated.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
