### PR TITLE
LPD-20173 Keep source and target languages when concurrent user error is shown

### PR DESCRIPTION
**Pull request by Mikellorza**
bugs:

1. https://liferay.atlassian.net/browse/LPD-20173
2. https://liferay.atlassian.net/browse/LPD-20176

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:reevaluate:1277401_11396

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:reevaluate:1367401_5483

**Comment by Mikellorza** [comment]
ci:report:2550714243

**Comment by Mikellorza** [comment]
Failed test is not related with the changes of this PR. Other tests did not run because of : "failed prior to running test" , see thread in the slack private channel : https://liferay.slack.com/archives/C19PWQ74J/p1710453746788589. 

So, let's move forward.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
