### PR TITLE
LPD-28007 Revert "LPD-17744 Disable Iframe sanitizer at setup"

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-28007 Investigate "ElementNotFoundPoshiRunnerException: Element is not present at "//span[contains(@class,'custom-control-label-text') and contains(.,'Enabled')"

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28007

# How am I fixing it?

The fix for LPD-17744 was causing more test to fail than fix so revert the fix

# How can you verify that it works?

Run the included automated tests.

# Commits

This reverts commit eeff6825a4cc4d46dc56aec929bd18162a8e3856.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Review by NemethNorbert — APPROVED** [review]
LGTM

**Comment by AliciaGarciaGarcia** [comment]
ci:report:15700690

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
