### PR TITLE
LPD-21979 DM Filter&Search put under Feature Flag

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Previously approved in https://github.com/liferay-content-management/liferay-portal/pull/5297 

Missed FF for the epic https://liferay.atlassian.net/browse/LPD-11313.
The only story affected (is the only only developed) is https://liferay.atlassian.net/browse/LPD-6878

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
SF error in other component (Commerce) that I'm not sure how to fix 🤦‍♀️ . I will wait for an update in upstream and get back to this pull once it is fixed.

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
