### PR TITLE
LPD-41435 Hide wiki from widget templates

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

This pr depends on [this other one](https://github.com/liferay-page-management/liferay-portal/pull/16532/commits) in page-management repository, so, we can't move forward until page-management pr is on master.

https://liferay.atlassian.net/browse/LPD-41435

# How am I fixing it?

Hide wiki  from widget template creation.

# How can you verify that it works?

Run included tests

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
Putting on hold until parent PR is merged.

**Comment by Mikellorza** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1387401_11408

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:65283776

**Comment by Mikellorza** [comment]
ci:report:65283776

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:65760726

**Comment by Mikellorza** [comment]
There are not unique failures, so we are ready to move forward.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
