### PR TITLE
LPD-18667 Remove public render parameter for nodeId

### PR DESCRIPTION
**Pull request by SamZiemer**
https://liferay.atlassian.net/browse/LPD-18667

With nodeId being a public render parameter it is stored in the request as "p_r_p_http://www.liferay.com/public-render-parameters/wiki_nodeId" rather than "nodeId". Do we still need to have nodeId as a public render parameter? Do the other public render parameters in this same file need to be adjusted as well?

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@SamZiemer I don't understand the fix. How does removing the prp fix the issue?

Also, is the parameter renaming (from `nodeId` to `wiki-nodeId`) "automatic"? That looks like a bug to me. If you declare certain parameter to be public, changing its name defeats its purpose. In any case, I'm not aware of anything using these public parameters (@robertoDiaz do you know if there's anything using them?). If there aren't any usages, I think we should remove them, as they're broken anyway.

**Comment by SamZiemer** [comment]
I am going to close this. I revisited and realized I can just use the action request to get the nodeId instead. I initially thought nodeId was not available as a parameter in the actionRequest which is why I went this route. I will resend with a new PR.

**Pull request closed without merging**
