### PR TITLE
LPD-38995 [playwright] Fix test 'Web Content version, status and ID are shown and updated after auto save'

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38995

Fix test 'Web Content version, status, and ID are shown and updated after autosave' (journalArticleAutosave.spec.ts) 

# How am I fixing it?

Updating the broken locator and use the new utility openFieldset

# How can you verify that it works?

1. Go to /modules/test/playwright
1. Run npm install (setup)
1. Run npm run `npm run playwright test -- -g @LPD-32874` to run the test

# Before the PR

image

# After the PR (launched 10 times to avoid flaky results)

```sh
npm run playwright test -- -g @LPD-32874 --repeat-each 10 --reporter list
```

image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
Test passes in the CI https://testray.liferay.com/#/project/35392/routines/45357/build/37870963/case-result/37876204

image

image

**Comment by boton** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
