### PR TITLE
LPD-21632 & LPD-21634 Ellipsis menu appear on default language

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket 1](https://liferay.atlassian.net/browse/LPD-21632)  
[Link to ticket 2](https://liferay.atlassian.net/browse/LPD-21634)

## Steps

*   Activate FFs 'LPD-11253' and 'LPS-114700' 
*   **Case 1**
    *   Go to Content & Data > Create a Web Content
    *   Asset Translations options ellipsis is not present

*   **Case 2**
    *   Go to Content & Data > Create a Web Content
    *   Change the language to a different one from the default
    *   Click on the Translations Options ellipsis
    *   See Reset Translations button is disabled

### CODE REVIEW

**Comment by DiegoHu97** [comment]
\-     ci:test:\*\*sf\*\*

**Comment by DiegoHu97** [comment]
ci:test:suite

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by DiegoHu97** [comment]
ci:report:2560383620

**Comment by DiegoHu97** [comment]
ci:test:stable

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Review by NemethNorbert — APPROVED** [review]
Hey @DiegoHu97 ,

I reviewed the changes and everything looks good to me. Great job!

Thanks!

**Pull request closed without merging**
