### PR TITLE
Revert for #5555 LPD-28315 Release FF - Removal: Reorganizing permissions and schedule configuration on Web Content Editor 

### PR DESCRIPTION
**Pull request by boton**
Original reverted PR #5555 

- **Revert "LPD-28315 Regen"**
- **Revert "LPD-28315 Delete smoke test and add a test to add a web content and see if it exist in the content management list"**
- **Revert "LPD-28315 Change way to reach element with testId from getByTestId to css selector with attribute data-testid"**
- **Revert "LPD-28315 Delete wrong FF LPS-141392"**
- **Revert "LPD-28315 SF delete FF LPD-15596"**
- **Revert "LPD-28315 Fix test, take into account that the publish button it is a drop-drown with two buttons."**
- **Revert "LPD-28315 Delete language keys"**
- **Revert "LPD-28315 Delete FF LPD-15596 from the code"**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:content-management

**Comment by boton** [comment]
/ cc @Mikellorza

**Comment by boton** [comment]
ci:test:content-management

**Comment by boton** [comment]
I relaunched it to double-check but looks like it's working

https://testray.liferay.com/#/project/34754/routines/34756/build/22284827?filter=%7B%22dueStatus%22%3A%5B%22FAILED%22%5D%7D&filterSchema=buildResults&page=1&pageSize=150

image

**Comment by jkappler** [comment]
ci:report:22532771

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by jkappler** [comment]
https://github.com/liferay-content-management/liferay-portal/pull/5607

**Pull request closed without merging**
