### PR TITLE
LPD-15878 Add status user name as wiki notification variable (and show it in DL as well)

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:reevaluate:1357401_5282

**Comment by robertoDiaz** [comment]
ci:reevaluate:1357401_5282

**Comment by robertoDiaz** [comment]
ci:report:2532815358

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:report:2535509117

**Comment by robertoDiaz** [comment]
Failures are unrelated

**Comment by robertoDiaz** [comment]
ci:forward:force

**Comment by robertoDiaz** [comment]
ci:forward:force

**Pull request closed without merging**
