### PR TITLE
LPD-28046 Create endpoint for updating Document Shortcut

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28046

Adding PUT and PATCH methods to the DocumentShortcut endpoint

# How am I fixing it?

Adding new methods to the schema definition, building and implementing the PUT method (the PATCH method is automatically created).

I've also refactored the tests. There was unnecessary code overriding automatically created tests.

NOTE: this code is created on top of PR #5525 by @jonathanmccann . It cannot be forwarded until this PR is merged.

# How can you verify that it works?

Run `DocumentShortcutResourceTest` integration tests.

Call the endpoint directly by accessing the API page.

### CODE REVIEW

**Comment by jkappler** [comment]
@marcogalluzzi, all looks good. One think that can be added in future tests would be for invalid values, such as folder or target document. I don't think it would make sense to test put/post for invalid shortcuts

So for me, the PR would be good to go.

I'll leave @jonathanmccann decide on how to proceed ❤️

**Review by jkappler — APPROVED** [review]

**Comment by jonathanmccann** [comment]
The changes look good.

My only concern is that the `viewableBy` parameter does not seem to work. However, it doesn't look to work for any of the other assets I've tried with either (DLFolder, DLFileEntry, etc.)

In `addFileShortcut` we call `addFileShortcutResources` to add the permission initially but in `updateFileShortcut` we don't have a similar call to update the permissions - https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLFileShortcutLocalServiceImpl.java#L89-L99

Like I said it happens everywhere so perhaps this change would be better suited in a different task to ensure the permissions are updated for all models.

**Review by jonathanmccann — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
Hi @jonathanmccann you are right. I also saw that: the `viewableBy` parameter is only used during creation. I will ask POs if it's okay or it needs to be addressed (in a separate issue).

**Comment by marcogalluzzi** [comment]
Rebased onto master, no changes needed, forwarding.

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
