### PR TITLE
LPD-33784 Add Test.

### PR DESCRIPTION
**Pull request by manuelRives**
### What is this trying to solve?
https://liferay.atlassian.net/browse/LPD-33784 Adding missing test from LPP-52474
### How am I fixing it?
Creating a new functional test that follows these steps:
1. Create a widget page
2. Add an Asset Publisher to this page
3. Open the Asset Publisher configuration popup, set the Asset Selection as Dynamic and save configuration.
4. In the "+" button on this Asset Publisher add a Basic Document
5. Sets a name and click on publish
### How can you verify that it works?
1. Running the test

### CODE REVIEW

**Review by robertoDiaz — APPROVED** [review]
LGTM

**Comment by robertoDiaz** [comment]
ci:content-management

**Comment by manuelRives** [comment]
ci:test:content-management

**Comment by robertoDiaz** [comment]
ci:test:content-management

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
