### PR TITLE
LPD-34653 Fix test failures in ContentPageReviewUpgrade#ViewContentPageReviewArchive

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-34653

Fix the following tests:

* LocalFile.ContentPageReviewUpgrade#ViewContentPageReviewArchive72101
* LocalFile.ContentPageReviewUpgrade#ViewContentPageReviewArchive73101

# How am I fixing it?

Removing the instruction `PageEditor.gotoTab(tabName = "Browser")`  incorrectly added in LPD-30896.

# How can you verify that it works?

Run:

* `ant -f build-test.xml run-selenium-test -Dtest.class=ContentPageReviewUpgrade#ViewContentPageReviewArchive72101`
* `ant -f build-test.xml run-selenium-test -Dtest.class=ContentPageReviewUpgrade#ViewContentPageReviewArchive73101`

Note: the associated data folder and db dump should be imported first.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:upgrade

**Review by adolfopa — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:report:71428269

**Comment by marcogalluzzi** [comment]
The failing tests are unrelated

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
