### PR TITLE
LPD-26290 dm preview fixed tbar [ee-ts]

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPD-26290 

**Steps to test it:** 
1. Go to Content & Data > Documents and Media > Provided by Liferay > Open an Image
2. In the browser console > Inspect the page > Click on "Toggle device toolbar" > Change dimensions for "iPhone 14 Pro Max" for example.
3. Scroll down the page 

https://github.com/liferay-content-management/liferay-portal/assets/8373764/b6ed29cc-aa51-4c27-b611-c0c19f5fcc00

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
hey @boton @NemethNorbert @DiegoHu97 will some of you have bandwitch to review this today? 🙏

**Comment by DiegoHu97** [comment]
Works fine @ambrinchaudhary :tada: !

**Review by DiegoHu97 — APPROVED** [review]

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by boton** [comment]
Ty @DiegoHu97 ❤️

**Pull request closed without merging**
