### PR TITLE
LPD-17066 Reuse injected instead use Util or reInject

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
When doing the displayDate task I realized that some of the test were failing on my local (NPE on the injected class) and were extension of a base class that have an injected class that can be reused

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
