### PR TITLE
LPD-36634 Update the GroupERC on publication if the group is a Staging group

### PR DESCRIPTION
**Pull request by robertoDiaz**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-36634

There's an error when showing published assetListEntries and the asset publisher is not showing them

# How am I fixing it?

I'm updating the portal properties so they point to a published group instead of a staged one

# Why doesn't this include any test?

There are already tests that cover this (e.g. a regression bug or a library upgrade.):

- DepotCollections#CanBePublishedViaRemoteStaging
- DMRemoteStaging#CanViewImageInManualCollectionViaAPAfterPublish
- DepotRemoteStagingDM#CanViewImageInDynamicCollectionViaAPAfterFriendlyURLIsUpdated

### CODE REVIEW

**Comment by adolfopa** [comment]
@robertoDiaz Can you update the description? This fixes some test failures, so we should state that so that the PR isn't rejected. See https://github.com/liferay-content-management/liferay-portal/pull/5886 for an example of what you should do here.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
cc/ @ealonso

**Comment by robertoDiaz** [comment]
> @robertoDiaz Can you update the description? This fixes some test failures, so we should state that so that the PR isn't rejected. See #5886 for an example of what you should do here.

Sure @adolfopa I forget it! I'll do that.

Thank you for the heads up!

**Comment by robertoDiaz** [comment]
@adolfopa , done!

**Comment by adolfopa** [comment]
ci:report:16103818

**Comment by adolfopa** [comment]
Tons of publications tests failing. Retrying.

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by robertoDiaz** [comment]
ci:test:content-management

**Comment by robertoDiaz** [comment]
Repeating the test since some of them do not fail in local.

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
