### PR TITLE
LPD-27932 JournalArticleSmallImageSourceUpgradeProcessTest failing in oracle db due to a SQL syntax error.

### PR DESCRIPTION
**Pull request by jkappler**
JournalArticleSmallImageSourceUpgradeProcessTest failing in oracle db due to a SQL syntax error

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-27932)

JournalArticleSmallImageSourceUpgradeProcessTest fails for Oracle DB 

# How am I fixing it?

Change the query so that it works for oracle an other DBs

# How can you verify that it works?

Launch the JournalArticleSmallImageSourceUpgradeProcessTest in several DB (Oracle would be better since it's were the problem is visible)

# Why doesn't this include any test?

Tests was already present and was failing for Oracle DB, so no more tests are needed

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:upgrade

**Comment by jkappler** [comment]
@manuelRives

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:upgrade

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Waiting for the results of ci test upgrade before forwarding.

**Comment by jkappler** [comment]
ci:report:28618716

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:28740606

**Comment by jkappler** [comment]
ci:report:28740606

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
