### PR TITLE
LPD-24376 Adaptive media task is not taking into account web content images

### PR DESCRIPTION
**Pull request by Mikellorza**
bug: https://liferay.atlassian.net/browse/LPD-24376

### CODE REVIEW

**Review by AliciaGarciaGarcia — COMMENTED** [review]
if I execute all the test on the adaptive-media folder, the new test are failing, thats why I sent the relevant. Wait for the results.

maybe is a because the execution of a previous test is making fail the new ones, or not

**Comment by AliciaGarciaGarcia** [comment]
c:test:relevant

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
see if all the references are needed or not.

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]
The code seems ok
Review failures, if relevant fix

**Comment by Mikellorza** [comment]
ci:forward

**Pull request closed without merging**
