### PR TITLE
LPD-27556 Web content displayed in a DPT is not being expired

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LPD-27556

# What is this trying to solve?

Avoid inconsistence data affect to all article expirations/publications.  

1. Add a transaction for all changes behind expiration or publication perform actions in order to rollback the data in case it fails. 
2. Catch exception to allow performing other expiration or publication tasks.
3. Delte unnecessary sentence for actionable query because now all actions behind perform action is being executed behind a transaction: 

```
 indexableActionableDynamicQuery.setTransactionConfig(
			DefaultActionableDynamicQuery.REQUIRES_NEW_TRANSACTION_CONFIG);
```

# How am I fixing it?

Adding catch sentence in perform action method of actionable query and also add a Transaction using TransactionInvokerUtil.

# How can you verify that it works?

Run the included tests.

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:report

**Comment by Mikellorza** [comment]
ci:report:11420130

**Comment by Mikellorza** [comment]
ci:report:11532996

**Comment by Mikellorza** [comment]
ci:forward

**Pull request closed without merging**
