### PR TITLE
LPD-36686 add external reference code support for assetTag entity

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-36686 Technical Task | Add ExternalReferenceCode to Tags

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-36686

As a systems administrator I want to be able to use an External Reference Code of a tag during the import/export process so that my data is migrated accurately without any duplication or mismatches

# How am I fixing it?

The first step is to add the support on the service for the external reference code field on the AssetTag entity. Then, modify the addTag and updateTag methods to ensure that the erc can be added by the user if it is wanted.

# How can you verify that it works?

Run the included automated tests.

# Commits

- **LPD-36686 add external reference code field to AssetTag entity**
- **LPD-36686 buildService**
- **LPD-36686 upgrade process for the assetTag entity for external reference code**
- **LPD-36686 add test to check the new upgrade for the external reference code for AssetTag entity**
- **LPD-36686 modify addTag method to take into account the externalReferenceCode**
- **LPD-36686 modify updateTag method to take into account the externalReferenceCode**
- **LPD-36686 buildService**
- **LPD-36686 add externalReferenceCode parameter on addTag and updateTag calls as null**
- **LPD-36686 update the tag with the correct values**
- **LPD-36686 baseline**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:report:52449088

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:report:55430100

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:report:55430100

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:report:55430100

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:upgrade

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:report:56969738

**Comment by AliciaGarciaGarcia** [comment]
The only test failure that worried me was 


and the reason is a flacky reason that is something that with a random string can happens :D



Errors | testGroupValidSiteFriendlyURLI18nPath: java.lang.AssertionError: /web/enqqzoyf should not contain /en at org.junit.Assert.fail(Assert.java:89) at org.junit.Assert.assertTrue(Assert.java:42) at org.junit.Assert.assertFalse(Assert.java:65) at com.liferay.site.service.test.GroupServiceTest.testGroupValidSiteFriendlyURLI18nPath(GroupServiceTest.java:990) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
-- | --

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
