### PR TITLE
LPD-18491 Separate JournalTemplatesPage

### PR DESCRIPTION
**Pull request by sandrodw3**
Follow-up of https://github.com/liferay-content-management/liferay-portal/pull/5179

cc @Mikellorza @NemethNorbert

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:playwright

**Comment by sandrodw3** [comment]
Hey @Mikellorza @NemethNorbert it seems there's another flaky test, but not related to this PR 🥰

**Review by Mikellorza — APPROVED** [review]

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
@sandrodw3  see : https://github.com/liferay-content-management/liferay-portal/pull/5263

**Comment by Mikellorza** [comment]
ci:close

**Pull request closed without merging**
