### PR TITLE
LPD-29524 Use correct parameter name in order to search for keywords properly within the Message Boards widget

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-29524

Message Boards widget search does return correct results based on keywords

# How am I fixing it?

The name parameter was erroneously duplicated causing a mismatch between the front end and back end.

# How can you verify that it works?

Run `npm run test -- -g "LPD-29524"`

To test manually:

1. Add a Message Boards widget to the page
2. Add a new thread named test1
3. Add a new thread named test2
4. Using the Message Boards widget’s search box search for test1
5. Assert the test2 thread is also displayed

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:playwright

**Comment by AliciaGarciaGarcia** [comment]
ci:test:playwright

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1287401_9669

**Comment by ambrinchaudhary** [comment]
Failures not related with this pull

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
