### PR TITLE
LPD-19989 filter vocabularies

### PR DESCRIPTION
**Pull request by jkappler**
Checked here: https://github.com/liferay-search/liferay-portal/pull/1287#issuecomment-2010726358

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks again @BryanEngler!

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2552974823

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Comment by Mikellorza** [comment]
ci:forward:force

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
