### PR TITLE
LPD-40531 RELEASE BLOCKER: WC publish button disabled after required fields errors

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[Link to ticket ](https://liferay.atlassian.net/browse/LPD-40531) Publish button is disabled when publishing WC without title

> If we publish a WC with no title, the publish button is disabled even if we fill the title

# How I am fixing it
As soon as publish button is clicked, lock is activated (thus, publish button disabled), and in theory when the form is submitted, it is unlocked. This was introduced in https://github.com/liferay-content-management/liferay-portal/pull/5424/commits/42fef9803849f437f7878978746fea2b00f02d30
The problem is that when required fields are empty, the form is not submitted. I haven't found any conditional to unlock jut in that case, so I decided to unlock directly for all the cases. 

# How can be tested
You can follow the steps on the issue, or run `npm run playwright -- test -g 'LPD-40531' --reporter list`

```
npm run playwright -- test -g 'LPD-40531' --reporter list --repeat-each=5

> @liferay/playwright@1.0.0 playwright
> playwright "test" "-g" "LPD-40531" "--reporter" "list" "--repeat-each=5"


Running 5 tests using 1 worker

  ✓  1 [journal-web] › journal-web/journalArticleAutosave.spec.ts:741:1 › Web Content publish button is enabled after required error messages appear (31.1s)
  ✓  2 [journal-web] › journal-web/journalArticleAutosave.spec.ts:741:1 › Web Content publish button is enabled after required error messages appear (21.5s)
  ✓  3 [journal-web] › journal-web/journalArticleAutosave.spec.ts:741:1 › Web Content publish button is enabled after required error messages appear (21.4s)
  ✓  4 [journal-web] › journal-web/journalArticleAutosave.spec.ts:741:1 › Web Content publish button is enabled after required error messages appear (22.7s)
  ✓  5 [journal-web] › journal-web/journalArticleAutosave.spec.ts:741:1 › Web Content publish button is enabled after required error messages appear (23.9s)

  5 passed (2.3m)
```

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Review by DiegoHu97 — APPROVED** [review]
Works fine for me! :clap:

**Comment by DiegoHu97** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:report:56477937

**Comment by ambrinchaudhary** [comment]
```
Unique Failures
:dxp:apps:osb:osb-faro:osb-faro-web:packageRunTest
```

could not be related to this pull...

**Comment by ambrinchaudhary** [comment]
liferay/ci:test:stable

**Comment by DiegoHu97** [comment]
ci:test:stable

**Comment by DiegoHu97** [comment]
ci:forward

**Review by boton — APPROVED** [review]
Good enough to fix the bug.

I don't like the logic. We have a ton of logic to disable and enable the button in certain cases and after this change, we always enable it.

I think we need to create a task to follow up and invest some time in refactoring it.

Good job with the test 😄 , passes locally and in CI
image

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
