### PR TITLE
LPD-26964 Adds an integration test for LPS-158221 use case

### PR DESCRIPTION
**Pull request by lfbesada**
[LPD-26964](https://liferay.atlassian.net/browse/LPD-26964) Add a test for Whole page content is not visible while clicking on search result

# What is this trying to solve?

Adds an integration test for the use case: the WebContent in search results links to the Asset Publisher instead of WC. Ref: LPP-46545: Whole page content is not visible while clicking on search result

# How am I fixing it?
Adds the integration test JournalArticleAssetRendererTest.testGetURLViewInContextWithLayoutUuid

# How can you verify that it works?
Execute the test JournalArticleAssetRendererTest.testGetURLViewInContextWithLayoutUuid

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
@lfbesada ❤️

**Pull request closed without merging**
