### PR TITLE
LPD-35926 Fix tests broken by FF LPS-188058 removal

### PR DESCRIPTION
**Pull request by robertoDiaz**
### Fixing tests after the FF 'LPS-188058' removal

1. Poshi tests are modified to apply the new user interface
2. Disable and refactor KB playwright: This PR only fixes one test and deletes another obsolete test. Now two tests are failing but they are unrelated to these changes.

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:content-management

**Review by adolfopa — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:test:content-management

**Comment by boton** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
ci:test:content-management

**Comment by robertoDiaz** [comment]
This PR fixes 80+ tests 

forwarding

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
