### PR TITLE
LPD-32481 Add Order by Relevance option to the DL search in DPContext

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi,
May I ask to review this PR?

This is for https://liferay.atlassian.net/browse/LPD-32481.

**As a** content creator,

**I want** my document search results to be ordered by relevance,

**So that** the most pertinent results appear first.

**Requirements:**

New Ordering Option: Introduce a new option in the ordering selector for documents & media labeled “Relevance.” This option should appear the last one on the list.

Ordering by Relevance: When the “Relevance” option is selected, search results should be ordered with the most relevant results appearing first. The ascending/descending option should not appear.

Thanks in Advance!

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:sf

**Review by jkappler — APPROVED** [review]

**Review by DiegoHu97 — APPROVED** [review]
LGTM!

**Comment by DiegoHu97** [comment]
ci:test:playwright

**Comment by DiegoHu97** [comment]
ci:forward

**Pull request closed without merging**
