### PR TITLE
LPD-30577 change app_name with name of new credentials

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-30577 Update the Sharepoint authentication on CI

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-30577

After the update of the credentials on https://liferay.atlassian.net/browse/LRCI-4313 we should update the new credentials on the poshi test. On this case the app name

# How am I fixing it?

Changin the app name for the new one of the new credential

# How can you verify that it works?

Run the included automated tests.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sharepoint

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Everything looks fine, but I'm not doing the forward to give time for the sharepoint tests to complete.

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa that's the spirit!!

**Comment by AliciaGarciaGarcia** [comment]
ci:report:33330881

**Comment by AliciaGarciaGarcia** [comment]
ci:report:33330881

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sharepoint

**Comment by AliciaGarciaGarcia** [comment]
this makes no sense. re-lauching tests

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by adolfopa** [comment]
ci:reevaluate:1287401_9732

**Comment by AliciaGarciaGarcia** [comment]
ci:report:33486858

**Comment by AliciaGarciaGarcia** [comment]
the errors are strange, but the change is needed.

maybe this does not fix all the SharepointRest failures, but solves the authorization error

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
