### PR TITLE
LPD-31078 Cannot view image resources from fragment

### PR DESCRIPTION
**Pull request by jkappler**
Cannot view image resources from fragment

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-31078)

When adding folders to fragment resources through the repository browser, guest permissions are not set, so any guest user won't be able to see the resources in them

# How am I fixing it?

Adding an attribute to the taglib, and setting the permissions accordingly

# How can you verify that it works?

Either follow the steps in the ticket, or run the integration tests

fragments

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
