### PR TITLE
LPS 197132 Unchecked extension format between file and filename

### PR DESCRIPTION
**Pull request by manuelRives**
Changes requested on https://github.com/brianchandotcom/liferay-portal/pull/144178

### CODE REVIEW

**Comment by manuelRives** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1367401_5828

**Comment by adolfopa** [comment]
ci:reevaluate:1367401_5828

**Comment by manuelRives** [comment]
ci:reevaluate:1367401_5828

**Comment by manuelRives** [comment]
Forwarding since failures do not seem related with the changes made on this pull.

**Comment by manuelRives** [comment]
ci:forward:force

**Pull request closed without merging**
