### PR TITLE
LPD-35388 Asset publishers show assets after site/asset library is disconnected

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-35388 Asset publishers show assets after site/asset library is disconnected

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-35388

When a object from an asset library is shown on an asset publisher we should check if the site/asset library is connected or not

# How am I fixing it?

On the DepotAssetRendererFactoryWrapper check if the asset entry is from a asset library, and if the group we are showing it is connected or not to it

# How can you verify that it works?

Run the included automated tests.

# Commits

- **LPD-35388 if asset Renderer Group is depot check if is connected to show it**
- **LPD-35388 check NPE**
- **LPD-35388 add test to check that the asset renderer of the entry of the asset library returns null when the site and depot are not connected**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:report:79231278

**Comment by AliciaGarciaGarcia** [comment]
ci:report:79231278

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1397401_11140

**Comment by jkappler** [comment]
@AliciaGarciaGarcia

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
0 out of 1 jobs passed in 3 minutes

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:report:79214658

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
test failures was relevant to this PR. 
Changing failing line and rebased with master

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management-playwright

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1407401_10836

**Comment by AliciaGarciaGarcia** [comment]
[playwright-js-tomcat90-mysql57-jdk8/2/0](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039437//consoleText) - [Playwright Report](https://testray.liferay.com/reports/production/logs/2024-09/test-1-40/test-portal-acceptance-pullrequest(master)/10836/playwright-js-tomcat90-mysql57-jdk8/2/0/playwright-report/index.html)
[document-library-web/fileEntry.spec.ts](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039437/testReport/document-library-web_fileEntry.spec/ts) Seems to be a flaky one:

// @DiegoHu97

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1407401_10840

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1397401_11151

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1397401_11151

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:report:79546902

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:80334622

**Comment by AliciaGarciaGarcia** [comment]
ci:report:80334622

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
