### PR TITLE
LPD-26394 It is not possible to create a Web Content Structure

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by Mikellorza** [comment]
hey @izaera,

I've just tested on my side but It's not working. is it working on your side , please see this video:


https://github.com/liferay-content-management/liferay-portal/assets/46810560/744ad07d-5f9e-48df-a6f3-407c29549aa0


I've reverted these commits and it seems to work:

image

can you take a look please?

**Review by Mikellorza — CHANGES_REQUESTED** [review]
See above message

**Comment by Mikellorza** [comment]
@izaera finally its works but I have to do a git clean -fdx, so let's move forward

**Comment by Mikellorza** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
hi @izaera 

A external question : there is a way to test this without make an ant all?

Thanks!

**Comment by izaera** [comment]
@AliciaGarciaGarcia Nope. This regenerates all `package.json` files inside the JARs so you need to build all of them... :shrug:

**Comment by AliciaGarciaGarcia** [comment]
Thanks @izaera

**Pull request closed without merging**
