### PR TITLE
LPD-25907 set whitelist attribut on iframeconfiguration

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-25907 This is the pull request title

To forward this https://github.com/liferay-content-management/liferay-portal/pull/5627 need to pass

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-25907

I want to have a whitelist configuration in the Iframe Sanitizer

# How am I fixing it?

I'm adding to the Iframe Configurator: 

```
@Meta.AD(
    deflt = "com.liferay.fragment.model.FragmentEntry|com.liferay.journal.model.JournalArticle",
    name = "whitelist", required = false
)
public String[] whitelist();
```

# How can you verify that it works?

Run the included automated tests.
image

# Commits

- **LPD-25907 add whitelist configuration to the IFrame Configuration**
- **LPD-25907 add method on configuration helper to obtain the whitelist from the configuration**
- **LPD-25907 if the class is on the whitelist do not sanitize**
- **LPD-25907 change methods to get the className and classPK on the test**
- **LPD-25907 add tests to check the behavior with the whitelist value**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:report:24991372

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1367401_6357

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:report:27984803

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1407401_10223

**Comment by AliciaGarciaGarcia** [comment]
ci:report:29081904

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
