### PR TITLE
LPD-27914 add info to the macro method

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-27914 add info to the macro method

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-27914

There is some Flaky test that use the _getFileResponseHeader_ method. to Know more about the error I want to add more info to this method.

# How am I fixing it?

This should not fix anything, only give us more information about the flaky failures

# How can you verify that it works?

Run the affected automated tests.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sharepoint

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:report:37665849

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by AliciaGarciaGarcia** [comment]
wrong suite 😞

**Comment by AliciaGarciaGarcia** [comment]
ci:report:37704483

**Comment by AliciaGarciaGarcia** [comment]
ci:report:37704483

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
