### PR TITLE
LPD-37464 Inherit locale in web content

### PR DESCRIPTION
**Pull request by jkappler**
Default locale creating a web content 

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-37464)

The locale is overriden by the default values of a structure when creating a web content from a structure from global in another site

# How am I fixing it?

When we changed the behaviour because of PTR-3728, we didn't think about inherited structures, it should have only applied when enabling the configuration and for the same site

# How can you verify that it works?

Follow the steps in the ticket or execute the unit test

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Review by DiegoHu97 — APPROVED** [review]
LGTM! Everything works fine! Thank you!

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:34242081

**Comment by jkappler** [comment]
ci:report:34242081

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
