### PR TITLE
LPD-31427 Can't select web content display template with the Preview feature

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Follow up of https://github.com/liferay-content-management/liferay-portal/pull/5700

### What is this trying to solve?
https://liferay.atlassian.net/browse/LPD-31427

### How am I fixing it?

The issue originates from passing the wrong data to the js file. I fixed the issue by generating the proper payload and forwarding it from the preview to the change event.

### How can you verify that it works?

To test manually:
1. Create a web content structure and 2 display templates for that structure.
2. Create a content of that type, give it a name, and save it.
3. From the Properties column, change the default template by accessing it from the eye icon instead of from Select.

cc/ @bakayattila

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
@bakayattila unfortunately I don't get why SF is still failing... I will continue looking into it on monday.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:playwright

**Comment by ambrinchaudhary** [comment]
Test passes successfully: https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/947766/testReport/journal-web_journalArticle.spec/ts/

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1397401_10859

**Comment by ambrinchaudhary** [comment]
ci:report:46674939

**Comment by ambrinchaudhary** [comment]
Failing tests are not related to this pull.

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
