### PR TITLE
LPD-36957 Make auto tagging work with asset libraries

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-36957

In order to prevent content from being accessible from disconnected sites, additional restrictions were enforced. This required group/service context thread locals to be fully initialized, logic that was only triggered in depots.

# How am I fixing it?

By initializing the group thread local when auto tagging assets.

# Why doesn't this include any test?

The existing `DepotAutoTagging.testcase` covers this issue.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:report:16041354

**Comment by adolfopa** [comment]
Test failures are not related to my changes (depot failures are occurring upstream as well).

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:report:16961045

**Comment by adolfopa** [comment]
Relevant failures not related.

**Pull request closed without merging**
