### PR TITLE
LPS 197132 Unchecked extension format between file and filename

### PR DESCRIPTION
**Pull request by manuelRives**
Changed exceptions as requested in https://github.com/brianchandotcom/liferay-portal/pull/149976 and discussed internally.

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@manuelRives

**Comment by jkappler** [comment]
@manuelRives, baseline issues 😢

**Comment by manuelRives** [comment]
ci:test:upgrade

**Comment by manuelRives** [comment]
ci:test:upgrade

**Comment by manuelRives** [comment]
ci:test:upgrade

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
Upgrade failures do not seem related to this pull.

**Comment by jkappler** [comment]
ci:report:2567664996

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
