### PR TITLE
LPD-28668 Update success message after FF removal

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-28668 This is the pull request title

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28668

After the removal of the LPS-196847 Feature Flag on https://liferay.atlassian.net/browse/LPD-28355 , the message of success was dependent of the number of the permission changed

`Your request completed successfully. `or the lang key  `"x-permissions-were-updated-successfully"`

# How am I fixing it?

I'm changing the message to the least common multiple of both messages.

# How can you verify that it works?

Run the included automated tests.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:bulk

**Comment by AliciaGarciaGarcia** [comment]
ci:test:bulk-editing

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:bulk-editing

**Comment by AliciaGarciaGarcia** [comment]
ci:report:19154881

**Comment by AliciaGarciaGarcia** [comment]
ci:report:19154881

**Comment by AliciaGarciaGarcia** [comment]
ci:test:bulk-editing

**Comment by AliciaGarciaGarcia** [comment]
ci:report:19356223

**Comment by AliciaGarciaGarcia** [comment]
ci:test:bulk-editing

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
