### PR TITLE
LPD-34910 Remove LPD-10701 FF

### PR DESCRIPTION
**Pull request by robertoDiaz**
Remove Feature Flags for the epic

# What is this trying to solve?
[Link to ticket](https://issues.liferay.com/browse/LPD-34919)

This pull request removes the feature flags for LPD-10701

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
@adolfopa tests seem unrelated.

Could we forward this and analyze the report?

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by robertoDiaz** [comment]
ci:forward:force

**Pull request closed without merging**
