### PR TITLE
LPD-31633 Check if Item Selectors Browser Breadcrumb is updated 

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi, 
May I ask to review this PR? 

This is the playwright test for the issue:  https://liferay.atlassian.net/browse/LPS-174323

**Steps to reproduce**
1. Go to Content & Data > Document and Media, and Add Folder
2. Create a WC (or another content)
3. Select on image selector 
4. select the created folder of D&M
**Actual result**
Breadcrumb does not change

Task: https://liferay.atlassian.net/browse/LPD-31633

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:playwright

**Comment by boton** [comment]
@gergelyszalay LGTM can you please attach a screenshot of 10/15 repeated runs on your local to avoid flakiness 😄  

```sh
npm run playwright -- test -g "@LPD-31633" --reporter list --repeat-each 10

```

**Comment by gergelyszalay** [comment]
Thanks for looking into @boton 
image
BR,

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
