### PR TITLE
LPD-28893 Move IFrame Sanitizer enablement to Instance Settings

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-28893 Move IFrame Sanitizer enablement to Instance Settings

Resent from https://github.com/liferay-content-management/liferay-portal/pull/5599 with some sort and a new test after : https://github.com/brianchandotcom/liferay-portal/pull/151722#issuecomment-2194524487

@brianchandotcom On the test, the reorder of the iframe attributes: the sandbox attribute is added, if needed, on the sanitizer via JSoup library on the last position, and I could not find the way to order it with this tool. So to do not mismatch the constant, that some of them would be one way and others another (the generated and the not generated) I did not order none to be more consistent on the test. Please tell me if you want other way.

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28893

adding the company scope to the iframe configuration we will allow several companies to have or not have the iframe sanitizer and others enabled and disabled at choice

# How am I fixing it?

I'm adding the scope company to the Configuration. With this some changes on the update of the configuration must be made (helper) and while testing I realized that with groups we can search configuration with PID but for companies not, so I recreated the same behavior for both (internally was calling the pid)

# How can you verify that it works?

Run the included automated tests.

new Integration test for all the changes and old POSHI test should pass

# Commits

- **LPD-28893 change scope to company level for the IFrameConfiguration**
- **LPD-28893 create helper and use it on**
- **LPD-28893 add helper to the source formatter exclusion because if not can not be found**
- **LPD-28893 add saveCompanyConfiguration  with pid to unify methods with saveGroupConfiguration**
- **LPD-28893 baseline**
- **LPD-28893 change test to test saveCompanyConfiguration with pid too**
- **LPD-28893 fix POSHI test and integration test with new behavior**
- **LPD-28893 New test to check that the changed configuration works with company scope now, that the iframe sanitizer is enabled by default, that when sandbox added without values is still empty but exists**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
sf failing because "reasons" 

added a SF with offending files

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:28099068

**Comment by jkappler** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:28634283

**Comment by AliciaGarciaGarcia** [comment]
ci:report:28634283

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:report:28680130

**Comment by AliciaGarciaGarcia** [comment]
ci:report:28680130

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
