### PR TITLE
LPD 24663 BUG Blogs friendlyURL categories add

### PR DESCRIPTION
**Pull request by boton**
# Issue: https://liferay.atlassian.net/browse/LPD-24663

## Before PR
image

image

## After PR
image
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
Dear colleges of @liferay-frontend, 

Can you check [6735334](https://github.com/liferay-content-management/liferay-portal/pull/5439/commits/6735334853f15b8647f663919cdc57de9ad736ee)? 

I think that it is a tiny change, Thanks in advance ❤️

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
Rebase with master and relaunch **relevant**

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:close

**Comment by boton** [comment]
ci:reopen

**Comment by boton** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

I didn't have the time to test it, but from code it look good to me.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Review by markocikos — APPROVED** [review]
@boton The `frontend-js-web` part LGTM! :sparkles:

**Comment by boton** [comment]
ty @markocikos ❤️ !!

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
