### PR TITLE
LPD-31827 | Add ExternalReferenceCode to Blogs Images (Part 1)

### PR DESCRIPTION
**Pull request by bakayattila**
task ticket:
https://liferay.atlassian.net/browse/LPD-31827
Story ticket:
https://liferay.atlassian.net/browse/LPD-27622

------

The pull might seem a bit empty but https://liferay.atlassian.net/browse/LPS-130893 already implemented the ERC in the service updated the add method and created a get for ERC. In this pull, I added the missing delete by ERC.  I did not create an update by ERC as there is no update method for BlogPostingImage at all.

- [x] add with ERC [addFileEntry](https://github.com/bakayattila/liferay-portal/blob/f908f8fa9e0b8c56a702ee770ebdc83d9a5ddf94/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppLocalServiceImpl.java#L139C4-L139C33)
- [x] get/fetch by ERC [fetchFileEntryByExternalReferenceCode](https://github.com/bakayattila/liferay-portal/blob/f908f8fa9e0b8c56a702ee770ebdc83d9a5ddf94/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppLocalServiceImpl.java#L592-L600), [getFileEntryByExternalReferenceCode](https://github.com/bakayattila/liferay-portal/blob/f908f8fa9e0b8c56a702ee770ebdc83d9a5ddf94/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppLocalServiceImpl.java#L667-L675  )
- [x] delete by ERC This pull

Resent the pull based on: https://github.com/brianchandotcom/liferay-portal/pull/152993#issuecomment-2271718690

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hey @bakayattila could you please review the semantic versioning errors? Thanks! ;-).

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:report:59825636

**Comment by ambrinchaudhary** [comment]
Hey Attila, according to the report, there are unique failures to this pull: 
Unique Failures
```
com.liferay.headless.admin.user.resource.v1_0.factory.test.PhoneResourceFactoryImplTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846284/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.AccountGroupResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846288/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.AccountResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846292/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.AccountRoleResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846296/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.EmailAddressResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846300/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.OrganizationResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846304/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.PhoneResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846308/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.PostalAddressResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846312/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.RoleResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846316/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.SegmentResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846320/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.SegmentUserResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846324/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.TicketResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846328/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.UserAccountResourcePerformanceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846332/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.UserAccountResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846336/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.UserGroupResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846340/history,Unique,testRun: Failed to run test on CI
com.liferay.headless.admin.user.resource.v1_0.test.WebUrlResourceTest,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59846344/history,Unique,testRun: Failed to run test on CI
PortalLogAssertorTest-modules-integration-mysql57-jdk8/4/4,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59847602/history,Unique,PortalLogAssertorTest#testScanXMLLog: Unable to bind to the LDAP server javax.naming.CommunicationException: localhost:10389 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]  at com.sun.jndi.ldap.Connection.<init>(Connection.java:235)  at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)  at com.sun.jndi.ldap.LdapClientFactory.createPooledConnection(LdapClientFactory.java:71)  at com.sun.jndi.ldap.pool.Connections.createConnection(Connections.java:187)  at com.sun.jndi.ldap.pool.Connections.getAvailableConnection(Connections.java:152)  at com.sun.jndi.ldap.pool.Pool.getOrCreatePooledConnection(Pool.java:188)  at com.sun.jndi.ldap.pool.Pool.getPooledConnection(Pool.java:148)  at com.sun.jndi.ldap.LdapPoolManager.getLdapClient(LdapPoolManager.java:340)  at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1607)  at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2847)  at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)  at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUr...
PortalLogAssertorTest-modules-integration-mysql57-jdk8/2/8,https://testray.liferay.com/#/project/34754/routines/34756/build/59825636/case-result/59849046/history,Unique,PortalLogAssertorTest#testScanXMLLog: The img tag contained an attribute that we could not process. The onerror attribute has been filtered out. but the tag is still in place. The value of the attribute was "alert&#40;content&#41;".

```

Could you please chck if they are really related? If not... let's force the forward..

**Comment by ambrinchaudhary** [comment]
After speaking with @bakayattila, we agreed that these failures cannot be related to the pull. 

> These failures are not even in a related class. And there is no new test for the feature yet.
> Introducing a new method(which has not been used yet) should not affect any existing test. 

Force forwarding...

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
