### PR TITLE
LPD-39367 [Playwright] Fix 'Check alert message of duplicated friendly URL in french'

### PR DESCRIPTION
**Pull request by boton**
>[!NOTE]
> This PR is built on instead of #5998 simply the logic

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-39367

We are trying to fix the test failure `Check alert message of duplicated friendly URL in french`

image

# How am I fixing it?
My first attempt was to use `data-qa-id` but updating the locator is good enough.
Update the locator to use regex to include FR and use the `this.fillTitle` to wait until the page is ready

# How can you verify that it works?

1. Go to `/modules/test/playwright`
1. Run `npm install` (setup)
1. Run `npm run playwright test -- -g "Check alert message of duplicated friendly URL in french"` to execute the test

# Test launched 10 times test locally to avoid flaky results

image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
I updated the branch and put this commit from https://github.com/liferay-echo/liferay-portal/pull/16419/commits/10894416eb00099e6a5507c4662b76e8e03a8888 to fix the SF error

**Comment by boton** [comment]
ci:test:sf

**Review by gergelyszalay — APPROVED** [review]

**Review by DiegoHu97 — APPROVED** [review]
LGTM! thank you @boton ! :heart:

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Comment by DiegoHu97** [comment]
The test passes in CI, I will forward the PR

**Pull request closed without merging**
