### PR TITLE
LPD-43100 Inconsistencies in tags filter 

### PR DESCRIPTION
**Pull request by Mikellorza**
Coming from:  https://github.com/liferay-content-management/liferay-portal/pull/6145 in order to fix failing tests and so on

Inconsistencies in tags filter

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-43100)

There are some inconsistencies when configuring the tags filter to show a specific asset type. For one, the count that is displayed is the global count, not the count for the specific asset type. The second is the ordering, it's sorted alphabetically and not by asset count.

Also, the tags that are not used are not taken into account

# How am I fixing it?

1. Retrieve also the empty tags in the response, with an union
2. For the count, don´t retrieve the global asset count, but calculate it by asset type

# How can you verify that it works?

Follow the steps on the ticket or run the adapted integration tests

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:open

**Comment by Mikellorza** [comment]
ci:reopen

**Comment by Mikellorza** [comment]
ci:reevaluate:1377401_19177

**Comment by Mikellorza** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by Mikellorza** [comment]
ci:report:90130054

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:report:90130054

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:91061425

**Comment by Mikellorza** [comment]
Failed tests are not related, so, we can move forward!

**Comment by Mikellorza** [comment]
ci:forward:force

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
