### PR TITLE
LPD-39899 Permission's improvements in DM

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Sending here for first review before forwarding to Frontend Infra team. 

# What is this trying to solve 

- https://liferay.atlassian.net/browse/LPD-39899 Remove more/hide options button 
- https://liferay.atlassian.net/browse/LPD-39898 Change label in DM from “Viewable by” to “Viewable and Downloadable by” (only applies to File Upload and Multiple Upload in DM)

Screenshot 2024-10-23 at 14 17 50
Screenshot 2024-10-23 at 14 18 19

Other places like Blogs, Web Content ... are not affected, because DM is the only one that has de Download permission. 

# How can I test it
Run `npm run playwright -- test -g 'LPD-39898' --reporter list`

```
npm run playwright -- test -g 'LPD-39898' --reporter list --repeat-each=5

> @liferay/playwright@1.0.0 playwright
> playwright "test" "-g" "LPD-39898" "--reporter" "list" "--repeat-each=5"


Running 5 tests using 1 worker

  ✓  1 [document-library-web] › document-library-web/dmPermissions.spec.ts:22:1 › DM Permissions initial status (27.9s)
  ✓  2 [document-library-web] › document-library-web/dmPermissions.spec.ts:22:1 › DM Permissions initial status (24.9s)
  ✓  3 [document-library-web] › document-library-web/dmPermissions.spec.ts:22:1 › DM Permissions initial status (22.2s)
  ✓  4 [document-library-web] › document-library-web/dmPermissions.spec.ts:22:1 › DM Permissions initial status (35.1s)
  ✓  5 [document-library-web] › document-library-web/dmPermissions.spec.ts:22:1 › DM Permissions initial status (22.7s)

  5 passed (2.5m)
```

### CODE REVIEW

**Comment by boton** [comment]
ci:test:content-management-playwright

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
Java part LGTM 👍

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Comment by ambrinchaudhary** [comment]
Checked the results of ci:test:content-management-playwright. The failures are currently present on our daily routines, so they are not related to this pull. New test added here is passing. 

@boton are you ok if I send this to Frontend Infra team?

**Comment by boton** [comment]
@ambrinchaudhary I'm reviewing now 😅

**Comment by boton** [comment]
I added some changes after chatting with @ambrinchaudhary, test is working :D 

image

**Comment by boton** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Thank you for your review @boton. PR submitted to FI: https://github.com/liferay-frontend/liferay-portal/pull/4515

**Pull request closed without merging**
