### PR TITLE
LPD-44786 Fix blogEntry.spec.ts failures

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-44786

Test broken by feature (outdated UI) https://liferay.atlassian.net/browse/LPD-32047

# How am I fixing it?

Updating the test to fit with the new UI and interactions. Used new methods that page management added to pageEditorPage and assetPublisherPage.

# How can you verify that it works?

Runt the test
```sh
npm run playwright -- test tests/blogs-web --grep-invert Permission
```

# Locally test passed
image

### CODE REVIEW

**Comment by boton** [comment]
@sandrodw3 Can you please check [018c850](https://github.com/liferay-content-management/liferay-portal/pull/6196/commits/018c85093d3b0785432d32b2991cccc7ce34119d) and [c26f246](https://github.com/liferay-content-management/liferay-portal/pull/6196/commits/c26f2462e5634731ccd89453011b339b22efa290) ? 🥺

**Comment by boton** [comment]
ci:test:content-management-playwright

**Review by ambrinchaudhary — APPROVED** [review]
LGTM! 🎉

**Comment by boton** [comment]
Passed on CI [[master] ci:test:content-management-playwright - boton > liferay-content-management - PR#6196 - 2024-12-19[04:17:37]](https://testray.liferay.com/#/project/35392/routines/45357/build/95765748)

image

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
