### PR TITLE
LPD-17743 move date exceptions for file entries to portal-kernel module

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Motivation
to unify and to be able to validate th dates on the insertion of the table, I want the dateException be able to be seen from the DLFileEntryLocalService class

- LPD-17743 add exceptions on service
- LPD-17743 move exception to let them be accessible for dlFileService classes
- LPD-17743 semver
- LPD-17743 autoSF

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2538436184

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2538666701

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1327401_3664

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
passing test here to check FFMPEG failures :D

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2539440602

**Pull request closed without merging**
