### PR TITLE
LPD-30614 Set thread local company ID

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-30614

The feature flag for LPS-203351 is *not* at system level, but there are some places in the code where the company ID cannot be passed explicitly. As the FF checks need to rely on the thread local company, we need to set it in the tests to avoid the log from being polluted (which will make some other tests fail).

# How am I fixing it?

By setting the thread local company ID before running the tests and resetting it afterwards.

# How can you verify that it works?

Run `JournalArticleContentDashboardItemTest` and verify that not error messages related to feature flags are displayed in the logs.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
@adolfopa, I think we normally use "originalCompanyId" as pattern, but I'm moving fwd. If Brian requests a change I will send a follow up

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
