### PR TITLE
LPD-40396 actualURL needs to know the correct scopeGroupId to know in the case of a assetLibrary-Site connection if is or not connected

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-40396 An asset library custom document entry cannot be displayed with the default display page template on a connected site

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-40396

If we want the correct asset renderer we should obtain the correct relation between the group and the asset library.

# How am I fixing it?

on FriendlyURLServlet.getRedirect() to obtain the actualURL and get the assetRendered from DepotAssetRendererFactoryWrapper.getAssetRenderer need the current group, but now, the scoped group is not the one from the url, is the guest group. If this group is not connected with the asset library (and this is the reason that with liferay portal this bug is not reproducible) the assetRendered is null.
this is why we should restore the serviceContext **after** obtaining the actualURL.

# How can you verify that it works?

Run poshi test related to this: 

LocalFile.DepotDisplayPage#CanViewDepotDMUsingDepotType
LocalFile.DepotDisplayPage#CanViewDepotDMUsingGlobalType

# Why doesn't this include any test?

There are already tests that cover this.

# Commits

**LPD-40396 actualURL needs to know the correct scopeGroupId to know in the case of a assetLibrary-Site connection if is or not connected**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:friendly-url

**Comment by AliciaGarciaGarcia** [comment]
ci:test:site-management

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
