### PR TITLE
LPD-26404 - Permissions to be asked during publication and not when autosaving

### PR DESCRIPTION
**Pull request by gergelyszalay**
https://liferay.atlassian.net/browse/LPD-26404

As a Content Creator,

I want to check and manage permissions during the publishing process of my web content, rather than during autosaving,

So that I am aware of who will be able to see it at the appropriate stage in the process.

[Figma](https://www.figma.com/proto/I2zVHduay0iYhUR5D84JEK/LPD-11228-Autosave-draft-in-Web-Content-editor?page-id=84%3A16808&node-id=91-16457&viewport=852%2C330%2C0.15&t=u4UAs0EcTKnbxjPD-1&scaling=min-zoom&starting-point-node-id=91%3A16457)

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
looks good!

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:30212391

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
@jkappler @gergelyszalay I'll give stable another try, but if it fails I think it is better to forward this manually; we should catch any failure pretty quickly, as we're actively monitoring test failures.

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Not sure if the failure is related (there's one test about saving webcontent). @gergelyszalay Can you take a look? If it is not related, please forward the PR manually.

**Comment by adolfopa** [comment]
ci:report:32981080

**Comment by Mikellorza** [comment]
see:https://github.com/liferay-content-management/liferay-portal/pull/5736

**Comment by Mikellorza** [comment]
ci:close

**Pull request closed without merging**
