### PR TITLE
LPD-29894 locked items test properties

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPD-29715 

# What is this trying to solve?
This test is currently displaying in Testray as belonging to “Ci Infrastructure”

# How am I solving this
I added the missing test.properties file for the playwright test, and referenced it to the content-management suite.

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:stable

**Review by marcogalluzzi — APPROVED** [review]
LGTM. Thanks!

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:stop

**Pull request closed without merging**
