### PR TITLE
LPD-36593 Fix versions tab display

### PR DESCRIPTION
**Pull request by interaminense**
Hi Content Management, team!

In this fix, I removed the logic that sets the position of the tabs according to the feature flag. This was causing the ClayTabs component not to find the versions tab, and therefore the content was not loading.

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
You still need to enable the feature flag to display the performance tab.

**Comment by NemethNorbert** [comment]
Hey @interaminense ,

I am not sure about this change, Are we sure we want to remove that conditional and display 4tabs all the time? It might be expected with [LPD-28830](https://liferay.atlassian.net/browse/LPD-28830) but right now thats under featureflag.
As with this change we always have all 4 tabs available. We will also have 4tabs available if we don't use that featureflag and that concerns me. In case we would want to keep this conditional, we could use:
`const TABS_1 = {
	categorization: 1,
	details: 0,
	version: 2,
};
const TABS_2 = {
	categorization: 1,
	details: 0,
	performance: 3,
	version: 2,
};`

As putting this in a conditional would not change the tab numbers for any specific tab, just simply expand it with another performance tab conditionally. This should ensure the tabs keep working. What do you think?

**Review by NemethNorbert — CHANGES_REQUESTED** [review]
Hey @interaminense ,

I am not sure about this change, Are we sure we want to remove that conditional and display 4tabs all the time? It might be expected with [LPD-28830](https://liferay.atlassian.net/browse/LPD-28830) but right now thats under featureflag.
As with this change we always have all 4 tabs available. We will also have 4tabs available if we don't use that featureflag and that concerns me. In case we would want to keep this conditional, we could use:
const TABS_1 = { categorization: 1, details: 0, version: 2, }; const TABS_2 = { categorization: 1, details: 0, performance: 3, version: 2, };

As putting this in a conditional would not change the tab numbers for any specific tab, just simply expand it with another performance tab conditionally. This should ensure the tabs keep working. What do you think?

**Review by NemethNorbert — APPROVED** [review]
Hey @interaminense ,

THanks for pointing out the conditional rendering of the performance tab later on the component. I approve this PR

**Comment by NemethNorbert** [comment]
ci:forward

**Comment by interaminense** [comment]
Hi @NemethNorbert, no problem since the Performance tab will still need FF enabled to be displayed in the UI. It's even more readable in my opinion. Thanks!

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
