### PR TITLE
LPD-39795 File upload error message wrong size limit 

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-39795

The file upload error message shows the global limit instead of the Mime Type for that format.

# How am I fixing it?

Sending the right message in on FileSizeException and priority to the server message and render if exists

# How can you verify that it works?

Run the included integration test

### CODE REVIEW

**Comment by robertoDiaz** [comment]
I'll get this pull this afternoon to help with the tests.

**Comment by robertoDiaz** [comment]
Starting with the tests

**Comment by robertoDiaz** [comment]
ci:test:sf

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by boton** [comment]
Failures doesn't look related

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
