### PR TITLE
LPD-36182 journal discard all button

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
This task is part of story https://liferay.atlassian.net/browse/LPD-36051, where a new “Undo All” button should appear and Undo, Redo and History are now hidden under FF LPD-36053
Screenshot 2024-09-12 at 16 04 10

As this is something temporal for the Milestone, I decided not to add new test for this button. Current tests for AutoSave + Undo/Redo are hidden under Feature Flag.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Review by NemethNorbert — APPROVED** [review]
LGTM, I think the failing tests might be flaky as they are passing manually

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Comment by ambrinchaudhary** [comment]
Hey @boton may I ask your review in this pull? I put the [playwright tests under the new FF](https://github.com/liferay-content-management/liferay-portal/pull/5865/commits/399e31f52076944c12ccea1a42eed2c3ab0b5617) but they are failing consistently in ci... am I doing something wrong

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1327401_5004

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Comment by ambrinchaudhary** [comment]
On hold, it depends on https://github.com/liferay-forms/liferay-portal/pull/2612. If that one gets merged soon, this pull is not necessary

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Comment by ambrinchaudhary** [comment]
Tests are now passing. However, and after confirmation with Product Owner, we are waiting for https://github.com/liferay-forms/liferay-portal/pull/2612, if it gets merged this week (or during next days), this pull is not necessary. 

I'm going to mark is at draft just to avoid accidental forward.

**Review by boton — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/154445 has just been approved. I will wait for product/ux review, and if it passes I will close this PR as discarded.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
