### PR TITLE
LPD-27899 [FE] Replace option does not work on Categories Selector

### PR DESCRIPTION
**Pull request by Mikellorza**
Replace option does not work on Categories Selector

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-27899

It is not possible to replace categories in bulk. So, this PR fix it.

# How am I fixing it?

This PR fix the replace categories in bulk functionallity, 

# How can you verify that it works?

Run playwright included test.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]
LGTM! 🎉

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Comment by ambrinchaudhary** [comment]
I think test haven't passed 🤔: https://testray.liferay.com/#/project/35392/routines/45357/build/5689241/case-result/5709263

I will launch it again...

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Comment by adolfopa** [comment]
ci:test:content-management-playwright

**Comment by Mikellorza** [comment]
ci:test:content-management-playwright

**Comment by Mikellorza** [comment]
@ambrinchaudhary @adolfopa  executing again to see if works, btw I added a comment in the ci channel about the issue that we are facing here to see if they can help us to fix it

**Comment by boton** [comment]
Guys, you have the report here https://github.com/liferay-content-management/liferay-portal/pull/5846#issuecomment-2340337284

**Testray Build:** [[master] ci:test:content-management-playwright - Mikellorza > liferay-content-management - PR#5846 - 2024-09-10[02:42:26]](https://testray.liferay.com/#/project/35392/routines/45357/build/6401755)

**Comment by kenjiheigel** [comment]
Sorry, I'm testing something out to see if we can fix the github message issues.

**Comment by Mikellorza** [comment]
For some reason, the postDocument call is not working fine but I tested many times on my local and It worked fine, so, let's run again.

**Comment by Mikellorza** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
I tried to get it working on https://github.com/boton/liferay-portal/pull/250, I launched 20 times the test in the CI to check it was a flaky solution or a good one.

**Comment by Mikellorza** [comment]
Finally we have managed to fix the test. 

thanks @boton for your work!!!

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:content-management-playwright

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:report:13591326

**Comment by Mikellorza** [comment]
ci:report:13554951

**Comment by Mikellorza** [comment]
Test failures are not related with this PR. So, let's move to Brian if I can :(

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
