### PR TITLE
LPD-35636 Force the use of h264 codec in mp4 videos.

### PR DESCRIPTION
**Pull request by manuelRives**
### What is this trying to solve?
https://liferay.atlassian.net/browse/LPD-35636 FFmpeg not using h264 codec in SUSE and RedHat systems..
### How am I fixing it?
Forcing the use of h264 codec in mp4 videos.
### How can you verify that it works?
1. Create an environment running SUSE Enterprise Linux 15
2. Setup a vanilla bundle of Liferay 7.4 U92
3. Configure and enable FFmpeg (compile version 7.0.2 from source as there is no install file option)
4. Go to Documents and Media
5. Upload any video file
6. Observe that the video does not have sound and does not play (except for a static image)
### Why does this pull not include tests?
This cannot be observed reliably from a test. The behavior is observed only with certain ffmpeg builds on some systems.

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]
It works on my machine!

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@manuelRives Did you check the error in https://github.com/liferay-content-management/liferay-portal/pull/5833#issuecomment-2332359789? It definitely looks like a legit failure. Does it pass locally for you? If so, comment in the pr so that it is visible.

**Comment by manuelRives** [comment]
Hi @adolfopa,

I had rerun it because locally I cannot reproduce it. On my machine those 2 failed tests pass.

Sorry for not mentioning that in the pull.

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:report:14412023

**Comment by adolfopa** [comment]
@manuelRives To figure out what is failing you'll need to log both the stdout and stderr of the ffmpeg process. Pass stderr to the `_consumeProcessInputStream` method, and while consuming both streams, accumulate it into a StringBundler and log it.

**Comment by adolfopa** [comment]
See https://github.com/liferay-content-management/liferay-portal/pull/5896 for an additional debug commit.

**Pull request closed without merging**
