### PR TITLE
LPD-37998 Documents and Document Folders can be Moved between sites

### PR DESCRIPTION
**Pull request by balazssk**
# What is this trying to solve?
[LPD-37998 Documents and Document Folders can be Moved between sites](https://liferay.atlassian.net/browse/LPD-37998)

Documents and Document Folders can be moved between sites, but this action does not handle dependencies like Document Types, breaking Documents in the process.

# How am I fixing it?
By disabling the option to move Documents and Document Folders between sites.

# How can you verify that it works?
"Run the included automated tests."

Cheers,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]

**Review by ambrinchaudhary — CHANGES_REQUESTED** [review]
Hey guys, I'm not sure if this is the correct fix. I think moving between sites was done on purpose and it is expected, but I can't the epic/story about it. If something break in the proccess, we should try to fix that (or check if that is the intentional behaviour). Anyway, I think this change must be confirmed with product owners

**Comment by jkappler** [comment]
@balazssk, did you talk to POs about this?

**Comment by balazssk** [comment]
hey @ambrinchaudhary @jkappler 
Yes, Ruth confirmed it is a bug here : https://liferay.slack.com/archives/GQBCVUPBQ/p1727943290454149?thread_ts=1727783761.820149&cid=GQBCVUPBQ

**Comment by balazssk** [comment]
hmm, need to rethink

**Pull request closed without merging**
