### PR TITLE
LPD-35646 Validate title field when autosaving

### PR DESCRIPTION
**Pull request by DiegoHu97**
LPD-35646 Validate title field when autosaving

# What is this trying to solve?

- Validate the title required field when we fill firstly other fields. Before, when we leave the title empty and fill another field first, the title validation was not shown. 

[Link to ticket](https://liferay.atlassian.net/browse/LPD-35646)

# How am I fixing it?

- Validate both title field and ddm fields when the title is empty

# How can I test it?

- Follow the steps in the test

image
image

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Review by NemethNorbert — COMMENTED** [review]
Hey @DiegoHu97,

It looks good to me, but I have one concern. Reading the code, if LPS-114700 is enabled, we don't do any validation just warn the user about the title. Do you think that is the expected behaviour in that scenario? Maybe these validations should run in that case as well.

**Comment by DiegoHu97** [comment]
Hey @NemethNorbert you are right! But it should be the case when The FF LPS-114700 is not enabled right? In this line here [https://github.com/liferay-content-management/liferay-portal/blob/4ead3e41e358f2c6bf64fdbd0f80b9c646a873e9/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/JournalPortlet.es.js#L249](https://github.com/liferay-content-management/liferay-portal/blob/4ead3e41e358f2c6bf64fdbd0f80b9c646a873e9/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/JournalPortlet.es.js#L249)  
  
The case you described, when LPS-114700 is enabled is handled here [https://github.com/liferay-content-management/liferay-portal/blob/4ead3e41e358f2c6bf64fdbd0f80b9c646a873e9/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/JournalPortlet.es.js#L261](https://github.com/liferay-content-management/liferay-portal/blob/4ead3e41e358f2c6bf64fdbd0f80b9c646a873e9/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/JournalPortlet.es.js#L261)

**Comment by DiegoHu97** [comment]
Hey @NemethNorbert ! I just added this commit 23bda5d :smile:

**Review by NemethNorbert — APPROVED** [review]
Thank you @DiegoHu97,

The Changes are good :)

**Comment by NemethNorbert** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
Failures are not related

**Comment by DiegoHu97** [comment]
ci:forward:force

**Comment by DiegoHu97** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by DiegoHu97** [comment]
We need to check an issue with PO

**Comment by DiegoHu97** [comment]
Hey @NemethNorbert, I will forward the PR, the case that we talked yesterday, Ruth said that it's a permissions bug, not related with this story, I will create that bug when I have time, thank you!

**Pull request closed without merging**
