### PR TITLE
LPD-28848 Add test to ensure web content folder can be moved to another folder via the management toolbar (covers LPD-15248)

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28848
https://liferay.atlassian.net/browse/LPD-15248

# How am I fixing it?

This is adding a Playwright test to cover the use case in LPD-15248

# How can you verify that it works?

Run `npm run playwright -- test -g 'LPD-15248'`

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:playwright

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:playwright

**Comment by jonathanmccann** [comment]
ci:test:stable

**Comment by jonathanmccann** [comment]
ci:test:playwright

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Failures look unrelated.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
