### PR TITLE
LPD-25634 Fix hide/show content field

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPD-25634)

## Steps

- Go to Content & Data > Structures
- Add two structures and save
- Go to Web Content > Create a Web Content based on the structure created
- Fill the fields for default language
- Change the language and fill only one of the ddm field
- Change the translation filter to “translated“ or “untranslated“
- See the content wrapper does not show even if there is a field that’s not translated/unranslated

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2568164724

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by DiegoHu97** [comment]
ci:report:2568180225

**Comment by DiegoHu97** [comment]
ci:forward:force

**Pull request closed without merging**
