### PR TITLE
LPD-36721 Getting error in Headless API response after deleting any image from web content

### PR DESCRIPTION
**Pull request by jkappler**
Getting error in Headless API response after deleting any image from web content

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-36721)

There's an error being thrown when we delete an image of a ddm field and then retrieve the web content through headless API

# How am I fixing it?

Controlling the exception

# How can you verify that it works?

Follow the steps in the ticket or execute the integration test

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:15711664

**Comment by jkappler** [comment]
Failures are not related to the changes

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
