### PR TITLE
LPD-18213 Remove duplicated label and avoid unnecessary aui:field-wrapper

### PR DESCRIPTION
**Pull request by boton**
# Issue: https://liferay.atlassian.net/browse/LPD-18213

## Before PR
image
image

## After PR
image
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:reevaluate:1397401_9471

**Comment by manuelRives** [comment]
ci:reevaluate:1397401_9471

**Comment by manuelRives** [comment]
Failures don't seem related to this pull.

**Comment by manuelRives** [comment]
ci:forward:force

**Pull request closed without merging**
