### PR TITLE
LPD-24189 Validations when setting display date in D&M

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPD-24189

How to test it

1) enable FF 
2) Go to D&M > New > Multiple Files Upload > select or drag file(s)
3) set a display date AFTER a expiration date

- there is an error on each file
- 
image

- **LPD-24189 the error message must be shown on each file so we must include all the possible causes inside of the try catch of the message creation**
- **LPD-24189 put the relevant message for each relevant exception**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
@boton 
i do not know if more is what we wanted. Please review :)

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
Looks good from a backend perspective. I'll let @boton give the final approval and do the forward.

**Review by boton — APPROVED** [review]
LGTM!

It isn't the most beautiful errors but works :D

**Comment by boton** [comment]
I only reviewed the code / screenshot but have not tested it myself

**Comment by boton** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
failures totally relevant to this PR.

I will fix them on an additional commit.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
