### PR TITLE
Cannot add linebreaks in Message Boards with BBCode format

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[Link to issue ](https://liferay.atlassian.net/browse/LPD-39135) Cannot add linebreaks in Message Boards with BBCode format

# How am I fixing it. 
This bug was introduced by https://github.com/brianchandotcom/liferay-portal/pull/141654/files. I am reverting the change and checking that there is currently no XSS issue by running these functional tests: 
- MBThread#CannotPublishThreadWithTagContainingJavaScript
- MBThread#CanViewBBCodeNoXSSWithRemoteServices
- MBThread#JavascriptIsNotExecutedInBBCodeBody
- MBThread#JavascriptIsNotExecutedInHTMLBody

Also I have added a playwright test to cover that linebreaks can be added in BBCode (the default configuration)

Screenshot 2024-10-14 at 13 49 19

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:message-boards

**Comment by ambrinchaudhary** [comment]
Manually checked that at least 
[.MBThread#JavascriptIsNotExecutedInBBCodeBody]](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1112145/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MBThread_JavascriptIsNotExecutedInBBCodeBody_)
[.MBThread#CannotPublishThreadWithTagContainingJavaScript]](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/938072/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MBThread_CannotPublishThreadWithTagContainingJavaScript_)
are passing, which means that the revert is correct. I will work on the test then.

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Comment by ambrinchaudhary** [comment]
ci:test:message-boards

**Comment by robertoDiaz** [comment]
Looks good to me, but it could be an integration test.

Functional test in this case is a little bit overkill

**Review by robertoDiaz — COMMENTED** [review]
Looks good to me, but it could be an integration test.

Functional test in this case is a little bit overkill

**Comment by ambrinchaudhary** [comment]
> Looks good to me, but it could be an integration test.
> 
> Functional test in this case is a little bit overkill

I understand your point. In this case, I don't have the knowledge to write a java integration test, it will require help from a backend, but also it seemed interesting to me to have a functional test that not only covers the sanitizer problem, but also this issue https://liferay.atlassian.net/browse/LPS-110498 that came up some years ago and it is linked in the current LPP. 
Do you still think it should be changed by an integration test? could you add it, or who? 
Thanks!

**Comment by ambrinchaudhary** [comment]
ci:test:message-boards

**Review by robertoDiaz — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
Manually forwarded to Brian: https://github.com/brianchandotcom/liferay-portal/pull/155226

**Pull request closed without merging**
