### PR TITLE
LPD-31578 Reload after posting a comment on workflow tasks page so the action menu is updated correctly

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://liferay.atlassian.net/browse/LPD-31578

hi everyone! 🌸

this is a follow-up of this [PR](https://github.com/liferay-content-management/liferay-portal/pull/5727) and was already tested on ci (results [here](https://github.com/liferay-workflow/liferay-portal/pull/1228)), but feel free to run again or other suites if you think it's necessary.

if you have any questions feel free to ask and thanks a lot! 🌷

cc: @boton

### CODE REVIEW

**Review by boton — APPROVED** [review]
Nice work here @rebsilva ❤️ 

The frontend part is much cleaner and the test is passing.

image


Let's wait until @robertoDiaz reviews the java part 😄 

>[!NOTE]
> @robertoDiaz @rebsilva It would be fantastic if we had this same solution in 7.3, much cleaner than the previous one, how can we do it?

**Comment by rebsilva** [comment]
hi guys! any updates about this?

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
Passed review.

@rebsilva , please do not forget to backport this to all the required branches (7.3.x included)

Thx!

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
