### PR TITLE
LPD-29527 Create test for LPP-52349

### PR DESCRIPTION
**Pull request by DiegoHu97**
Test automation for LPP-52349 - Deleting a translated web content created from a structure with at least one required and non-localizable field is not possible

# What is this trying to solve?

Create automation test for [LPP-52349](https://liferay.atlassian.net/browse/LPP-52349)

[Link to ticket](https://liferay.atlassian.net/browse/LPD-29527)

# How am I fixing it?

1. Create functional test following the steps in the ticket

# How can I test it?

1. Manually: Follow the steps [in this bug](https://liferay.atlassian.net/browse/LPD-15352) 
2. Or execute the test

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:report:30241817

**Comment by adolfopa** [comment]
ci:report:31106375

**Comment by adolfopa** [comment]
@boton Can you take a look at this pr?

**Comment by boton** [comment]
> @boton Can you take a look at this pr?

Yes I'm reviewing it

**Comment by boton** [comment]
@DiegoHu97 and I worked on this on pair, @DiegoHu97 is going to update the PR after some changes and check everything is working well

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
Hey @boton, i have just made the changes that we talked, thank you for the review :hugs:

**Comment by boton** [comment]
ci:test:playwright

**Comment by DiegoHu97** [comment]
ci:test:playwright

**Review by boton — APPROVED** [review]
LGTM!

We need to wait until `ci:test:playwright` ⏳ finished to analyze the results

**Comment by boton** [comment]
[Failures](https://github.com/liferay-content-management/liferay-portal/pull/5630#issuecomment-2218092916) look unrelated
image

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
