### PR TITLE
LPD-28315 and LPD-29163 - FF removal and poshi fixes 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Resent from https://github.com/liferay-content-management/liferay-portal/pull/5596

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
See original [comment](https://github.com/liferay-content-management/liferay-portal/pull/5596#issuecomment-2182477329) from @Mikellorza 
> Hey team,
> 
> As I have spoken with Jorge, we are going to open a thread in order to synchronize ourselves. I also left a comment here in order to inform what methods we have to take into account:
> 
> We have to implement a new macro for the cases that are called to save as draft button, something like saveAsDraftWithPermissions.
> We have to take into account these methods that we are using it to create a content and publish or save it as draft:
> 1 WebContent.addArticleCP -> Change inside there from publish to publishWithPermissions, for sure it will fix a lot of failures. Or change from Button.clickPublish(); to publishWithPermissions. Or change from PortletEntry.saveAsDraft(); to saveAsDraftWithPermissions. Or change from PortletEntry.submitForWorkflow(); to submitForWorkflowWithPermissions. Or change from PortletEntry.save(); to saveAsDraftWithPermissions. And for those cases, see if the publish/saveAsDraft/etc is directly related with add content or maybe it is related with another action that we are doing after.
> 2 WebContent.addCP --> Changes where is it used from publish to publishWithPermissions
> 3 WebContent.addDraft --> Here we have to add new macro called saveAsDraftWithPermissions where we have to do exactly the same as publishWithPermission but changing the titles of the button from Publish With permissions to Save as draft or something like this.
> 4 WebContent.addDraftPGViaAP --> Same that above.
> 5 WebContent.addExistingRelatedAssetCP --> Change inside there from publish to publishWithPermissions.
> 6 WebContent.addFailWithoutRequiredCategoryAssetTypeCP --> Change inside there from publish to publishWithPermissions.
> 7-WebContent.addNullCP --> Change inside there from publish to publishWithPermissions.
> 8 And the other method are using WebContent.addCP and this is the same case of point 1.
> 9 WebContent --> the uses of PortletEntry.saveAsDraft() or Button.clickSaveAsDraft(); we have to change from it to saveAsDraftWithPermissions() and clickSaveAsDraftWithPermissions(); ( but maybe we can replace these cases to use saveAsDraftWithPermissions() we have to check it).
> So, definitively, we have to create two more macros:
> 
> saveAsDraftWithPermissions
> submitForWorkflowWithPermissions

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
@ambrinchaudhary this is bloody strange, I can't see any test execution on your PR in the **Testray Build:** [[master] ci:test:content-management - ambrinchaudhary > liferay-content-management - PR#5613 - 2024-06-24[06:31:04]](https://testray.liferay.com/#/project/34754/routines/34756/build/24994838) neither passed ✅   or failed ❌ 


## Total test cases 0

image

**Comment by Mikellorza** [comment]
ci:report:25026799

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
ci:report:25307877

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
Requested help in [#ci ](https://liferay.slack.com/archives/C19PWQ74J/p1719391374464339) channel to understand these failures

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
ci:report:26932268

**Comment by ambrinchaudhary** [comment]
ci:report:26932268

**Comment by ambrinchaudhary** [comment]
ci:report:27371856

**Comment by jkappler** [comment]
ci:report:27371856

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:report:27847263

**Comment by Mikellorza** [comment]
ci:report:27847263

**Pull request closed without merging**
