### PR TITLE
LPD-5513 Replace Resource Selector usages

### PR DESCRIPTION
**Pull request by DiegoHu97**
> [!CAUTION]
> This PR is fully reviewed ✅  but we need the [taglib PR](https://github.com/liferay-frontend/liferay-portal/pull/3967) merged before forward this one. 

[Link to ticket](https://liferay.atlassian.net/browse/LPD-5513)

## Motivation

In Echo team, we have realised that there are many usages of the Folder Selector and Categories Selector. These two selectors works in the same way but with different names.

## Proposed solution

We have decided to unify this component by creating a ResourceSelector component inside **frontend-taglib**, so that in the future we can replace the usages of each module for this new taglib, and this can apply to all selectors that select any source.

The PR in FI is here: liferay-frontend#3967, we should wait for this taglib to be merged before we merge the usages

**PD: The first 7 commits are from journal-web, these commits have been already reviwed by Echo.**

## Steps

**Case 1: Folders when editing bookmarks**

- Go to Content and Data > Bookmarks   
- Create a folder and some child folders   
- Click on the ellipsis of the folder > Edit  
- See folder selector

https://github.com/DiegoHu97/liferay-portal/assets/91208451/6f23c7ff-5ad9-4893-b7cd-b0f753927052

**Case 2: Moving Bookmarks entry/folder**

- Go to Content and Data > Bookmarks   
- Create a folder and some child folders   
- Click on the ellipsis of the folder > Move  
- See folder selector

https://github.com/DiegoHu97/liferay-portal/assets/91208451/b4c8432f-d53e-46d4-bab4-853506b12d3f

**Case 3: Select root folder of Bookmarks in Configuration**

- Follow the steps before to create some folders inside bookmarks  
- Go to Content and Data > Bookmarks   
- Upper right in Product Menu Bars > click on ellipsis > Configuration  
- Change root folder

https://github.com/DiegoHu97/liferay-portal/assets/91208451/7bee7490-50f8-46a7-8bae-bf04dcee4e6f

**Case 4: Edit Folder in bookmarks in Asset Publisher**

- Follow the steps before to create some folders inside bookmarks  
- Go to Content and Data > Bookmarks   
- Create a Bookmark  
- Go to Site Builder > Pages > Create a Content Page  
- Add an Asset Publisher to the CP  
- Click on Configuration in Asset Publisher  
- Select Dynamic   
- In Source tab > select Bookmarks Entry  
- Go to the Content Page view  
- Click on edit the bookmark  
- Move the bookmark to another folder

https://github.com/DiegoHu97/liferay-portal/assets/91208451/3e1b6635-b066-46fc-98db-9358c5baa935

**Case 5: Edit folder in Documents and Media widget**

- Go to Content and Data > Documents and Media > Create a folder and a child folder  
- Go to Site Builder > Pages > Create a Content Page  
- Add a Documents and media widget > Go to it's configuration  
- Go to Folders Listing section > Select a root folder

https://github.com/DiegoHu97/liferay-portal/assets/91208451/c10c3333-296d-4b08-b197-1c7697617f44

**Case 6: Edit folder in Media Gallery widget**

- Go to Content and Data > Documents and Media > Create a folder and a child folder  
- Go to Site Builder > Pages > Create a Content Page  
- Add a Media Gallery widget > Go to it's configuration  
- Go to Folders Listing section > Select a root folder

https://github.com/DiegoHu97/liferay-portal/assets/91208451/d74c4aab-42d1-421c-a6fc-a6ce0f79d51a

**Case 7: Select folder when adding a Basic Document from Asset Publisher**

- Go to Content and Data > Documents and Media > Create a folder and a child folder  
- Go to Site Builder > Pages > Create a Widget Page  
- Add an Asset Publisher > Go to it's Configuration   
- Select Dynamic > In Asset Type > Document > Basic Document > Save  
- Go to the Asset Publisher view > Click on plus icon > Basic Document > Add a basic document

https://github.com/DiegoHu97/liferay-portal/assets/91208451/6815be99-9d25-4259-9383-ba8cef3ea04a

**Case 8: Move Categories in Message Boards**

- Go to Content and Data > Message Boards   
- Create a Category and a child Category inside it   
- CLick on the child ellipsis > Move

https://github.com/DiegoHu97/liferay-portal/assets/91208451/eaede816-d427-483b-b951-c65c68b26283

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/15186

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:close

**Comment by BarbaraCabrera** [comment]
Hi again, guys! 😅 
After discussing it with my team we realize that probably this pr will break some poshi test that should be fixed so I'm back to this pr just to suggest that @DiegoHu97 add to this pr this commit (3ad5b8915ec08074b1cf571735ac36f1ed464860) to make this pr work and to add the necessary changes in the poshi tests. In the meantime, the other pr will be on hold until Brian merge this one so I can work on my own tests too.
Let me know your thoughts about it 😄

**Comment by BarbaraCabrera** [comment]
ci:reopen

**Comment by DiegoHu97** [comment]
ci:report:2538422450

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:report:2539267926

**Comment by ealonso** [comment]
@DiegoHu97 I think you need to update LocalFile.WebContentExportImport#MoveImportedWebContentArticlesToFolders

**Comment by DiegoHu97** [comment]
Hey @ealonso, teh test works fine on local, forwarding te PR

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:report:2539796461

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
