### PR TITLE
LPD-21918 Allow to delete repositories with missing configurations

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-21918

In some cases (e.g. Sharepoint) it is possible to delete repository configurations before their corresponding repositories.  Once this is done, repository deletion will fail, as it will try to read the configuration.

# How am I fixing it?

By ignoring the `UndeployedRepository*Exception` when trying to delete the repository. As the user is trying to remove it, the absence of the configuration should have no consequences.

# How can you verify that it works?

Follow the steps described in https://liferay.atlassian.net/browse/LPD-21918.

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2558625704

**Comment by jkappler** [comment]
@adolfopa, failures don't seem related to the changes, but will run relevant again just in case

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:report:2558681960

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
