### PR TITLE
LPD-29066 Sites and Library displays all sites depending on the users navigation

### PR DESCRIPTION
**Pull request by jkappler**
Sites and Library displays all sites depending on the users navigation

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-29066)

Depending on the navigation by the user, all sites are shown when selecting content in a web content display widget

# How am I fixing it?

Maintain the parameters needed to show the sites correctly

# How can you verify that it works?

Execute the unit tests that are included or follow the steps in the ticket

wcd

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:22434702

**Comment by jkappler** [comment]
No unique failures, so forwarding

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
