### PR TITLE
LPD-22366 Blogs connect categories selector

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:report:2563904816

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by jkappler** [comment]
@robertoDiaz, there was a conflict with BChans branch because of the language key that was changed, so I updated accordingly

**Comment by jkappler** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:report:2564091225

**Comment by robertoDiaz** [comment]
ci:forward:force

**Comment by robertoDiaz** [comment]
ci:forward:force

**Pull request closed without merging**
