### PR TITLE
LPD-28315 Release FF - Removal: Reorganizing permissions and schedule configuration on Web Content Editor

### PR DESCRIPTION
**Pull request by Mikellorza**
### What is this trying to solve?
https://liferay.atlassian.net/browse/LPD-28315

Delete release feature Flag LPD-15596
 
### How am I fixing it?

Deleting feature flag

### How can you verify that it works?

Disabling or deleting all feature flags that you have in your bundle and going to content management and also check if these requirement are working as expected:

1. On the edition of a Web Content there should be the ellipsis menu with the following options:
- View Source
- Permissions

2. When a user with permissions to change permissions of a web content clicks on “Publish” a pop-up will open where he can see and manage the permissions of that web Content.

- The user can select if the content is viewable by the guest role, site members or owner. And in more options manage the rest of permissions of the Guest Role and Site Members considering what they have selected on the viewable drop down. (This should work exactly the same as it works now on the creation)

- When the user clicks “Publish” the content will publish.

- The pop-up should only appear the first time the content is being created, meaning there is no previously version (draft, published, ect) created.

3.When clicking the Publish button a drop down will appear with 2 different options: Publish and Schedule Publication

- When clicking the Schedule option

      if the content is not already created, meaning there is no draft or another version created → a pop-up will appear where the user can select a date and time to publish the content and manage the permissions of the content (related with story LPD-6769: Check/ Edit Web Content Permissions in the edition and when Publishing 
      CERRADA
       )
      
      if the content has been already created, there is an existing version (draft, published, etc) → a pop-up will appear where the user can select a date and time to publish the content.

- The date and time can not be in the past. An error should appear if the user selects a past date.

- The user needs to enter a valid date.

- The date and time selected should clearly show the timezone to which it refers.

- When the user clicks Schedule. A schedule version is created and a Success toast with the scheduled date should appear.

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by jkappler** [comment]
@Mikellorza, there's a playwright error. Unsure if it's from removing the FF

**Comment by Mikellorza** [comment]
ok @jkappler I am going to review it again.

thanks for heads up!

**Comment by Mikellorza** [comment]
ci:report:16461717

**Comment by adolfopa** [comment]
ci:report:16461717

**Comment by Mikellorza** [comment]
@jkappler  I reviewed the error and it is not related with the changes of the PR. I will fix it in another PR.  So, let's move to brian.

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:stop

**Comment by Mikellorza** [comment]
@jkappler Analyzing the error more deeper I found out that is is related with the changes of this PR. Sorry for the confusion.

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1407401_9981

**Comment by Mikellorza** [comment]
ci:report:16870494

**Comment by Mikellorza** [comment]
There are 3 uniques failing tests:

1. Objects: this is not related with this PR
2. Journal article playwright test: there are some fluky tests but we have to pay attention reinforce them to do not fail.
3. Poshi fluky test

So, let's go again to forward again.

**Comment by Mikellorza** [comment]
ci:forward

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by Mikellorza** [comment]
ci:report:17697127

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:stop

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:19008212

**Comment by Mikellorza** [comment]
ci:report:19008212

**Comment by Mikellorza** [comment]
It seems like is not taking into account last changes about playwright tests :(

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:19664335

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
I've just rebase with master because we have some fix about semantic versioning in journal-api and maybe this is root of the stable issues. See https://github.com/liferay/liferay-portal/commit/bb8c9d28d99c8005209088e9a361c965ecca197c  and https://github.com/liferay/liferay-portal/commit/f1a9941e6cbeae7db2dab48fc3cb480a3ad75396

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
It seems there is an smoke error failing every time in stable suite, so, I am going to fix it because if not if impossible to move forward to brian :(

**Comment by Mikellorza** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:20489026

**Comment by jkappler** [comment]
@Mikellorza, I'm unsure, the failure for journal-web/journalArticle.spec.ts still happens, but I think it's not related. If you feel this way, then lets forward this

**Comment by adolfopa** [comment]
@Mikellorza if the playwright failure is not reproducible in your local, we can forward this.

**Comment by Mikellorza** [comment]
Failing playwright test is not related with the changes of the PR and it seems an smoke test, so, finally go to Brian.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
