### PR TITLE
LPD-28842 Cannot select web content from Global Site when selecting site scope

### PR DESCRIPTION
**Pull request by jkappler**
Cannot select web content from Global Site when selecting site scope

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-28842)

In previous versions, the users could select web content from Global Site without the need to change the scope in the configuration. This was lost during a bug fix.

# How am I fixing it?

Just add the Global Site to the Sites that the user can select web content from

# How can you verify that it works?

Follow the tests in the ticket or run the unit tests

global

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:20468338

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
