### PR TITLE
LPD-37380 Document types are not being deleted from the index

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-37380

Document tyoes are not being deleted from the index and this is causing some errors when we are using recently created headless apis : https://liferay.atlassian.net/browse/LPD-32248 

# How am I fixing it?

Adding  annotation : `@Indexable(type = IndexableType.DELETE) ` to delete DLFileEntryType from the index

# How can you verify that it works?

try to:

1. Go to documents & media and create a document type in the defaut site
2. Immediately afterwards, delete above document type.
3. Enable FF https://liferay.atlassian.net/browse/LPD-32247
4. Go to swagger http://localhost:8080/o/api? and try to get document type from the default site using getSiteDocumentDataDefinitionTypesPage

and:

Run updated test

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:21554437

**Comment by Mikellorza** [comment]
Running again relevant suite because of if semantic error of semantic-versioning-jdk8/0/0 with build-common-java.compile error is related with this PR.

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:22567490

**Comment by Mikellorza** [comment]
I have been able to verify that there is no failing test related to this PR. So, let's move to Brian.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
