### PR TITLE
LPD-20723 Clay link is translating asset titles/names by default in vertical card

### PR DESCRIPTION
**Pull request by Mikellorza**
Pending to core infra PR: https://github.com/liferay-core-infra/liferay-portal/pull/6780

bug: https://liferay.atlassian.net/browse/LPD-20723

Description
------
I have observed that we have some assets what we are translating the link to the details because the clay link is developed with this behavior by default. So, this PR contains the modifications to not translate the following assets:

1. Journal article and journal folders for all display views.
2. DL file and DL folder in table view.
3. KB article and KB folder in table view.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:forward

**Review by boton — APPROVED** [review]
LGTM! Nice job @Mikellorza 

I haven't tested but I taked an eye to https://github.com/liferay-frontend/liferay-portal/pull/4075 before this PR and both look good.

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
Sorry @Mikellorza, I missed your [forward comment](https://github.com/liferay-content-management/liferay-portal/pull/5262#issuecomment-2019800382).

I followed the `frontend review needed` tag but I'm not sure; Are we still applying this tag?

**Comment by Mikellorza** [comment]
ci:reevaluate:1347401_6009

**Comment by Mikellorza** [comment]
ci:reevaluate:1347401_6009

**Comment by Mikellorza** [comment]
ci:report:2554937310

**Comment by Mikellorza** [comment]
Hey @marcogalluzzi ,

For some reason [here](https://github.com/liferay-content-management/liferay-portal/pull/5262#issuecomment-2020790994) is failing your recent created test for DLViewEntriesDisplayContextTest, see https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/384394/testReport/com.liferay.document.library.web.internal.display.context/DLViewEntriesDisplayContextTest/classMethod_2/, please take a follow up in other pr's to see if is a isolated fail or it is failing in a common way.

**Comment by Mikellorza** [comment]
Failed test is not related with the changes of this PR. Let's move to brian.

**Comment by Mikellorza** [comment]
ci:forward:foce

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
