### PR TITLE
LPD 33130 Allow use the extensions in the DL  Friendly URLs

### PR DESCRIPTION
**Pull request by robertoDiaz**
[Add ability to include file extension in the document URL](https://liferay.atlassian.net/browse/LPD-33130)

# What is this trying to solve?

Allow customers add the extension of the file entry in its friendlyURL so they could manage it.

# How am I fixing it?

Adding a new configuration to control if the portal should allow and generate by default this kind of urls with extension and applying it where needed (web and service layers)

# How can you verify that it works?

Added 10 new tests in `DLFileEntryLocalServiceTest` with this name patterns:

- _testAddFileEntryWith\*FriendlyURL*ExtensionWhen[Enabled/Disabled]FriendlyURLWithExtension_
- _testUpdateFileEntryWith\*FriendlyURL*ExtensionWhen[Enabled/Disabled]FriendlyURLWithExtension_

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
SF is not failing in local....

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by robertoDiaz** [comment]
ci:test:report

**Comment by robertoDiaz** [comment]
ci:report: 56139067

**Comment by robertoDiaz** [comment]
ci:report:56139067

**Comment by robertoDiaz** [comment]
errors seem unrelated

**Comment by robertoDiaz** [comment]
ci:test:content-management

**Comment by robertoDiaz** [comment]
ci:report:56602864

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
