### PR TITLE
LPD-39468 Back icon in notifications

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[Link to ticket](https://liferay.atlassian.net/browse/LPD-39468)
Back button disappears when clicking Notifications/Requests List on Notifications

# How did I fix it
I added the back url as a parameter to the link for the tabs, thus always is a back button

Screenshot 2024-10-16 at 11 50 22

# How can you test it
Follow the steps described in the issue, or run `npm run playwright -- test -g 'LPD-39468' --reporter list`
```
npm run playwright -- test -g 'LPD-39468' --reporter list --repeat-each=5

> @liferay/playwright@1.0.0 playwright
> playwright "test" "-g" "LPD-39468" "--reporter" "list" "--repeat-each=5"


Running 5 tests using 1 worker

  ✓  1 [notifications-web] › notifications-web/notifications.spec.ts:18:1 › Back button is present while navigating between tabs (39.1s)
  ✓  2 [notifications-web] › notifications-web/notifications.spec.ts:18:1 › Back button is present while navigating between tabs (26.7s)
  ✓  3 [notifications-web] › notifications-web/notifications.spec.ts:18:1 › Back button is present while navigating between tabs (17.4s)
  ✓  4 [notifications-web] › notifications-web/notifications.spec.ts:18:1 › Back button is present while navigating between tabs (20.0s)
  ✓  5 [notifications-web] › notifications-web/notifications.spec.ts:18:1 › Back button is present while navigating between tabs (19.4s)

  5 passed (2.6m)
```

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
@ambrinchaudhary, jsp change looks good :heart:

**Comment by ambrinchaudhary** [comment]
Thanks for your review @jkappler. I still need to work on solving SF errors...

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@ambrinchaudhary, fixed sf :)

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:44362482

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
