### PR TITLE
LPD-23376 Fix failing KB tests

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-23376

As part of https://liferay.atlassian.net/browse/LPD-15162, the JDK versions were bumped. This broke KB, as the ASM version required by the markdown parser doesn't support newer versions.  This is a release blocker, so I'm (partially) reverting those changes until we can replace the parser (or deprecate the feature).

# How am I fixing it?

By partially reverting e8d45abc5320a7e4f155e5ba793848c00d191eb2.

# How can you verify that it works?

All integration tests in `knowledge-base-test` pass.

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2561187482

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_13092

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Errors are unrelated. I will retry 'stable' again; if it fails I'll forward manually.

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
