### PR TITLE
LPD-31271 Technical Task | Resolution filter in Content Dashboard

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LPD-31271

# What is this trying to solve?

1. Add resolution filter to Content Dashboard
2. Add resolution to information panel

# How am I fixing it?

Add resolution filter to Content Dashboard

# How can you verify that it works?

Run included integration tests.

### CODE REVIEW

**Comment by Mikellorza** [comment]
@jkappler I've just deleted any option for aspect ratio and resolution filters and also I 've changed label format for size filter.

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:stop

**Comment by Mikellorza** [comment]
ci:stop

**Comment by Mikellorza** [comment]
ci:help

**Comment by Mikellorza** [comment]
ci:test:help

**Comment by Mikellorza** [comment]
ci:test:stop

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:44263021

**Comment by Mikellorza** [comment]
ci:report:44263021

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
There are no unique failures related with this pr. So, let's move forward to brian.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
