### PR TITLE
LPD-25575

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPD-25575

When adding a document by external reference code through the headless API it does not have a _folderId_ field. However, this information can be passed along through the _document_ object. These changes allow for getting the folder from this object before defaulting to the root folder.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
ci:report:2568992134

**Comment by jonathanmccann** [comment]
@adolfopa @jkappler The failing test (testPutAccountByExternalReferenceCode) doesn't seem related. Is this safe to force forward?

**Comment by jkappler** [comment]
yes @jonathanmccann!

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
