### PR TITLE
LPD-6963 Rename fieldset based on FF

### PR DESCRIPTION
**Pull request by boton**
# Issue: https://liferay.atlassian.net/browse/LPD-6963

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by boton** [comment]
ci:reevaluate:1307401_8812

**Comment by jkappler** [comment]
ci:report:2541297860

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
