### PR TITLE
LPD-38870 Skip test if not properly configured

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38870

The tests always fail locally, as it assumes Google Drive creds will be available in system properties.

Note that the fix for this same test in the CI was sent in https://liferay.atlassian.net/browse/LRCI-4722. It is expected for the test to fail in the CI until that PR is merged.

# How am I fixing it?

By skipping the test if not propertly configured.

# How can you verify that it works?

Run the test with no configuration and see it pass.

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Learned something new today @adolfopa, thanks!

**Comment by jkappler** [comment]
@adolfopa, seems tests are related

**Comment by adolfopa** [comment]
@jkappler This is expected, the actual fix was sent in https://liferay.atlassian.net/browse/LRCI-4722 (sorry, I forgot to mention it in the PR description :bow: ).

This PR simply makes the test runnable locally, by including those extra assumptions. But until the reference LRCI ticket gets merged those tests will keep failing.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
