### PR TITLE
LPD-33602 Delete document metadata sets via headless API

### PR DESCRIPTION
**Pull request by SamZiemer**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-33602

Create a new endpoint for Headless API to delete DocumentMetadataSets

# How am I fixing it?

Added a new endpoint for the delete method

# How can you verify that it works?

Run the tests in DocumentMetadataSetResourceTest

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
cc/ @balazssk

**Comment by adolfopa** [comment]
ci:forward

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:relevant

**Pull request closed without merging**
