### PR TITLE
LPD-32573 Use the url mapping to avoid missing parameters on language change

### PR DESCRIPTION
**Pull request by robertoDiaz**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-32573

# How am I fixing it?

Using the existing implementations of FriendlyURLMapper to get the full url and avoid missing parameters

# How can you verify that it works?

Run the included automated tests.

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:content-management

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:report:13709689

**Comment by robertoDiaz** [comment]
@adolfopa Test seem unrelated.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
