### PR TITLE
LPD-35134 fix test: Icon menu should close when another menu opens

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi Team,
I would like to kindly ask to review my PR

Technikal task: https://liferay.atlassian.net/browse/LPD-35134 original issue: https://liferay.atlassian.net/browse/LPD-26435
 
Added clickAndExpectToBeVisible because it could not find the drop down menu, now it is waiting for that to be visible.

image

Thanks!

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
@DiegoHu97 @jkappler Looks like this is deleting the main wikinode in the end, which is used by the second, that is causing the failure. I will correct that later

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
image
@DiegoHu97 Should be both fine now. Thanks

**Review by DiegoHu97 — APPROVED** [review]
LGTM! it works fine :fireworks:

**Comment by DiegoHu97** [comment]
ci:forward

**Pull request closed without merging**
