### PR TITLE
LPD-34760 & LPD-34923 Autosave is not enabled until all required fields are completed

### PR DESCRIPTION
**Pull request by DiegoHu97**
LPD-34760 & LPD-34923 Autosave is not enabled until all required fields are completed

# What is this trying to solve?

- Verify that every required field is filled when autosaving. This verification was already implemented in this task: https://liferay.atlassian.net/browse/LPD-32874
- Chnage autosave error 
- Remove title alert error when FF LPS-114700 is enabled as described in the requirements 
- Create test for the story

[Link to ticket](https://liferay.atlassian.net/browse/LPD-34760)
[Link to ticket (test)](https://liferay.atlassian.net/browse/LPD-34923)

# How am I fixing it?

- Change language key
- Remove alert error for the title when LPS-114700 is enabled
- Create playwright test 

# How can I test it?

- Follow steps in the test 

image

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Review by boton — COMMENTED** [review]
LGTM! I left some minor comments

The playwright test is working on CI. 

image

Can you please run the test 10 times using `--repeat-each 10` and attach a screenshot to avoid a flaky test?

**Comment by DiegoHu97** [comment]
Hey @boton I just made the changes, thank you for the review! The test result:

**Review by boton — APPROVED** [review]
LGTM!

**Comment by boton** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:report:75866304

**Comment by DiegoHu97** [comment]
Failures are not related

**Comment by DiegoHu97** [comment]
ci:forward:force

**Pull request closed without merging**
