### PR TITLE
LPD-22600 Add DEFAULT_LANGUAGE_ID to indexing

### PR DESCRIPTION
**Pull request by gergelyszalay**
Issue is https://liferay.atlassian.net/browse/LPD-22600. If I upload a document, after I change the site dafult language, the search does not display the document's title and content.

Root cause: DLFileEntryModelSummaryContributor.java the getSummary() method cannot get content and title from the document, because the document doesn't have Field.DEFAULT_LANGUAGE_ID and it uses the portal default, and not the document one.

Solution. add to the document indexing the default language id in DLFileEntryModelDocumentContributor.java, so after re-indexing it, it changes the default language together with the localized title and content.

tested it locally and solves the issue

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@gergelyszalay

**Comment by jkappler** [comment]
ci:report:2561292365

**Review by jkappler — CHANGES_REQUESTED** [review]
@gergelyszalay, DLFileEntryIndexerIndexedFieldsTest is failing for the PR, we have to adapt 😞

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:report:2561449685

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
