### PR TITLE
LPD-31827 | Add ExternalReferenceCode to Blogs Images (Part 1)

### PR DESCRIPTION
**Pull request by bakayattila**
task ticket:
https://liferay.atlassian.net/browse/LPD-31827
Story ticket:
https://liferay.atlassian.net/browse/LPD-27622

------

The pull might seem a bit empty but https://liferay.atlassian.net/browse/LPS-130893 already implemented the ERC in the service updated the add method and created a get for ERC. In this pull, I added the missing delete by ERC.  I did not create an update by ERC as there is no update method for BlogPostingImage at all.

- [x] add with ERC [addFileEntry](https://github.com/bakayattila/liferay-portal/blob/f908f8fa9e0b8c56a702ee770ebdc83d9a5ddf94/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppLocalServiceImpl.java#L139C4-L139C33)
- [x] get/fetch by ERC [fetchFileEntryByExternalReferenceCode](https://github.com/bakayattila/liferay-portal/blob/f908f8fa9e0b8c56a702ee770ebdc83d9a5ddf94/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppLocalServiceImpl.java#L592-L600), [getFileEntryByExternalReferenceCode](https://github.com/bakayattila/liferay-portal/blob/f908f8fa9e0b8c56a702ee770ebdc83d9a5ddf94/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppLocalServiceImpl.java#L667-L675  )
- [x] delete by ERC This pull

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @bakayattila, can we add some tests for this? Or are they included in Part2?

**Comment by bakayattila** [comment]
Hi @jkappler, I did not find any related test classes targeting any of these kinds of calls. If needed I can create an integration test for it. But as it is 90% service builder call. I don't really see the point. I think it is better to test it in the second part.

**Comment by jkappler** [comment]
@bakayattila, we have DLFileEntryLocalServiceTest and DLFileEntryServiceTest. We also test service builder calls on our code.

**Comment by bakayattila** [comment]
Should I add a test for the new method now or in part 2?

**Comment by jkappler** [comment]
Lets fwd it, and add a test later. Shouldn't be a problem since this is part of a story

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:53563977

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:54256871

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
