### PR TITLE
LPD-22454 Remove dev FF for Calendar Events epic

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:report:2558969390

**Comment by adolfopa** [comment]
@ambrinchaudhary com.liferay.asset.search.test.AssetSearcherStagingTest.testSiteRolePermissions() seems to be unique to this PR. Can you take a look at it?

**Comment by ambrinchaudhary** [comment]
ci:report:2559152372

**Comment by ambrinchaudhary** [comment]
> @ambrinchaudhary com.liferay.asset.search.test.AssetSearcherStagingTest.testSiteRolePermissions() seems to be unique to this PR. Can you take a look at it?

Hey @adolfopa, that error didn't really seem to be related to the pull, so I run `ci:test:relevant` again and now there are not unique failures. However, now the ci:test:stable fails... Looks like CI is being unstable these days... 😱

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
