### PR TITLE
LPD-30426 Incorrect setting of WC structure Default Values

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-30426

Fix the setting of the Default Values of a Web Content Structure

# How am I fixing it?

Handling also the nested fields.

# How can you verify that it works?

Follow steps in issue.
Also run:  `ant -f build-test.xml run-selenium-test -Dtest.class=WebContentStructures#EditStructureDefaultValuesBasedOnFieldset`

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1307401_9588

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Tests are not failing in locat, so executing relevant again

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
