### PR TITLE
LPD-33786 Technical Task | Test Automation for LPP-52254

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-33786 LPD-33786 Technical Task | Test Automation for LPP-52254

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-33786

# How am I fixing it?

Adding playwright test.

# How can you verify that it works?

Run the included automated tests.

image

# Commits

- **LPD-33786 Create JSONWebServicesDepotApiHelper to create and delete asset libraries/depot entries**
- **LPD-33786 create depot-web module on playwright to test asset libraries**
- **LPD-33786 add method to post a tag on an asset library**
- **LPD-33786 create test to check if the asset library/depot only see the tags created by them or the global**
- **LPD-33786 the tags form another depot is not shown**
- **LPD-33786 new JSONWebServicesDepotGroupRelApiHelper to connect asset libraries to sites**
- **LPD-33786 connect to the site and then check that the tag of the connected site does not appears**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:tset:playwright

**Comment by AliciaGarciaGarcia** [comment]
ci:test:playwright

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
conflict with master > rebased with master

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by DiegoHu97 — APPROVED** [review]
LGTM! :fireworks:

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Comment by DiegoHu97** [comment]
ci:forward

**Pull request closed without merging**
