### PR TITLE
LPD-39900 Remove FF - Limit file size in D&M for sites and mimetypes

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-39900 remove FF LPS-114786 uses

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-39900

We want to all the users have the avalability of Limit file size in D&M Component

# How am I fixing it?

remove any reference to the LPS-114786 Feature Flag

# How can you verify that it works?

Run the included automated tests.

# Commits

- **LPD-39900 no needed**
- **LPD-39900 remove FF uses**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by AliciaGarciaGarcia** [comment]
On draft because I want to pass a review ALLLL the test

/
/

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by AliciaGarciaGarcia** [comment]
all went smoottthly XD

ci:test:content-management - 6 out of 1000

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1367401_6879

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1277401_12868

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:report:49788904

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
@AliciaGarciaGarcia, changes look good to me :heart:

**Comment by jkappler** [comment]
still, don't know if this is related:

com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest,https://testray.liferay.com/#/project/35392/routines/45357/build/49788904/case-result/49795745/history,Unique,testElExpressionWithUndefinedVariablesJsp: java.lang.AssertionError: Completed in 1000ms. but the expected completion time should be less than 1000ms  at org.junit.Assert.fail(Assert.java:89)  at org.junit.Assert.assertTrue(Assert.java:42)  at com.liferay.portal.kernel.test.performance.PerformanceTimer.close(PerformanceTimer.java:73)  at com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest.testElExpressionWithUndefinedVariablesJsp(JspServletPerformanceTest.java:127)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)  at java.lang.Thread.run(Thread.java:750)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management - 0 out of 1 jobs passed in 1 minute

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by AliciaGarciaGarcia** [comment]
ci:report:51460098

**Comment by AliciaGarciaGarcia** [comment]
relevant has 2800+ incomplete test so : relaunching

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:report:52236353

**Comment by AliciaGarciaGarcia** [comment]
errors seems not related with this PR

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:53634415

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
