### PR TITLE
LPD-34159 | Headless API structured content response shows null instead of empty string values ""

### PR DESCRIPTION
**Pull request by bakayattila**
### What is this trying to solve?
https://liferay.atlassian.net/browse/LPD-34159

### How am I fixing it?
The String.ValueOf did not handle the case well when the data field in the Value was null. It returned a "null" instead of an empty string. The GetterUtil.getString returns an empty string in case of null.

### How can you verify that it works?

To test run:
`gw testIntegration --tests StructuredContentResourceTest.testGetStructuredContentWithDataDefinitionEmptyDefaultValue`

Or manually test based on the LPD steps

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
