### PR TITLE
LPD-22291 add user only after share to select the proper user on dropdown

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
…down

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sharing

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia There's something wrong with some of your PR descriptions? There were a couple of PRs from you where they looked weird.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2558505086

**Pull request closed without merging**
