### PR TITLE
LPD-22238  Asset Library: Cannot configure mimetype limits for DM

### PR DESCRIPTION
**Pull request by NemethNorbert**
[LPD-22238](https://liferay.atlassian.net/browse/LPD-22238)
What is this trying to solve?
The FileSizeMimetypes react component did not load properly

[Link to ticket](https://liferay.atlassian.net/browse/LPD-26863)

How am I fixing it?
I imported the module directly from document-library-web

How can I test it?
follow ticket description

Why no test?
I had to fix an import there is no additional business logic that needs to be tested here, the component is covered by
LocalFile.DepotMimeTypeLimits#ALTakesEffectOverInstanceLimit
LocalFile.DepotMimeTypeLimits#CanLimitMultipleMimeTypesSize
LocalFile.DepotMimeTypeLimits#CanLimitSizeOnlyInCurrentDepot
LocalFile.DepotMimeTypeLimits#SystemTakesEffectOverALLimit

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @NemethNorbert 

you can put on the description is that no test are needed because 

LocalFile.DepotMimeTypeLimits#ALTakesEffectOverInstanceLimit
LocalFile.DepotMimeTypeLimits#CanLimitMultipleMimeTypesSize
LocalFile.DepotMimeTypeLimits#CanLimitSizeOnlyInCurrentDepot
LocalFile.DepotMimeTypeLimits#SystemTakesEffectOverALLimit

Cover this :)

**Review by boton — APPROVED** [review]
LGTM!

I tested and it's working ❤️ 

## Before PR
image

## After PR

image

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
I supouse that the link to the ticket is a bad copy paste 😄 

> [Link to ticket](https://liferay.atlassian.net/browse/LPD-26863)

It would be of great help if you added some screenshots or videos to the following PRs 🥺 🙏

**Comment by adolfopa** [comment]
ci:reevaluate:1307401_9377

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
