### PR TITLE
LPD-27921 Remove Release FF for AI image generation in DAM

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-27921

I'm removing the Release Feature Flag for the AI Image Creation (DALL-E option)

# How am I fixing it?

Fix code everywhere

# How can you verify that it works?

All existing tests have been executed successfully. Actually, I had to fix one POSHI test.

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]

**Review by SamZiemer — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
> I am not very familiar with FF removal tickets, do we need to remove the FF from [AICreatorImages.testcase](https://github.com/SamZiemer/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/documentmanagement/aiimagegeneration/AICreatorImages.testcase#L4) and [Language.properties](https://github.com/SamZiemer/liferay-portal/blob/master/modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties#L7330-L7331)? If not, the rest looks good to me and this can be forwarded.

Hi @SamZiemer, yes we need to remove the flag also from testcase and language properties, see my commits:

[f21af07](https://github.com/liferay-content-management/liferay-portal/pull/5528/commits/f21af07e11c8bccb6cbf23594f3c7d24ac2bc383) and [98e59dc](https://github.com/liferay-content-management/liferay-portal/pull/5528/commits/98e59dc8f70f397da11196d95e2fe70d269987dd)

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:report:12019052

**Comment by marcogalluzzi** [comment]
Unique failures not related to this PR. Forcing forward.

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
