### PR TITLE
LPD-6589 Add fieldName as prop in Rich Text field

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Hey @veroglez, thank you for this pull. 
Although, this change is already included in https://github.com/liferay-content-management/liferay-portal/pull/5193, which is also ready to forward. 
Not sure if this could cause conflicts or not. Just mentioning @NemethNorbert and @DiegoHu97 to be aware.

**Comment by DiegoHu97** [comment]
Hey @veroglez, this change is already included in this PR commit: 84a27f7 :smile:   
CC:  @ambrinchaudhary

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
