### PR TITLE
LPD-26281 Add new finder to generate a new index

### PR DESCRIPTION
**Pull request by robertoDiaz**
No tests needed since it's a performance improvement.

See https://liferay.atlassian.net/browse/LPD-26281?focusedCommentId=2655630 for more data and for information about the test we've perform with a real database.

In this case the use of the dslQuery is required (in order to take advantage of sql functionalities over service builder capabilities) but an index is needed in order to avoid database locks and bottlenecks 

cc/ @lfbesada

### CODE REVIEW

**Review by adolfopa — CHANGES_REQUESTED** [review]
@robertoDiaz Can you replace the dynamic query in https://github.com/liferay/liferay-portal/commit/4d9f6d2d19ad883fba85cf1c3771997f99c327f3 by this new method?

Also, can you write explicitly in the description that this is a performance improvement, and so this needs no new tests? It is fine to include the link to the comment, but it will make things easier if we include all the info here.

**Comment by robertoDiaz** [comment]
> @robertoDiaz Can you replace the dynamic query in [liferay@4d9f6d2](https://github.com/liferay/liferay-portal/commit/4d9f6d2d19ad883fba85cf1c3771997f99c327f3) by this new method?

Hi, I agreed this solution with Lourdes.

The SQLQuery from https://github.com/liferay/liferay-portal/commit/4d9f6d2d19ad883fba85cf1c3771997f99c327f3 requires some functionalities that service builder does not provide, (the use of disctinct group) so we had get all the elements and filter them programatelly (that could also impact in performance)


> Also, can you write explicitly in the description that this is a performance improvement, and so this needs no new tests? It is fine to include the link to the comment, but it will make things easier if we include all the info here.

Sure I will. I didn't want to be so explicit in public about a performance improvement.

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:stable

**Comment by robertoDiaz** [comment]
Error seems related since it fails when using the new index restriction IX_84BB53FA

Analyzing

**Comment by robertoDiaz** [comment]
ci:test:stable

**Comment by robertoDiaz** [comment]
ci:test:stable

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Pull request closed without merging**
