### PR TITLE
LPD-42376 Change groupId to groupExternalReferenceCode in Web Content Display

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-42376

# How am I fixing it?

Change templateKey to templateExternalReferenceCode in Web Content Display.

# How can you verify that it works?

There is already a test to cover this, added in the las pr:  https://github.com/liferay-content-management/liferay-portal/pull/6077/commits/8504492706478a916dbe3714d1aa4225f3792749

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:77630179

**Comment by Mikellorza** [comment]
ci:help

**Comment by Mikellorza** [comment]
ci:test:content-management

**Comment by Mikellorza** [comment]
ci:test:content-management-playwright

**Comment by Mikellorza** [comment]
ci:reevaluate:1307401_10501

**Comment by Mikellorza** [comment]
As I am not clear if the failed test are related or not, I am going to run them again

**Comment by Mikellorza** [comment]
ci:report:77950387

**Comment by Mikellorza** [comment]
ci:test:content-management

**Comment by Mikellorza** [comment]
ci:report:78905935

**Comment by Mikellorza** [comment]
Failed tests are not related with the changes of this PR. So, we are ready to move forward.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
