### PR TITLE
LPD-23065 Structure Boolean Field defaults to Null

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPD-23065

Controls the case of checkbox field with no interaction in the interface.

## Change summary:

* Takes into account the checkbox field when retrieving the structured content fields though a headless call

## Test Scenario No 1

* Create a new Structure: Content & Data > Web Content > Structures > New
* Drag and Drop the Boolean Field
* Name it “test-struct” and click Save
* Publish a new Web Content called “test-wc” using “test-struct” and leave the Boolean field unchecked.
* From API explorer, go to the getStructuredContent endpoint(/v1.0/structured-contents/{structuredContentId})
* Enter the structuredContentId for “test-wc“ and click Execute
* See that contentFieldValue for the checkbox contains the correct boolean value

## Test Scenario No 2

* After following the first scenario, set the X-Accept-All-Languages to true to the request and click Execute
* See that contentFieldValue_i18n for the checkbox contains the correct boolean value

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2560709022

**Comment by jkappler** [comment]
AccountResourceTest failure is not related to the changes

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
