### PR TITLE
LPD-37885 Set LPD-11228 (Journal Autosave) as Release FF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[Link to ticket](https://liferay.atlassian.net/browse/LPD-37885)

Screenshot 2024-10-02 at 13 15 14

Note: on hold until https://github.com/liferay-forms/liferay-portal/pull/2621 is merged and tested.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by DiegoHu97 — APPROVED** [review]
LGTM! I will forward it when we make sure https://github.com/liferay-content-management/liferay-portal/pull/5901 has no failing tests

**Comment by DiegoHu97** [comment]
ci:report:30694896

**Comment by DiegoHu97** [comment]
Failures not related

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
