### PR TITLE
LPD-26190 update amazon awssdk libs to newer version

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Updating `software.amazon.awssdk` to `2.25.53`

The new version uses `netty-nio-client:2.25.53` that includes `netty-codec-http:4.1.108`

**This is a library upgrade, so no additional tests necessary. Existing regression suite should catch any outstanding issues.**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — CHANGES_REQUESTED** [review]
@AliciaGarciaGarcia The changes look good, but you need to include in the description why this doesn't include any tests; something like this should be enough:

> This is a library upgrade, so no additional tests necessary. Existing regression suite should catch any outstanding issues.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translation

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translation

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translation

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2571057796

**Comment by AliciaGarciaGarcia** [comment]
the ci:test:translation - 45 out of 56 jobs passed in 1 hour 57 minutes errors was due : https://liferay.atlassian.net/browse/LPD-26394

**Comment by AliciaGarciaGarcia** [comment]
hi @adolfopa 

You are ok with the comment and the PR?

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Yes, it is fine.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
