### PR TITLE
LPD-24662 BUG Blogs friendlyURL history button

### PR DESCRIPTION
**Pull request by boton**
# Issue: https://liferay.atlassian.net/browse/LPD-24662

## Before the PR
image

## After the PR
image
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Review by robertoDiaz — APPROVED** [review]
Functional analysis looks good.

Good to go

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
