### PR TITLE
LPD-24176 Add test to our daily routine and link playwright to relevant

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-24176

Execute the our playwright test in our `ci:test:content-management` routine.

This PR links our playwright test to our current relevant suite.

For example, if some code on documents and media is updated the playwright test on [document-library-web](https://github.com/liferay/liferay-portal/tree/59431935c110c3274bde292e0587ad8bcd3e2248/modules/test/playwright/tests/document-library-web) will execute in on the PR with the `ci:test:relevant` command.

# How am I fixing it?

I'm following the steps shared in [slack channel](https://liferay.slack.com/archives/C06A59K5D46/p1713174409459909) and connecting the points with @sandrodw3 's help

# How can you verify that it works?

I'm not sure, we can check if it is included in our daily routine in the future.

# Why doesn't this include any test?

It's test infra-related changes, we can not test it.

### CODE REVIEW

**Comment by boton** [comment]
I have some mistakes fixing it

**Comment by boton** [comment]
fixed!

**Comment by boton** [comment]
ci:test:sf

**Review by robertoDiaz — APPROVED** [review]

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
