### PR TITLE
LPD-18667 Use action request instead of uploadPortletRequest

### PR DESCRIPTION
**Pull request by SamZiemer**
https://liferay.atlassian.net/browse/LPD-18667

Resending with a new fix as mentioned here: https://github.com/liferay-content-management/liferay-portal/pull/5169#issuecomment-1964769675

We need to use the actionRequest to get the correct nodeId instead of the uploadPortletRequest.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
