### PR TITLE
LPD-25646 Show the author name

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
@robertoDiaz Sorry for jumping in here and apologies if this was already discussed elsewhere. Wouldn't this provide the wrong information in the following situation:

1. User1 creates a Web Content article
2. User2 edits the article
3. The message shows "Modified 2 Minutes ago by User1"

Shouldn't it show that User2 is the one who modified the article? Looking at the history of the article it shows the author of the latest content as User2.

**Comment by robertoDiaz** [comment]
Yes, I could confirm that.

I'll recheck with @jkappler this since I assumed that each version had it's own owner

**Comment by robertoDiaz** [comment]
We've discarded this.

We`ve concluded that current is the expected behavior

**Pull request closed without merging**
