### PR TITLE
LPD-16548 LPD-16549 Remove unused references

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-16548
https://liferay.atlassian.net/browse/LPD-16549

There are some unused references in DLApp wrapper classes. These are safe to remove.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Review by marcogalluzzi — APPROVED** [review]
Good! It seems to be safe, based also on GIT history

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
[LocalFile.ConnectACWithDXP#CheckIsPossibleConnectACWithValidToken](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1024448//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ConnectACWithDXP_CheckIsPossibleConnectACWithValidToken_) is failing in other pulls, so it is not related with this changes. Forcing forward...

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
