### PR TITLE
LPD-44108 Improve journalArticle.spec.ts > Can paginate Web Content in an Asset Publisher

### PR DESCRIPTION
**Pull request by DiegoHu97**
LPD-44108 Improve journalArticle.spec.ts > Can paginate Web Content in an Asset Publisher

# What is this trying to solve?
The test failed because when clicking in the widget page name it finds two locators, soI have improved the test creating and accessing the widget page by API and friendly URL.
The test failed on the release test failures and since then it has been passing but I found it interesting to improve the test.

[Link to ticket](https://liferay.atlassian.net/browse/LPD-44108)

# How can I test it?
Run the PW test 
image

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Comment by DiegoHu97** [comment]
Failures are not related

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
