### PR TITLE
LPD-19556 Use select resource button instead

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:depot

**Comment by austinchiang** [comment]
cc @robertoDiaz

**Comment by austinchiang** [comment]
Looks like there's still some issue with the tests :sob:

**Comment by robertoDiaz** [comment]
ci:forward

**Review by robertoDiaz — APPROVED** [review]

**Pull request closed without merging**
