### PR TITLE
LPD-18878 Convert to Release Feature Flag

### PR DESCRIPTION
**Pull request by jkappler**
Parent task: https://liferay.atlassian.net/browse/LPD-18441

The idea of the PR is to change to release feature flag. Also, changed the old LPS ticket to LPD ticket

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2544447645

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2544625378

**Comment by jkappler** [comment]
Errors are not related to the changes, also, no unique failure for the PR

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
