### PR TITLE
LPD-24377 Fix error when filtering by two or more tags/categories

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPD-24377 Filter by Tags does not work on DM nor Web Content 

With this fix the poshi test `LocalFile.DMFileEntry#FilesAreFilteredByExactTags` runs successfully

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Hey @liferay-frontend, I hope you don't mind I send this over our repo, as it fails in our components. See https://liferay.atlassian.net/browse/LPD-24377, it is caused by recent changes in https://liferay.atlassian.net/browse/LPD-21465

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
LGTM!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
