### PR TITLE
LPD-1769 obtain the list of the approved kb articles only

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPD-1769

 Reproduction steps

1) Create a scheduled KB article
2) Add the KB Display widget to a page

- LPD-1769 add new finder to obtain the main kbArticles by status
- LPD-1769 buildService
- LPD-1769 show only the approved kb articles when we are displaying them on the portal display
- LPD-1769 add test to ensure the behavior
- LPD-1769 add a test to schedule the kb article on playwright

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Review by marcogalluzzi — APPROVED** [review]
Good work!

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
