### PR TITLE
LPD-23383 old version tags are not case sensitive

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2563706169

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2563882091

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Do you think something similar may be happening in https://liferay.atlassian.net/browse/LPD-19714? In my tests it looks like the DB itself is broken before the upgrade, but it could be a configuration error on my part; maybe it is too a case sensitivity issue?

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa 
It can be, but my vote is that not (maybe i'm wrong)
looking at : 
https://testray.liferay.com/home/-/testray/case_results/2563885433?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1310865223%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1310865223%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc  
> 
https://testray.liferay.com/reports/production/logs/2024-04/test-1-28/test-portal-acceptance-pullrequest(master)/9325/functional-tomcat90-mysql57-jdk8/22/21/LocalFile.DMAutoTaggingUpgrade_ViewDMArchive72101/index.html.gz?authuser=0

the image showing is 
image

I can look into it on monday if you want (assign the LPD to me)

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2563912837

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2563912837

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1287401_9346

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2564340628

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2564514494

**Comment by AliciaGarciaGarcia** [comment]
https://testray.liferay.com/home/-/testray/case_results/2564518526/history?tab=result&hideFilterPin=true

**Pull request closed without merging**
