### PR TITLE
PD-26431 addAMImageEntry must always be executed in a new transaction, otherwise with large amounts of entries process never updates progress.

### PR DESCRIPTION
**Pull request by manuelRives**
# What is this trying to solve?

- https://liferay.atlassian.net/browse/LPD-26431 addAMImageEntry must always be executed in a new transaction, otherwise with large amounts of entries process never updates progress.

# How am I fixing it?

Modifying the adittion of addAMImageEntry making it write each transaction individually into the database.

# How can you verify that it works?

1. Upload a huge amount of image files. I start observing the behavior starting at 10 000 images.
2. Go to Control Panel/Adaptive Media, create a new resolution and start the Adapt Remaining operation for it.
3. The task never updates it’s progress until the full process is over.

# Why does this pull not include tests?

This cannot be observed reliably from a test. We'd need to check that a progress bar increases over time, which may lead to flakiness if the bar progresses too slowly or too fast.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by manuelRives** [comment]
ci:test:stable

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
ci:forward

**Pull request closed without merging**
