### PR TITLE
LPD-43452  migrate some Categories.testcase to integration tests (Vocabulary tests)

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-43452 Migrate AddVocabularyWith(Guest/SiteMember/Owner)ViewPermission to Integration test

This PR should be merged only after https://github.com/liferay-content-management/liferay-portal/pull/6150 because deletes some macros 

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-43452

To make the CI faster, is better to use integration/unit test than Poshi test.

# How am I fixing it?

Creating a test that summarize the behaviour that the POSHI tests were testing

# How can you verify that it works?

Run the included automated tests.

# Commits

- **LPD-43452 use service instead of Util**
- **LPD-43452 migrate AddVocabularyWithGuestViewPermission, AddVocabularyWithOwnerViewPermission, and AddVocabularyWithSiteMemberViewPermission to integration tests**
- **LPD-43452 no needed, covered on testAddEmptyNameVocabulary**

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Looks good. I'll let you do the forward when the other PR is ready.

**Comment by adolfopa** [comment]
ci:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
making same changes than on https://github.com/brianchandotcom/liferay-portal/commit/918f5c5ed919575fb20a73449d15044d70806cac

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
rebasing with Brian's master

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
