### PR TITLE
LPD-31827 | Add ExternalReferenceCode to Blogs Images (Part 1)

### PR DESCRIPTION
**Pull request by bakayattila**
task ticket:
https://liferay.atlassian.net/browse/LPD-31827
Story ticket:
https://liferay.atlassian.net/browse/LPD-27622

------

The pull might seem a bit empty but https://liferay.atlassian.net/browse/LPS-130893 already implemented the ERC in the service updated the add method and created a get for ERC. In this pull, I added the missing delete by ERC.  I did not create an update by ERC as there is no update method for BlogPostingImage at all.

- [x] add with ERC [addFileEntry](https://github.com/bakayattila/liferay-portal/blob/f908f8fa9e0b8c56a702ee770ebdc83d9a5ddf94/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppLocalServiceImpl.java#L139C4-L139C33)
- [x] get/fetch by ERC [fetchFileEntryByExternalReferenceCode](https://github.com/bakayattila/liferay-portal/blob/f908f8fa9e0b8c56a702ee770ebdc83d9a5ddf94/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppLocalServiceImpl.java#L592-L600), [getFileEntryByExternalReferenceCode](https://github.com/bakayattila/liferay-portal/blob/f908f8fa9e0b8c56a702ee770ebdc83d9a5ddf94/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppLocalServiceImpl.java#L667-L675  )
- [x] delete by ERC This pull

previous pull: https://github.com/liferay-content-management/liferay-portal/pull/5740

Resent the pull based on: https://github.com/brianchandotcom/liferay-portal/pull/153338#issuecomment-2297022443

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:report:67921977

**Comment by ambrinchaudhary** [comment]
Hey @bakayattila , these appears as unique failures to this pull, could you please check before forcing the forward? 

Unique Failures
**com.liferay.asset.publisher.exportimport.test.AssetPublisherExportImportTest**,https://testray.liferay.com/#/project/34754/routines/34756/build/67921977/case-result/67927722/history,Unique,testExportImportDisplayStyleFromDifferentGroupWithFeatureFlagEnabled: com.liferay.dynamic.data.mapping.exception.NoSuchTemplateException: No DDMTemplate exists with the key {groupId=51118. classNameId=20005. templateKey=51131}  at com.liferay.dynamic.data.mapping.service.persistence.impl.DDMTemplatePersistenceImpl.findByG_C_T(DDMTemplatePersistenceImpl.java:8753)  at com.liferay.dynamic.data.mapping.service.impl.DDMTemplateLocalServiceImpl.getTemplate(DDMTemplateLocalServiceImpl.java:627)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)  at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)  at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)  at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40)  at com.sun.proxy.$Proxy898.getTemplate(Unknown Source)  at com.liferay.asset.publisher.exportimport.test.AssetPublisherExportImportTest.testExportImportDisplayStyleFromDifferentGroupWithFeatureFlagEnabled(AssetPublisherExportImportTest.java:780)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)  at java.lang.Thread.run(Thread.java:750)
**com.liferay.journal.service.test.JournalArticleLocalServiceTest**,https://testray.liferay.com/#/project/34754/routines/34756/build/67921977/case-result/67934134/history,Unique,testUpdateArticleByNonownerUser: java.lang.AssertionError  at org.junit.Assert.fail(Assert.java:87)  at org.junit.Assert.assertTrue(Assert.java:42)  at org.junit.Assert.assertTrue(Assert.java:53)  at com.liferay.journal.service.test.JournalArticleLocalServiceTest.testUpdateArticleByNonownerUser(JournalArticleLocalServiceTest.java:1729)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)  at java.lang.Thread.run(Thread.java:750)

**Comment by bakayattila** [comment]
Hi @ambrinchaudhary,
The two failers are not related. The first one is a permission issue I don't see any possible way that it could be related to the updated getByERC method. The other method in the pull is not used in the code yet.
The second issue seems to be related to the ddmTemplateLocalService add method. I checked and did not find any reference to any changes in this part of the code either.

**Comment by ambrinchaudhary** [comment]
Thank you for checking it. Let's force it then.

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
