### PR TITLE
LPD-28315 and LPD-29163 - FF removal and poshi fixes

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Resent from https://github.com/liferay-content-management/liferay-portal/pull/5596

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
@ambrinchaudhary, I think testray is broken, there are no results....

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
Requested help in #ci channel: https://liferay.slack.com/archives/C19PWQ74J/p1719845823600849

**Comment by adolfopa** [comment]
ci:report:33674263

**Comment by adolfopa** [comment]
ci:report:34643459

**Comment by ambrinchaudhary** [comment]
Hey @adolfopa, I paused this pull on purpose. After this sprint, as test failures will be less than before, it will be easier to identify how many test breaks this pull, and fix them.

**Comment by adolfopa** [comment]
@ambrinchaudhary I know :-D Those random report requests are for the daily test reports; there's no way (afaik) to generate those directly in testray, so I need to use a random PR to get the report. I used this one because I thought it would create less noise. My apologies (but I'll continue using this PR anyway :smiling_imp: )

**Comment by ambrinchaudhary** [comment]
ci:report:43027276

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
ci:test:playwright

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
ci:test:data-engine

**Comment by jkappler** [comment]
@ambrinchaudhary, @gergelyszalay, will rebase the PR and resolve conflicts and then resend

**Pull request closed without merging**
