### PR TITLE
LPD-43121 Using ancestors when we are using fetchDDMTemplateByExternalReferenceCode

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-43121

Here in this PR there are commits from three PRs, 

1. LPD-42376 : this is already in brian, you can see it [here](https://github.com/brianchandotcom/liferay-portal/pull/156546).
2. LPD-43040 : this is in bpm repository pending to review it, see [here](https://liferay.atlassian.net/browse/LPD-43040)
3. LPD-43121 : finally, there is a commit related to the changes of this PR

# How am I fixing it?

Fetch template including ancestors since we can have the template in an AssetLibrary, in the site or in the global site

# How can you verify that it works?

There is already a test to cover this, added in the las pr:  https://github.com/liferay-content-management/liferay-portal/pull/6077/commits/8504492706478a916dbe3714d1aa4225f3792749

### CODE REVIEW

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
@Mikellorza could this be forwarded now or should we wait for other PRs to pass?

**Comment by Mikellorza** [comment]
@robertoDiaz we have to wait for the BPM team first. So, i put it on hold.

Thanks for the review

**Comment by Mikellorza** [comment]
The pending PR is already in brian queue, so, let's move this PR running our suites.

**Comment by Mikellorza** [comment]
ci:forward

**Comment by adolfopa** [comment]
@Mikellorza Test failures look legit.

**Comment by Mikellorza** [comment]
Yes, it seems that  is failing because of this [baseline  commit](https://github.com/brianchandotcom/liferay-portal/pull/156800/commits/ccb80634394af2cd9832684abfd3f4f9725daf8c) that I forget to pick from the bpm PR.

**Comment by Mikellorza** [comment]
ci:report:88571300

**Comment by Mikellorza** [comment]
Related PR is already merged, so, it's time to forward it

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
