### PR TITLE
LPD-30087 Remove FF for Resolution and orientation filters for content dashboard

### PR DESCRIPTION
**Pull request by jkappler**
Remove FF for Resolution and orientation filters for content dashboard

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-35527)

# How can you verify that it works?

* Go to Content Dashboard
* Click on Filter
* Resolution and Aspect Ratio will be shown

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:79319450

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
