### PR TITLE
LPD-35631 Create test for Select From List field

### PR DESCRIPTION
**Pull request by DiegoHu97**
LPD-35631 Create test for Select From List field

# What is this trying to solve?

- Create the test for the [improvement made for Select From List field](https://liferay.atlassian.net/browse/LPD-34654). This improvement allows us to restore the default "Choose an Option" option for this field when we use the undo/redo feature. The fix is already available in master.

[Link to ticket](https://liferay.atlassian.net/browse/LPD-35631)

# How am I fixing it?

- Create playwright test

# How can I test it?

- Execute the test

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Comment by DiegoHu97** [comment]
The test passed in CI:

**Review by NemethNorbert — COMMENTED** [review]
LGTM :)

Thanks @DiegoHu97 !

**Review by NemethNorbert — APPROVED** [review]

**Comment by DiegoHu97** [comment]
ci:forward

**Pull request closed without merging**
