### PR TITLE
LPD-40576 [playwright] Fix test 'Translation is removed when using Undo and restored when using Redo'

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-40576

Fix the test because is working manually

# How am I fixing it?

Using fillContent instead of fillTitle to test the undo/redo translation.

# How can you verify that it works?

1. Go to `/modules/test/playwright`
1. Run `npm install (setup)`
1. Run npm run `npm run playwright test -- -g "Translation is removed when using Undo and restored when using Redo"` to run the test

# Test launched 10 times test locally to avoid flaky results
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:content-management-playwright

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@boton Changes look ok, but failures may be related?

**Comment by boton** [comment]
@adolfopa the failures aren't related, they are failing in our daily routine too; Are you okay with forwarding it?

We need to invest some time in stabilizing and refactoring the Web Content playwright tests because we have issues with the title in playwright 😢

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
