### PR TITLE
LPD-17894, LPD-19243 Translations for Web Content

### PR DESCRIPTION
**Pull request by DiegoHu97**
\[LPD-19243\](https://liferay.atlassian.net/browse/LPD-19243)  
\[LPD-17894\](https://liferay.atlassian.net/browse/LPD-17894)

Previous PR: #5173

I resent this PR with LPD-19243 as it depends on LPD-17894.

Changes I applied to LPD-17894:  
b01a1fd : The TranslationManager was not able to track rich-text localisation due to a bug, this is the fix for it.

dc4ff02 : We should delete the translation instead of setting the value to the default locale's value, so data-engine knows it's not localised

872a347 : Once the above is done, we need the event to update the ddmFields

e841939 : rich-text requires additional care to update the editor's value, it's needed as the component tracks the value internally and we cannot force an update on the editor itself from outside the component

07b5822 : We did not handle the defaultLocaleChanged event, this is a fix for that -> I don't like the typescript handling of that event, we might need to create a type for it to handle it properly

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1327401_3973

**Comment by DiegoHu97** [comment]
ci:report:2550834148

**Comment by DiegoHu97** [comment]
The failures are not related

**Comment by DiegoHu97** [comment]
ci:forward:force

**Comment by DiegoHu97** [comment]
ci:forward:force

**Pull request closed without merging**
