### PR TITLE
LPD-24145 if is a shortcut, use the shortcut data instead of the file

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Steps to reproduce: 

1) On current site (Liferay) go to Content and Data > Documents and Media 
2) Create a file entry DM Document Title
3) Create a new site Site Name
4) On the new site, go to Content and Data > Documents and Media 
5) Create a shortcut to the DM Document Title that is on site Liferay (select from breadcrumb)
6) Once created, click on Move action and check the breadcrumb

**Expected result:** 
It opens where the shortcut is (Site and Libraries > Site Name)

Other Steps to reproduce:

1) Create new File
2) Create shortcut to this file Navigate to media.
3) Create a Folder
4) Move File to the folder
5) Move Shortcut to the folder

**Expected result:** 
you can move to the folder

- **LPD-24145 if is a shortcut, use the shortcut data instead of the file**
- **LPD-24145 remove the ignore on the poshi test**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Review by ambrinchaudhary — APPROVED** [review]
Thank you @AliciaGarciaGarcia for fixing this!! I've tested it manually and works perfect now ❤️ 

However, I run the poshi test and failed again (and if I test it manually with the site created by the test also fails 🤔 ). Not sure why... but lets wait to the `ci:test:content-management` results.

**Comment by AliciaGarciaGarcia** [comment]
> Thank you @AliciaGarciaGarcia for fixing this!! I've tested it manually and works perfect now ❤️
> 
> However, I run the poshi test and failed again (and if I test it manually with the site created by the test also fails 🤔 ). Not sure why... but lets wait to the `ci:test:content-management` results.

If the poshi test is not solved, then we can re-ignore the test again (remove the commit from this PR)

Y will put it on-hold to do not forward this 

thanks

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2563907790

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2563907790

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2563907790

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2563907790

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @ambrinchaudhary 
I saw that with the first fix the POSHI test was not fixed, I make a research and saw a strange thing on the POSHI creation of the shortcut.

This solves (I think) the CanMoveShortcutIntoFolder POSHI test but maybe break more test :( 

@austinchiang do you think that my last commit makes sense?

thanks!

**Comment by austinchiang** [comment]
LGTM, I checked the tests using JSONDocument.addShortcut and they are all passing 🎆

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2564374794

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
