### PR TITLE
LPD-21860 Error when adding friendly URL of category to rich text field in web content

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-21860

When validating URLs, the validation logic only takes into account some specific cases hardcoded in the staging classes. This makes it not possible to create content containing URLs pointing to arbitrary display pages.

# How am I fixing it?

Get the actual set of display page prefixes from the registry instead of using hardcoded values.

# How can you verify that it works?

Follow the steps described in https://liferay.atlassian.net/browse/LPD-21860.

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Review by jkappler — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:report:2557854163

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:report:2558189046

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
