### PR TITLE
LPD-35438 Change label when submitting for workflow

### PR DESCRIPTION
**Pull request by DiegoHu97**
LPD-35438 Change label when submitting for workflow

# What is this trying to solve?

- Change label "Submit for workflow" with "Submit for workflow with permissions" when we publish a web content for the first time as when we publish is "Publish with permissions" 

[Link to ticket](https://liferay.atlassian.net/browse/LPD-35438)

# How am I fixing it?

- Change the label and create the test

# How can I test it?

- Go to Configuration > Workflow > Web content article > SIngle approver
- Go to Content & Data > Web Content > Click on Submit for workflow
- See  "Submit for workflow with permissions" 
image

### CODE REVIEW

**Review by ambrinchaudhary — COMMENTED** [review]
Hey @DiegoHu97, 

the use case you described in the pull(basically workflow activated and **new** web content) was already showing the label `submit-for-workflow-with-permissions`. 

But you changed when the article previously exists. Is this correct? When a web content has already been saved (user saw the submit-for-workflow-with-permissions the first time), we are showing this message a second time (or more?). Also I don't see any description in the issue https://liferay.atlassian.net/browse/LPD-35438

**Comment by ambrinchaudhary** [comment]
Based on the description in  https://liferay.atlassian.net/browse/LPD-27364?focusedCommentId=2730636: 

> I’m moving this back to In development because when the workflow is activated, it should say “Submit for workflow with permissions” the first time it is sent to review. Next times it will just say “Submit for workflow”

It is because **autosave** is already saving and creating the article, but `showPublishModal` is still true? Then it makes sense your change. I would just made it clear in the description that we should wait for an Autosave.

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1407401_10829

**Comment by DiegoHu97** [comment]
ci:report:79319324

**Comment by DiegoHu97** [comment]
The failures are not related

**Comment by DiegoHu97** [comment]
ci:forward:force

**Pull request closed without merging**
