### PR TITLE
 [Release Blocker] LPD-44101 add icon on translation entry renderer getIconCssClass method

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-44101 add the method to show the translation icon on the workflow task

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-44101

The clay:icon from 'edit_workflow_task.jsp' is throwing a NPE id cssClass is null.

# How am I fixing it?

Adding the _getIconCssClass_ method to show the translation icon on the workflow task

# How can you verify that it works?

1. Enable workflow for Translations (for left product menu: Configuration > Workflow > Translations > Single Approver)
2. Create a Basic Web Content and Publish 
3. From the options menu, select Translate 
4. Once translated, click Submit for Workflow 
5. Go to user profile icon, and select My workflow task 
6. Access to the translation task 

Covered by : 
LocalFile.TranslationsWorkflow#CanApproveEntry
LocalFile.TranslationsWorkflow#CanResubmitRejectedEntries

# Commits

LPD-44101 clay:icon form edit_workflow_task is throwing a NPE id cssClass is null. So on TranslationEntryAssetRendererFactory add the method to show the translation icon on the workflow task

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translations

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translations

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
