### PR TITLE
LPD-30456 Update integration tests

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-30456

This is a followup to [5651](https://github.com/liferay-content-management/liferay-portal/pull/5651).

Update existing integration tests to double check that the last breadcrumb entry is not browsable.

Although there are existing POSHI tests that already cover this, adding this assertion will make it easier to fix any regressions.

# How can you verify that it works?

Run the tests in `DepotBreadcrumbEntryContributorTest`.

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by adolfopa** [comment]
Failure looks legit. Will push a fix.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
