### PR TITLE
LPD-35388 Asset publishers show assets after site/asset library is disconnected

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-35388 Asset publishers show assets after site/asset library is disconnected

resent with changes on tests name after : https://github.com/brianchandotcom/liferay-portal/pull/153944#issuecomment-2332910644

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-35388

When a object from an asset library is shown on an asset publisher we should check if the site/asset library is connected or not

# How am I fixing it?

On the DepotAssetRendererFactoryWrapper check if the asset entry is from a asset library, and if the group we are showing it is connected or not to it

# How can you verify that it works?

Run the included automated tests.

# Commits

- **LPD-35388 if asset Renderer Group is depot check if is connected to show it**
- **LPD-35388 check NPE**
- **LPD-35388 add test to check that the asset renderer of the entry of the asset library returns null when the site and depot are not connected**

//cc @jkappler

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:report:82514783

**Comment by AliciaGarciaGarcia** [comment]
ci:report:8252816

**Comment by AliciaGarciaGarcia** [comment]
@jkappler thanks for the review

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
