### PR TITLE
LPD-40156 We should check if the toggle switch is already checked or not in WikiPortlet.macro's enableWiki()

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-40156

Some staging tests are being affected by enable wiki macro like [this one](https://liferay.atlassian.net/browse/LPD-39489?atlOrigin=eyJpIjoiZTU4YzdmYjhiNjM0NGQwNDkxZGVjZGIxMjAyMGFlZWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ). So this PR is to tmprove enable wiki macro in order to take into account some use cases when:

1. We are calling to enable wiki twice
2. We need to be in the home page 

# How am I fixing it?

Check if there is a disabled wiki feature flag to enable it and go back to home page

# How can you verify that it works?

No test needed because this is to improve our tests. Execute ci:test:headless-functional to see if this change fix this [staging issue.](https://liferay.atlassian.net/browse/LPD-39489?atlOrigin=eyJpIjoiZTU4YzdmYjhiNjM0NGQwNDkxZGVjZGIxMjAyMGFlZWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:headless-functional

**Comment by Mikellorza** [comment]
ci:content:management

**Comment by Mikellorza** [comment]
ci:test:content:management

**Comment by Mikellorza** [comment]
ci:test:content-management

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:reevaluate:1307401_10334

**Comment by Mikellorza** [comment]
ci:reevaluate:1307401_10334

**Comment by Mikellorza** [comment]
ci:reevaluate:1337401_6904

**Comment by Mikellorza** [comment]
ci:report:51146416

**Comment by Mikellorza** [comment]
ci:report:51453938

**Comment by Mikellorza** [comment]
There is no related issues in ci:test:content-management  execution

**Comment by Mikellorza** [comment]
The fix is working fine and staging test now are passing!!

**Comment by Mikellorza** [comment]
ci:forward

**Pull request closed without merging**
