### PR TITLE
LPS-18763 Add sandbox att to allowed iframe sanitization

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- **LPD-18763 add sandbox to allowed attributes on blog sanitizer**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Review by robertoDiaz — APPROVED** [review]

**Review by robertoDiaz — COMMENTED** [review]
See https://github.com/liferay-content-management/liferay-portal/pull/5175#issuecomment-1966643118

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
