### PR TITLE
LPD-42720 Poshi migration > playwright | categories > properties

### PR DESCRIPTION
**Pull request by boton**
>[!NOTE]
> Follow up #6131 after analyzing test cases with @DiegoHu97 

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-42720

Migrate some functional categories properties tests 
 - Can not add duplicated category properties key

# How am I fixing it?

Adding one extra step to the current test

# How can you verify that it works?

1. Go to `/modules/test/playwright`
1. Run `npm install` (setup)
1. Run npm run `npm run playwright test -- ./tests/asset-categories-admin-web/categories.spec.ts` to run the test

# Test launched 10 times test locally to avoid flaky results
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:content-management-playwright

**Review by NemethNorbert — APPROVED** [review]
LGTM :)

**Review by DiegoHu97 — APPROVED** [review]
LGTM too :heart:

**Comment by DiegoHu97** [comment]
ci:forward

**Pull request closed without merging**
