### PR TITLE
LPD-35077 Allow importing documents into imported folders

### PR DESCRIPTION
**Pull request by devpedrotavares**
# Motivation

We are developing this user [story](https://liferay.atlassian.net/browse/LPD-29348) where the aim is to improve the export/import experience 
of object entries with attachment fields.

One of the acceptance criterias (AC5) of the story is:

> Given a successful import of an object entry with a previously missing attached file,
> 
> When the missing attached file is subsequently imported,
> 
> Then the system must establish the correct relationship between the object entry and the imported attached file.

In the cases where documents are in folders. We could not find a way to export and import the folders and documents as they were before, using the rest endpoints. Because the document only referenced the id of the its folder.

# Solution

In order to properly meet and test the criteria mentioned above, we added the folder ERC to the document DTO. And also added logic that takes the ERC into account when adding or updating a document, ensuring that it is created or moved to the corresponding folder if it exists.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:content-management

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@devpedrotavares At least the semver errors are caused by this PR. Can you review the test failures? Thanks!

**Comment by devpedrotavares** [comment]
ci:report:77897877

**Comment by devpedrotavares** [comment]
ci:report:77903865

**Comment by devpedrotavares** [comment]
Hi @adolfopa , I added a commit with the baseline changes. Apart from that, the failures seem unrelated to me.

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:report:78788623

**Comment by adolfopa** [comment]
Unique failures are not related to these changes.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
