### PR TITLE
LPD-31610 NullPointer accesing to "reserved-article-small-image-url" journal variable

### PR DESCRIPTION
**Pull request by jkappler**
NullPointer accesing to "reserved-article-small-image-url" journal variable

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-31610)

Freemarker errors are thrown when small image is not set

# How am I fixing it?

When the small image is not set, change it to a blank string

# How can you verify that it works?

Follow the steps in the ticket or run the integration test

error

### CODE REVIEW

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:38389294

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
failures are not related. Will check failing tests

**Pull request closed without merging**
