### PR TITLE
LPD-26357 Create endpoints for adding Document Shortcut to Site and Asset Library

### PR DESCRIPTION
**Pull request by jonathanmccann**
Create endpoints for adding Document Shortcut to Site and Asset Library

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-26357

These changes add new APIs to headless for adding document shortcuts to sites and asset libraries.

# How am I fixing it?

Add two new APIs as well as add validation logic to ensure the shortcut is added to an appropriate folder.

# How can you verify that it works?

Run the included automated tests.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@jkappler Changes were requested from Brian - https://github.com/brianchandotcom/liferay-portal/pull/151033#issuecomment-2150695770

The only difference from the previous pull is the final commit changing DLAppService to DLFileEntryLocalService.

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:report:12385165

**Comment by marcogalluzzi** [comment]
ci:report:12385165

**Comment by marcogalluzzi** [comment]
Hi @jonathanmccann there is only one unique failure and it seems related to your changes. The integration test `DLFileShortcutLocalServiceTreeTest` and its tests:

* `testFileShortcutTreePathWhenMovingSubfolderWithFileShortcut`
* `testRebuildTree`

Please have a look: https://testray.liferay.com/#/project/34754/routines/34756/build/12385165/case-result/12413277

**Comment by jkappler** [comment]
@jonathanmccann, seems the validateFolder method is the one throwing the exception 😱

**Comment by jonathanmccann** [comment]
@marcogalluzzi @jkappler Thanks for taking a look. That test was adding shortcuts to the default group but the folder was added to the group created in the `setUp` method. Please see https://github.com/liferay-content-management/liferay-portal/pull/5525/commits/86b79f34208ad30b0d64dec8c10c4089027cdd68 for the new changes.

**Comment by jonathanmccann** [comment]
ci:test:sf

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
@jonathanmccann, looks good! Feel free to forward it!

**Comment by marcogalluzzi** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
ci:test:stop

**Comment by marcogalluzzi** [comment]
ci:help

**Comment by marcogalluzzi** [comment]
ci:stop:stable

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:report:13608431

**Comment by marcogalluzzi** [comment]
The unique failure is not related. Forcing forwarfing.

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
