### PR TITLE
LPD-20911 "Null" values when creating articles with repeatable sections

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPD-20911

Steps to reproduce: follow the steps in the ticket

### CODE REVIEW

**Comment by jkappler** [comment]
Thank you so much @carolmariaabb, it works as a charm 😍 

cc:// @manuelRives

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2552487475

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2552631638

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
