### PR TITLE
[Playwright] LPD-24934 Functional test for LPD-16313

### PR DESCRIPTION
**Pull request by boton**
# Forwarded from #5440

> Hi,
> 
> May I ask to review my PR?
> 
> 
> The link for [figma](https://www.figma.com/file/YMcgShbEYvN2XMPPpc154t/LPD-16311-Define-and-manage-Site-default-D%26M-permissions?type=design&node-id=47-7787&mode=design)
> 
> Thank you!

I made a few adjustments to reduce the flaky tests

1.  Remove timeouts 92f36e39d65747badaac8997a1382cd8901ee817
2. Use clickAndExpectToBeVisible 158403a75f107ad145255c249d96f775fb23aa0d

---

image

### CODE REVIEW

**Comment by boton** [comment]
Please @gergelyszalay review that I don't make anything wrong

**Comment by boton** [comment]
ci:test:playwright

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:playwright:nocompile

**Review by gergelyszalay — APPROVED** [review]
tested and all the test passed

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
