### PR TITLE
LPD-20493 Add integration tests for existing functionality

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPD-20493

Subtask of https://liferay.atlassian.net/browse/LPD-6719

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
