### PR TITLE
LPD-27245 Enable AI creator test 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPD-27245

This test was disabled because of the captcha in the Gogo Shell. Now there is a way to disable that captcha for testing purposes.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:playwright

**Comment by ambrinchaudhary** [comment]
Opened a discussion in [slack](https://liferay.slack.com/archives/C01FP01V5L0/p1718015671541359) to understand why captcha is not disabled in the GogoShell

**Comment by ambrinchaudhary** [comment]
ci:test:playwright

**Comment by ambrinchaudhary** [comment]
Test passed successfully in CI 🎉 
Screenshot 2024-06-14 at 14 05 39

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
