### PR TITLE
LPD-26464 Cannot use keyword filtering in API

### PR DESCRIPTION
**Pull request by jkappler**
Cannot use keyword filtering in API

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-26464)

Filtering by contains for DDMFields fails because it's not targeting the correct field. Now for Strings, we should target field + .keyword_lowercase

# How am I fixing it?

Identify if we are targeting a ddmField of type "string" and target the correct field

# How can you verify that it works?

* Follow the steps in the LPD
* Or run the provided integration tests

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:search

**Comment by AliciaGarciaGarcia** [comment]
sorry for the delay
to test this on master we should apply https://github.com/liferay-content-management/liferay-portal/pull/5469

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
mmmm

can you check if this error is relevant? (on local)
```

com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest > testGetSiteStructuredContentsPage FAILED
    java.lang.AssertionError: [] expected:<1> but was:<0>
    	at org.junit.Assert.fail(Assert.java:89)
    	at org.junit.Assert.failNotEquals(Assert.java:835)
```

**Comment by jkappler** [comment]
ci:relevant:2571215688

**Comment by jkappler** [comment]
ci:report:2571215688

**Comment by jkappler** [comment]
@AliciaGarciaGarcia, I will take a look. Thanks

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
