### PR TITLE
LPD-29874 Add blacklist configuration to IframeSanitizer

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-29874 Add blacklist configuration to IframeSanitizer

~To forward this:  https://github.com/liferay-content-management/liferay-portal/pull/5627 and https://github.com/liferay-content-management/liferay-portal/pull/5640 are needed to pass~ 

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28774 (story)

I want to have a blacklist configuration in the Iframe Sanitizer

# How am I fixing it?

I'm adding to the Iframe Configurator: 

```
@Meta.AD(name = "blacklist", required = false)
public String[] blacklist();
```

# How can you verify that it works?

Run the included automated tests.

image

# Commits

- **LPD-29874 add blacklist attribute to the IFrameConfiguration**
- **LPD-29874 add blacklist to the configuration helper  and take it into account when we decide if we should sanitize or not**
- **LPD-29874 add test to check the behavior of classname blacklisted and the interaction with the whitelist**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Why is this on hold? :thinking:

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
c:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:report:30421009

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:report:30421009

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
