### PR TITLE
LPD-40738 Fix test WebServerServletTest

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-40738

The test `WebServerServletTest` is failing with the exception `DuplicateFolderNameException`.

# How am I fixing it?

A test repository is created twice, so giving it a random name solves the problem.

# How can you verify that it works?

`cd modules/apps/portal/portal-webserver-test`
`gw tI --tests WebServerServletTest`

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
