### PR TITLE
LPD-34910 Remove FF

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-34910 Remove FF

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-34910

We want to fully release the https://liferay.atlassian.net/browse/LPD-10701 : Display date for D&M to all the customers without activate any Feature Flag

# How am I fixing it?

Removing the FF LPD-10701

# How can you verify that it works?

Run the included automated tests.

cc// @robertoDiaz 

# Commits
- **LPD-34910 remove LPD-10701 from properties**
- **LPD-34910 remove calls for the FF**
- **LPD-34910 BuildLang**
- **LPD-34910 remove @FeatureFlags("LPD-10701") from test**
- **LPD-34910 change panel name on poshi**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:report:76023706

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:report:78032070

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:report:78874058

**Comment by AliciaGarciaGarcia** [comment]
ci:report:78874058

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1307401_10021

**Comment by AliciaGarciaGarcia** [comment]
This seems relevant

[LocalFile.DMFileEntry#CanCheckInAsMajorVersion](https://testray.liferay.com/#/project/34754/routines/34756/build/78874058/case-result/78929502/history)
[LocalFile.DMFileEntry#BulkCopyDoesNotFactorInDocumentStatus](https://testray.liferay.com/#/project/34754/routines/34756/build/78874058/case-result/78937434/history)
[LocalFile.TranslationsWCExportImport#CanImportWebContentWithXliffFile](https://testray.liferay.com/#/project/34754/routines/34756/build/78874058/case-result/78929338/history)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:report:79221989

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
https://github.com/liferay-content-management/liferay-portal/pull/5809#issuecomment-2327263122 test failures seems not related with this PR

**Comment by AliciaGarciaGarcia** [comment]
ci:report:79319527

**Comment by AliciaGarciaGarcia** [comment]
ci:report:79319527

**Comment by AliciaGarciaGarcia** [comment]
ci:report:79319527

**Comment by AliciaGarciaGarcia** [comment]
ci:report:79221989

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
my bad

**Review by robertoDiaz — APPROVED** [review]
Good to go.

Really nice @AliciaGarciaGarcia

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1327401_4913

**Comment by AliciaGarciaGarcia** [comment]
@robertoDiaz 

On theory this PR does **not** make any test failing because the FF removal. 

Please, take care of this on my absence

**Comment by AliciaGarciaGarcia** [comment]
ci:report:78032070

**Comment by AliciaGarciaGarcia** [comment]
ci:report:78032070

**Comment by AliciaGarciaGarcia** [comment]
[LocalFile.DMLocalStaging#PendingEntryWillNotBePublishedToLive](https://testray.liferay.com/#/project/34754/routines/34756/build/78032070/case-result/78056221)
[LocalFile.DMWorkflow#CopiedDocumentRespectsGrandparentFolderWorkflow](https://testray.liferay.com/#/project/34754/routines/34756/build/78032070/case-result/78056406)
[LocalFile.DMWorkflow#CanApproveCopiedDocument](https://testray.liferay.com/#/project/34754/routines/34756/build/78032070/case-result/78081526)
[LocalFile.DMWorkflow#CanRemoveWorkflowFromFolder](https://testray.liferay.com/#/project/34754/routines/34756/build/78032070/case-result/78078096)
[LocalFile.DepotWorkflow#CanApproveImage](https://testray.liferay.com/#/project/34754/routines/34756/build/78032070/case-result/78078854)
[LocalFile.DMFileEntry#CanViewExpiredDocument](https://testray.liferay.com/#/project/34754/routines/34756/build/78032070/case-result/78063023)
[LocalFile.DMFileEntry#CannotViewExpiredDocumentAsGuest](https://testray.liferay.com/#/project/34754/routines/34756/build/78032070/case-result/78076804)
[LocalFile.DMFileEntry#CanViewExpiredDocumentAsContentReviewer](https://testray.liferay.com/#/project/34754/routines/34756/build/78032070/case-result/78069078)


Are relevant to this PR

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:report:6398820

**Comment by adolfopa** [comment]
Failures seem related :-(

**Comment by robertoDiaz** [comment]
I'll check it tomorrow

**Comment by robertoDiaz** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
There are conflicts... marking this as draft for now...

**Comment by robertoDiaz** [comment]
Closed in favour of https://github.com/brianchandotcom/liferay-portal/pull/154393

**Pull request closed without merging**
