### PR TITLE
LPD-39650 Cannot change structure key when disabling configuration

### PR DESCRIPTION
**Pull request by jkappler**
Cannot edit structure key when disabling configuration

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-39650)

When disabling autogenerate structure key configuration in system settings, the user cannot change the structure key when creating a DDM Structure

# How am I fixing it?

Removing the system configuration since it was moved to instance configuration

# How can you verify that it works?

Run the integration tests

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_18311

**Comment by jkappler** [comment]
@adolfopa, failures seem related, I will take a look

**Comment by jkappler** [comment]
ci:report:46276669

**Comment by jkappler** [comment]
ci:report:46276669

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:report:47590563

**Comment by jkappler** [comment]
ci:report:47590563

**Comment by jkappler** [comment]
@Mikellorza, we are good to go!

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
