### PR TITLE
LPD-20538 set expiration date values and validation for properly expire documents

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-17556 is needed (waiting for master, thats why it's on hold)

How to check it

1) modify documents and media service putting the check interval to 1
2) create a document and put the expiration date on 3 min on the future
3) let it expire
4) edit and put it 3 mins on the future
5) assert that the file is approved and only when 3 mins passes it expires

- **LPD-20538 expire only between the date and the date minus the check interval**
- **LPD-20538 set expiration date to the fileEntry to allow searching on the check interval**
- **LPD-20538 add validation for expiration date and the relation of expiration - display date**
- **LPD-20538 add test to check the validation**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2551860933

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1307401_8961

**Comment by AliciaGarciaGarcia** [comment]
the failures related with this PR. 

reviewing . . .

**Comment by jkappler** [comment]
@AliciaGarciaGarcia. lots of unique failures 😢

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:documents

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:report:2552706179

**Comment by jkappler** [comment]
@AliciaGarciaGarcia, less unique failures :D

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1317401_10606

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1267401_12944

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1277401_11462

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1277401_11462

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2552974658

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2553083156

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2554479797

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:foce

**Pull request closed without merging**
