### PR TITLE
LPD-114700 | LPD-11253 Remove Feature Flags for the epics

### PR DESCRIPTION
**Pull request by jkappler**
Remove Feature Flags for the epics

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-35922)
[Link to ticket](https://issues.liferay.com/browse/LPD-35921)

This pull request removes the feature flags for LPD-114700 and LPD-11253

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by jkappler** [comment]
ci:report:8281238

**Comment by jkappler** [comment]
ci:report:8393486

**Comment by jkappler** [comment]
Test failures that are or seem related:

:apps:dynamic-data-mapping:dynamic-data-mapping-form-field-type:packageRunTest,https://testray.liferay.com/#/project/35392/routines/45357/build/8393486/case-result/8402683/history,Unique,Failed tests: ReactFieldBase shows the popover for Format field when hovering over the tooltip icon. ReactFieldBase renders the FieldBase with tooltip

:apps:frontend-js:frontend-js-components-web:packageRunTest,https://testray.liferay.com/#/project/35392/routines/45357/build/8393486/case-result/8402746/history,Unique,Failed tests: TranslationAdminSelector calls onSelectedLocaleChange callback on dropdown locale selection. TranslationAdminSelector renders an open dropdown with the list of active languages. TranslationAdminSelector renders a dropdown trigger with the selected locale flag icon as content. TranslationAdminSelector is used as a controlled component. TranslationAdminSelector renders an open dropdown with updated active locales when added from the Manage Translations Modal. TranslationAdminSelector selects the default locale if the current selected one is removed from the active locales list. TranslationAdminSelector renders an open dropdown with the list of active languages and manage translation option

:apps:journal:journal-web:packageRunTest,https://testray.liferay.com/#/project/35392/routines/45357/build/8393486/case-result/8402810/history,Unique,Failed tests: SaveButtons Show an alert appears when the title is empty. TranslationManager renders component. TranslationManager attaches inputLocalized:updateTranslationStatus event when the button is clicked

journal-web/journalArticle.spec.ts,https://testray.liferay.com/#/project/35392/routines/45357/build/8393486/case-result/8416767/history,Unique,Failed tests: LPD-29527 - Can delete translation of a web content created from a structure with at least one required and non-localizable field. This is a test for reset translations button in web content. LPD-30412: This is a test for deleting multiple translations from a web content. Translate several fields in a Basic Web Content and check how many fields have been translated. Check alert message of duplicated friendly URL in french. Translate all fields of a Web Content based on a custom structure with repeatable fields

journal-web/journalArticleAutosave.spec.ts,https://testray.liferay.com/#/project/35392/routines/45357/build/8393486/case-result/8416791/history,Unique,Failed tests: Autosave is not enabled until all required fields are completed. Translation is removed when using Undo and restored when using Redo. Create a web content selecting permissions in the modal. History button test

**Comment by NemethNorbert** [comment]
The Failing tests from test/js/translation_manager/TranslationManager.test.tsx looks like needs to be updated.
`'renders component' `fails due to a poor locator that requires an update
`'attaches inputLocalized:updateTranslationStatus event when the button is clicked' `fails due to the selector does not have a button role but rather a 'combobox'


The failing test from test/js/SaveButtons.test.js `'Show an alert appears when the title is empty'` looks like is failing due to Liferay.Form is undefined when the test is running. This one is strange, but when manually trying the tescase it is passing at least.


Playwright tests from JournalArticle.spec.ts also passing manually and they are require an update for the locators.


:apps:frontend-js:frontend-js-components-web tests requires a snapshot update (run the tests with --u)
And the test require an update as well for mostly the same locators, like the translationManager dropdown

Again, manually seems to work everything fine

**Review by NemethNorbert — CHANGES_REQUESTED** [review]

**Comment by jkappler** [comment]
@NemethNorbert

**Comment by NemethNorbert** [comment]
ci:test:content-management

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
Hey @jkappler ,

I updated the tests and some of the files. Once concern I still have is about [bb7539e](https://github.com/liferay-content-management/liferay-portal/pull/5852/commits/bb7539e0a5bcd722b3e8f97709dd7d7c4046002c)
As it is never visible, but I did not find where we include it in the sidebar

There are still a lot of tests failing in JournalArticle.spec.ts However they seem flaky to me locally, so I pushed up the current changes and I'd like to see what the ci reports now.

**Comment by jkappler** [comment]
ci:report:11649300

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
Hey @jkappler,

The TranslationOptions and the TranslationAdminSelector was not adapted for the UndoRedo feature and it caused translation related tests to fail. I pushed up a commit that resolves it.

There are still other tests that failing and are not related to this issue, so I keep looking into them

**Comment by jkappler** [comment]
Thanks @NemethNorbert!

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:report:15927419

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:report:22458321

**Comment by jkappler** [comment]
ci:report:22458321

**Comment by jkappler** [comment]
@DiegoHu97, @NemethNorbert, only 2 tests failing! Almost there!

LPD-29527 - Can delete translation of a web content created from a structure with at least one required and non-localizable field. 
LPD-30412: This is a test for deleting multiple translations from a web content. Check alert message of duplicated friendly URL in french

**Comment by DiegoHu97** [comment]
@jkappler taking a look to the tests  
CC: @NemethNorbert

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:report:27022319

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by DiegoHu97** [comment]
ci:report:27421909

**Comment by DiegoHu97** [comment]
ci:report:27879580

**Comment by DiegoHu97** [comment]
ci:report:27879580

**Comment by jkappler** [comment]
ci:report:27959518

**Comment by jkappler** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:28386682

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:test:content-management-playwright

**Comment by jkappler** [comment]
ci:test:stable

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:stable

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
https://github.com/liferay-content-management/liferay-portal/pull/5934

**Pull request closed without merging**
