### PR TITLE
LPD-28728 The Web Content Structure predefinedValues are not being updated correctly

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28728

When a repeatable field with a default value is being replicated in a Web Content, the new replicated fields don't have the default value.

# How am I fixing it?

The `predefinedValues` of Web Content Structures are currently stored in a hidden article. Now I'm also storing them in the Structure (which is the standard way used in D&M).

# How can you verify that it works?

Manually: follow the steps in Jira issue
Automatically: execute added unit and playwright tests

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
Hi @jkappler I've added the pending tests. Please have a look. Thanks.

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
@marcogalluzzi, bakend changes look good ❤️. I will launch content management test suit again, just in case and then we can analyze those results

**Comment by marcogalluzzi** [comment]
ci:test:stop

**Comment by marcogalluzzi** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:report:26541919

**Comment by jkappler** [comment]
@marcogalluzzi, only two tests look suspicious

EditStructureDefaultValuesBasedOnFieldset
PredefineExpirationDateInCustomStructure

but at the same time, they don't seem to be related 🤔

**Comment by jkappler** [comment]
@marcogalluzzi, if the tests are not related, please feel free to forward it (don't wait for me :D)

**Comment by marcogalluzzi** [comment]
Hi @jkappler thanks for your review. The tests discussed don't seem to be "unique" because they occurred before. I will forward the PR.

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
