### PR TITLE
LPD-19625 Change icon from lock to password-policies

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: https://liferay.atlassian.net/browse/LPD-19625

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:sf

**Review by jkappler — APPROVED** [review]

**Review by jkappler — CHANGES_REQUESTED** [review]
@Mikellorza, SF failing for the PR is super weird, can you please take a look? 

Thanks!

**Comment by jkappler** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
@jkappler this error make not sense :(

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
@jkappler  I have created another PR to see if we do not face to the same issue because it makes not sense. see https://github.com/liferay-content-management/liferay-portal/pull/5237

**Comment by Mikellorza** [comment]
ci:close

**Pull request closed without merging**
