### PR TITLE
LPD-22775 When attributes has the same name that the some words we need to rename it to add the proper data

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPD-22775

Steps to reproduce:

1) Create an structure Structure_one with a 5 text field
2) In this field advanced tap, change the field reference to "attributes" and save.
3) In second field advanced tap, change the field reference to "data" and save.
4) In 3rd field advanced tap, change the field reference to "options" and save.
5) In 4th field advanced tap, change the field reference to "optionsMap" and save.
6) In 5th field advanced tap, change the field reference to "type" and save.
7) Create another structure Structure_two
8) Add a fieldset Structure_one and save it
9) Create a web content with the Structure_two and add values to all the fields
10) Display this web content on a page, for instance, through a web content viewer.

- **LPD-22775 Rename the "data" attribute because if we have a child node with "data" as name the (String)get("data") will not return the proper data. We need to add an internal method to get the data looking if the name property had changed or not**
- **LPD-22775 Rename the "attributes" attribute because if we have a child node with "attributes" as name the getAttributes will not return the proper data.**
- **LPD-22775 Rename the "options" attribute because if we have a child node with "options" as name the getOptions will not return the proper data.**
- **LPD-22775 Rename the "optionsMap" attribute because if we have a child node with "optionsMap" as name the getOptionsMap will not return the proper data.**
- **LPD-22775 Rename the "type" attribute because if we have a child node with "type" as name the getType will not return the proper data.**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2560083233

**Comment by AliciaGarciaGarcia** [comment]
I will look at LocalFile.WebContentUpgradeWithWithSecondComplexStructure#CanAddAndRemoveTranslationToWebContentStructure because maybe is relevant to this changes.

**Comment by AliciaGarciaGarcia** [comment]
failing previously this pr
https://testray.liferay.com/home/-/testray/case_results/2557565760/history?tab=result&hideFilterPin=true

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2560384121

**Comment by AliciaGarciaGarcia** [comment]
image

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
