### PR TITLE
LPD-31751 Update metadata-extractor library

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-31751

Update the metadata-extractor to 2.19.0. This new version includes some relevant bug fixes.

# Why doesn't this include any test?

The existing tests cover this update.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:report:40788659

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:report:40788659

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
