### PR TITLE
LPD-37394 Fix test related with permissions in autosave test

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[Link to issue ](https://liferay.atlassian.net/browse/LPD-37394)

# Motivation
This test 'Create a web content selecting permissions in the modal' is failing in testray

# How to test it
run `npm run playwright -- test -g 'LPD-32949' --reporter list`

Screenshot 2024-09-30 at 13 23 17

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Review by boton — CHANGES_REQUESTED** [review]
LGTM but still failing in CI [[master] ci:test:content-management-playwright - ambrinchaudhary > liferay-content-management - PR#5916 - 2024-09-30[09:37:43]](https://testray.liferay.com/#/project/35392/routines/45357/build/27247791)

image

**Comment by ambrinchaudhary** [comment]
I'll review this again carefully, because in local I receive a different "failure"... thanks @boton

**Comment by ambrinchaudhary** [comment]
Closing for now and moving back the task to in development...

**Pull request closed without merging**
