### PR TITLE
Lpd 22505 master

### PR DESCRIPTION
**Pull request by SamZiemer**
https://liferay.atlassian.net/browse/LPD-22505

When a journal article is used in a web content display, and the DDMTemplate is specifically linked orphaned data is left behind upon deletion which prevents the template from being removed.

This PR may need to be submitted to the team who handles DDM as well since I have added an upgrade process there to remove orphaned data.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevent

**Comment by SamZiemer** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@SamZiemer Looks good to me. Can you send this to the @liferay-forms user?

**Comment by SamZiemer** [comment]
Thanks @adolfopa, I'll send that now.

**Comment by SamZiemer** [comment]
sent here https://github.com/liferay-forms/liferay-portal/pull/2509

**Pull request closed without merging**
