### PR TITLE
LPD-33570 web content publish bug

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[Link to ticket. ](https://liferay.atlassian.net/browse/LPD-33570)

# What is the problem
When Feature Flag `LPS-114700` is enabled (can be done in Instance Settings), the Publish button for Web Content does not work, and user is not redirected to the main view. 

# How did I resolve it
For some reason, the taglib `<liferay-data-engine:data-layout-renderer>` was not being rendered properly inside a `<clay:panel>`. The submit event was not attached to the form (https://github.com/ambrinchaudhary/liferay-portal/blame/master/modules/apps/data-engine/data-engine-js-components-web/src/main/resources/META-INF/resources/js/custom/form/FormView.es.js#L216C58-L216C58), and thus the `Liferay.fire('ddmFormSubmit')`, was never fired. 

I decided to change it for a `<liferay-frontend:fieldset>` and adjust the styles, as debugging inside Data Engine elements was going to require much more time. Look and feel is the same. Metadata section is a `<clay:panel>` but Fields is a `<liferay-frontend:fieldset>`
Screenshot 2024-08-19 at 17 04 35

# How to test it
Follow the steps described in the issue, or run the test: 
`npm run playwright -- test -g 'Web Content is published' --reporter list`

```
Running 1 test using 1 worker

  ✓  1 [journal-web] › journal-web/journalArticle.spec.ts:1751:1 › Web Content is published when Feature Flags LPS-114700, LPD-11228 and LPD-15596 are active (32.8s)
```

### CODE REVIEW

**Review by DiegoHu97 — APPROVED** [review]
It works fine, thank you!

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:test:playwright

**Comment by ambrinchaudhary** [comment]
ci:test:playwright

**Comment by ambrinchaudhary** [comment]
Test passes with the last change. The rest of failures are not related to this pull. I'm going to forward it. 
Screenshot 2024-08-21 at 12 40 01

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
