### PR TITLE
LPD-42445 Technical Task | Release FF - Remove (Increased flexibility for managing friendly URLs of asset types)

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-42445 Increased flexibility for managing friendly URLs of asset types - Remove Release FF

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-42445

We want to increased flexibility for managing friendly URLs of asset types. Customers are demanding the capability to manage the blog entries' URLs, Web Content, Documents & media, Object entries, or categories. So we worked on https://liferay.atlassian.net/browse/LPD-11147 and now we want this feature accesible to all.

# How am I fixing it?

Removing the Feature Flag 'LPD-11147'

# How can you verify that it works?

Run the included automated tests.

# Commits

- **LPD-42445 remove FF LPS-11147**
- **LPD-42445 remove FF from code**
- **LPD-42445 no longer needed**
- **LPD-42445 only if friendlyURLAssetCategoryIds is present we need to create un asset entry. friendlyURLAssetCategoryIds can be empty so if we want to delete the categories the attribute will be present but empty. If a Blog is patched via API and this attribute is not present, on other case the categories will be deleted**
- **LPD-42445 now the creation of a FriendlyURLEntry implies the creation of an asset entry**
- **LPD-42445 as on the updateAssetEntry, the serviceContext can be null**
- **LPD-42445 remove FF from integration test**
- **LPD-42445 remove FF from playwright tests**
- **LPD-42445 restore the original values of the configuration to avoid side effects**
- **LPD-42445 fix FriendlyURLSeparatorCompanyConfigurationDisplayContextTest**
- **LPD-42445 now the new friendly url will have a fieldset always disabled so we must create a new method that do not check this**
- **LPD-42445 element is now on Friendly URL panel**
- **LPD-42445 Automatic now is default for Friendly URLS**
- **LPD-42445 buildLang**

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by robertoDiaz** [comment]
ci:test:help

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
rebased with master

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1297401_10816

**Comment by robertoDiaz** [comment]
Hi @AliciaGarciaGarcia 

If any of the known failures involves other teams, please inform us in order to warn them before merging this in master.

cc/ @adolfopa

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:report:94865637

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
com.liferay.change.tracking.internal.test.LayoutCTTest is a know issue that should be addressed

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:report:95733346

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:96740523

**Comment by AliciaGarciaGarcia** [comment]
ci:report:96740523

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
