### PR TITLE
LPD-29163 Fix WebContent poshi tests failures related with the Publish button

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Revert of https://github.com/liferay-content-management/liferay-portal/pull/5607 
This pull also includes all the poshi fixes needed for this FF removal.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:report:22383129

**Comment by Mikellorza** [comment]
Hey team,

As I have spoken with Jorge, we are going to open a thread in order to synchronize ourselves. I also left a comment here in order to inform what methods we have to take into account:

1. We have to implement a new macro for the cases that are called to save as draft button, something like saveAsDraftWithPermissions.
2. We have to take into account these methods that we are using it to create a content and publish or save it as draft:
     - 1 WebContent.addArticleCP -> Change inside there from publish to publishWithPermissions, for sure it will fix a lot of failures. Or change from Button.clickPublish(); to publishWithPermissions. Or change from PortletEntry.saveAsDraft(); to saveAsDraftWithPermissions. Or change from PortletEntry.submitForWorkflow(); to submitForWorkflowWithPermissions. Or change from PortletEntry.save(); to saveAsDraftWithPermissions. And for those cases, see if the publish/saveAsDraft/etc is directly related with add content or maybe it is related with another action that we are doing after.
     - 2 WebContent.addCP --> Changes where is it used from publish to publishWithPermissions
     - 3 WebContent.addDraft --> Here we have to add new macro called saveAsDraftWithPermissions where we have to do exactly the same as publishWithPermission but changing the titles of the button from Publish With permissions to Save as draft or something like this.
     - 4 WebContent.addDraftPGViaAP --> Same that above.
     - 5 WebContent.addExistingRelatedAssetCP --> Change inside there from publish to publishWithPermissions.
     - 6 WebContent.addFailWithoutRequiredCategoryAssetTypeCP  --> Change inside there from publish to publishWithPermissions.
     - 7-WebContent.addNullCP --> Change inside there from publish to publishWithPermissions.
     - 8 And the other method are using WebContent.addCP and this is the same case of point 1. 
     - 9 WebContent --> the uses of PortletEntry.saveAsDraft() or Button.clickSaveAsDraft(); we have to change from it to saveAsDraftWithPermissions() and clickSaveAsDraftWithPermissions(); ( but maybe we can replace these cases to use saveAsDraftWithPermissions() we have to check it).
     
So, definitively,  we have to create two more macros:

1. saveAsDraftWithPermissions
2. submitForWorkflowWithPermissions

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Pull request closed without merging**
