### PR TITLE
LPD-31655 Action menu unresponsive when viewing journal article's history in card view

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-31655

# How am I fixing it?

The change adds in necessary parameters in order for the clicks to function properly. This is copied from the changes made in LPS-187505 (https://github.com/liferay-frontend/liferay-portal/pull/3463)

# How can you verify that it works?

Run `npm run playwright -- test -g 'LPD-31655'`

To test manually:

1. Create a Basic Web Content Article and Publish
2. Choose [View History] from the Action Menu
3. Change the Display mode to [Card View]
4. Click on the items in the Action menu

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
Not sure why the new test is failing, I will take a look at it today.

**Comment by jonathanmccann** [comment]
I've updated the test to include some additional `waitFor` calls to ensure the buttons and menus being interacted with are available. Previously, the test was failing about 3 times out of 20. Now it passes 20/20 consistently.

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:report:40058482

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
