### PR TITLE
LPD-29528 Convert EmailIsReceivedWhenUpdateReachesScheduledTime to integration test

### PR DESCRIPTION
**Pull request by jkappler**
Convert EmailIsReceivedWhenUpdateReachesScheduledTime to integration test

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-29528)

For the quality initiative, we are trying to convert existing poshi tests to unit/integration tests. In this case, we converted EmailIsReceivedWhenUpdateReachesScheduledTime

# How can you verify that it works?

Run the provided integration test

### CODE REVIEW

**Comment by jkappler** [comment]
@jonathanmccann, @marcogalluzzi

**Review by marcogalluzzi — APPROVED** [review]
Hi @jkappler the test is good to go :rocket: 

If you have time I would only change the other usages of `BlogsEntryLocalServiceUtil` to the new `_blogsEntryLocalService` you have introduced.

**Comment by jkappler** [comment]
Hi @marcogalluzzi, thanks! I will also change it along Jonathan's suggestion

**Comment by jkappler** [comment]
@jonathanmccann, @marcogalluzzi, changes applied, thanks a lot!

**Comment by marcogalluzzi** [comment]
Hi @jonathanmccann our proposals have been taken into accout. I'm forwarding.

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
