### PR TITLE
LPD-19337 Create TranslationFilter Component

### PR DESCRIPTION
**Pull request by DiegoHu97**
Epic: [LPD-11253](https://liferay.atlassian.net/browse/LPD-11253)
Story: [LPD-6603](https://liferay.atlassian.net/browse/LPD-6603)

Missing requirement:
- If Translated or Untranslated option are selected and there is module: Metadata or Fields, that has no fields meeting the criteria, the whole module should not appear.
In order to implement this, We have to update the useTranslationProgress hook to track the translations separately for MetaFields and DDMFields. I opened another technical task for it: [LPD-22957](https://liferay.atlassian.net/browse/LPD-22957)

Impedibug discovered:
There is a bug with the rich text field, when we change locale the rich-text field already considered translated. This can be reproduced consistently when changing locale the first time and when we change locale from a fully translated locale. This needs to be investigated, but it is connected to the useTranslationProgress hook and DDM not to this story

needs:
feature.flag.LPS-114700=true
feature.flag.LPD-11253=true

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by jkappler** [comment]
@DiegoHu97, @NemethNorbert

**Comment by jkappler** [comment]
ci:report:2562857390

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
