### PR TITLE
LPD-41913 Use a valid emptyResultsMessage in all cases

### PR DESCRIPTION
**Pull request by robertoDiaz**
# What is this trying to solve?

[{url}](https://liferay.atlassian.net/browse/LPD-41913)

Currently the MBCategories are not shown in the search results. In any case the empty results message shows a confusing message that drives customers think that it does

# How am I fixing it?

Changing the message in order to show the expected results

# How can you verify that it works?

Run the included automated tests

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
Fixing the copyright and the Missing breaking change in commit messages and resending

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
