### PR TITLE
Lpd 25685

### PR DESCRIPTION
**Pull request by SamZiemer**
https://liferay.atlassian.net/browse/LPD-25685

This pull adds a new finder method for DLFileShortcut to get all shortcuts in a group.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Review by jonathanmccann — APPROVED** [review]

**Comment by jonathanmccann** [comment]
ci:forward

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by SamZiemer** [comment]
@ambrinchaudhary the relevant test failures do not look related, can this be force forwarded?

**Comment by ambrinchaudhary** [comment]
> @ambrinchaudhary the relevant test failures do not look related, can this be force forwarded?

Yes, if errors are not related this could be forwarded 🎉

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
