### PR TITLE
LPD-6960 Change addFileEntry methods to add the new field displayDate

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
On this PR, I modified the addFileEntry methods on the portal.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:lima

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1287401_8988

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2534828368

**Review by adolfopa — APPROVED** [review]
Everything looks good to me.

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa 

thanks for your review.

I will try to pass the test (lima and relevant) because the PR is a "little" problematic, I only change 1... or 252 files :P

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2535282205

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:lima

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2535763111

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2535719997

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2535855637

**Comment by AliciaGarciaGarcia** [comment]
I will merge with Brian master because there is some merged there things that can make a conflict with this PR

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2536243174

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:test:stable

**Pull request closed without merging**
