### PR TITLE
LPD-34191 Upgrade DDMField and DDMFieldAttribut company id when is 0

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
This is a resend of https://github.com/liferay-content-management/liferay-portal/pull/5769 with a rebase with brian master due to rebase problems : https://github.com/brianchandotcom/liferay-portal/pull/153555#event-14020485235

LPD-32250 Add ExternalReferenceCode to Document Metadata Sets (Part 1)

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-27619

Add ExternalReferenceCode to Document Metadata Sets

# What is this trying to solve?

Add external reference code to dl file entry type to internal api.

# How am I fixing it?

Update the underlying service builder API to use ERC

# How can you verify that it works?

Run the included automated tests.

- Clean bundle
- Create an External Video Shortcut
- see that on database there are the external reference code

# Commits

- **LPD-32250 add company external reference code (ERC) to DLFileEntryMetadata entity**
- **LPD-32250 buildService**
- **LPD-32250 Add upgrade process for ERC and DLFileEntryMetadata table**
- **LPD-32250 add External Reference Code to creation**
- **LPD-32250 modify updateFileEntryMetadata to take into account the external reference code**
- **LPD-32250 add the ERC to the calls of the updateFileEntryMetadata**
- **LPD-32250 Update DataFactory**
- **LPD-32250 add delete By External Reference Code**
- **LPD-32250 buildService**
- **LPD-32250 Add test for upgrade process**
- **LPD-32250 add test to deleteFileEntryMetadataByExternalReferenceCode and UpdateFileEntryMetadata with external reference code**
- **LPD-32250 invoke the service method**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
This is only a rebase with https://github.com/brianchandotcom/liferay-portal as asked on https://github.com/brianchandotcom/liferay-portal/pull/153555#issuecomment-2311337598

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
is failing because reasons not related with this PR, I think

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
If SF is failing we cannot forward force from here. Once you're sure this is not related, you can forward directly to brian.

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa I'll wait if there is some kind of change on brian's or on master T_T

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:73382612

**Comment by AliciaGarciaGarcia** [comment]
ci:report:73382612

**Comment by AliciaGarciaGarcia** [comment]
ci:report:73401301

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
