### PR TITLE
LPD-17905 Move errors to the top of the page

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: https://liferay.atlassian.net/browse/LPD-17905

Description
----
Enable LPS-114700 FF to see that we are showing the errors in the middle of the page, in the fields field set . This PR move the errors to the top of the page below top bar where we have the publish button.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by Mikellorza** [comment]
ci:report:2541012201

**Comment by ambrinchaudhary** [comment]
No unique failures on this pull, it is safe to force forward.

**Comment by ambrinchaudhary** [comment]
ci:force:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
