### PR TITLE
LPD-16652 KB move a locked article shows a modal

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Issues:**

- Move: https://liferay.atlassian.net/browse/LPD-16652
- Revert: https://liferay.atlassian.net/browse/LPD-16388

### CODE REVIEW

**Review by boton — CHANGES_REQUESTED** [review]
The code LGTM ✅ but [not the test](https://github.com/liferay-content-management/liferay-portal/pull/5120/commits/d29858a6fc304b0464f0bb16d5a4c037717c3a1e) ❌ 

I found some describers for grouping one test and several `beforeAll` with the same code.

**Review by marcogalluzzi — APPROVED** [review]
LGTM!!

**Comment by ambrinchaudhary** [comment]
> The code LGTM ✅ but [not the test](https://github.com/liferay-content-management/liferay-portal/pull/5120/commits/d29858a6fc304b0464f0bb16d5a4c037717c3a1e) ❌
> 
> I found some describers for grouping one test and several `beforeAll` with the same code.

Thank you for your comment @boton. I've updated the [tests](https://github.com/liferay-content-management/liferay-portal/pull/5120/commits/6d6744c4e90beb98679ea44f5bc79396661fa487), unfortunately, I cannot remove the last group. 
It seems that the `return` of the `act` in the `beforeEach` sentence does some trick, and I'm not able to remove the group and make it work. 

```
         return act(() =>
				Liferay.componentReady(bridgeComponentId).then(({open}) => {
					open();
				})
			);
```

**Comment by boton** [comment]
@ambrinchaudhary I updated the code to work out the beforeEach and inline some stuff.
Can verify if it's ok for you? 🥺 

---

@ambrinchaudhary Apart from this PR, I'm struggling to debug stuff on these components, aren't we validating `props` in any way? 
no `prop-types` no `ts`??

**Review by boton — APPROVED** [review]
LGTM!! 🚀

**Comment by boton** [comment]
image
@ambrinchaudhary I remove the last `describe` as you ask me 😄

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:report:2537042900

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
