### PR TITLE
LPD-37606 Web Content doesn't publish when FF LPD-11228 is enabled and LPD-15596 is disabled

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[Issue to link](https://liferay.atlassian.net/browse/LPD-37606)

# Motivation
Web Content doesn't publish when FF LPD-11228 is enabled and LPD-15596 is disabled

# How did I solve it
taking in mind another FF for a condition. 

# How to test it
Follow the steps described in the issue https://liferay.atlassian.net/browse/LPD-37606, or run 
`npm run playwright -- test -g 'LPD-37606' --reporter list`

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by DiegoHu97 — CHANGES_REQUESTED** [review]
Hey @ambrinchaudhary , I found a bug: 
- If we enable `LPD-15596` only, and save as draft, the WC is published, could you take a look? Thanks!

**Comment by ambrinchaudhary** [comment]
Hi @DiegoHu97, thank you for testing this carefully. 
I also reproduced what you said: FF autosave disabled (LPD-11228) and FF permissions enabled (LPD-15596 from instance settings) but this also happens without this fix, so I would open a new bug, it is ok for you?

**Comment by DiegoHu97** [comment]
Yeah I agree with that @ambrinchaudhary, thank you!

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Comment by ambrinchaudhary** [comment]
ci:report:27659529

**Comment by ambrinchaudhary** [comment]
Result of the report: 
`journal-web/journalArticle.spec.ts,https://testray.liferay.com/#/project/35392/routines/45357/build/27659529/case-result/27659636/history,Unique,6 Failed tests: LPD-31427: Select web content display template with the Preview feature. Create a web content scheduled. LPD-24942: This is a test for translations filter button in web content. LPD-36441: Navigate in ddm template selector. Check alert message of duplicated friendly URL in french. Create a web content scheduled with workflow activated`

I have checked and all those failures are currently failing on our [last daily routine on testray](https://testray.liferay.com/#/project/35392/routines/1021677/build/26583234/case-result/26617679), so they are not related to this pull. 
I think it is safe to forward @DiegoHu97

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:forward

**Pull request closed without merging**
