### PR TITLE
LPD-32979 | Web content description is missing from table view

### PR DESCRIPTION
**Pull request by bakayattila**
### What is this trying to solve?
https://liferay.atlassian.net/browse/LPD-32979

### How am I fixing it?

Originally the description field was removed from the table view when the highlighted structure feature was released. I fix the issue by adding back the description field with the correct conditions. 
for the conditions see: 
https://liferay.slack.com/archives/CLD39UKM5/p1722243460258949

### How can you verify that it works?

To test run:
`npm run playwright -- test -g 'LPD-32979'`

### CODE REVIEW

**Comment by robertoDiaz** [comment]
PR code seems to be ok.

in any case, could you paste in the description the result of running:

`npm run playwright -- test -g 'LPD-32979' --repeat-each 10 --reporter list`

In order to prevent flaky testing?

Thanks!

**Comment by bakayattila** [comment]
Hi @robertoDiaz,
I found two issues with the test and fixed them both. I forgot again that Liferay persist some settings through the account and forgot to set the display style to table view in the test.

Here are the test results after the force push:

Running 10 tests using 1 worker

  ok 1 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.2s)
  ok 2 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.3s)
  ok 3 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.2s)
  ok 4 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.0s)
  ok 5 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.2s)
  ok 6 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.0s)
  ok 7 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (16.6s)
  ok 8 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (20.6s)
  ok 9 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (18.5s)
  ok 10 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (18.0s)

  10 passed (2.8m)

**Comment by robertoDiaz** [comment]
Goood to go! 👍

**Review by robertoDiaz — CHANGES_REQUESTED** [review]

**Comment by bakayattila** [comment]
Re-run the test just to be sure. 

Running 10 tests using 1 worker

  ok 1 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (46.5s)
  ok 2 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.7s)
  ok 3 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.7s)
  ok 4 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.4s)
  ok 5 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.2s)
  ok 6 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.2s)
  ok 7 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.6s)
  ok 8 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.7s)
  ok 9 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.3s)
  ok 10 [journal-web] › journal-web\journalArticle.spec.ts:411:1 › LPD-32979: Ensure the presence of the Description column when needed (13.5s)

  10 passed (3.0m)

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:sf

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by bakayattila** [comment]
can we rerun the tests? The test passed 10 out of 10 locally on the new build + DB it might have been a CI issue.

**Comment by robertoDiaz** [comment]
> can we rerun the tests? The test passed 10 out of 10 locally on the new build + DB it might have been a CI issue.

Be our guest 😃

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:content-management

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
There is an SF issue at the moment, but I will not fix it until the relevant finishes.

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Seems that current failures are unrelated

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
