### PR TITLE
LPD-19740

### PR DESCRIPTION
**Pull request by adolfopa**
https://liferay.atlassian.net/browse/LPD-19740

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
