### PR TITLE
LPD-40157 Failed Upgrade process .v3_2_6.DeleteStalePWCVersionsUpgradeProcess

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-40157

There is an upgrade process failing because  we are processing document library file entries concurrently. There are some entries with same name, in the same company and in same repository, so, when we are processing the upgrade concurrently we are processing the same file, but from different publication at the same time, and a hibernate error is occurring, because, there are some entries already deleted because of an execution, but in the same time they are part of other executions. This cause a hibernate inconsistency, and for that reason is failing.

# How am I fixing it?

Add dinstinct statement to avoid two process working with same file entry.

# How can you verify that it works?

Running the added tests.

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:52138300

**Comment by Mikellorza** [comment]
There are not unique failures related to this PR. Sol, let's move to brian.

**Comment by Mikellorza** [comment]
ci:forward

**Pull request closed without merging**
