### PR TITLE
LPD-33263 Add ExternalReferenceCode to MBCategory (3rd try)

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-33263

Add the ExternalReferenceCode to MBCategory entity

NOTE: I only replaced the last commit of previous PR #5891 . It seems I didn't understand comments by Brian. See his last comments here: https://github.com/brianchandotcom/liferay-portal/pull/154415#issuecomment-2369801634

# How am I fixing it?

Changing model, adding the ERC to ADD methods, create DELETE methods. Fixing all usages.
Also creating upgrade process.

# How can you verify that it works?

Run `gw tI --tests MBCategoryExternalReferenceCodeUpgradeProcessTest`

### CODE REVIEW

**Comment by Mikellorza** [comment]
Hey @robertoDiaz ,

This PR was reviewed some days ago but the only change is the last commit and it's fine for me, so let's move to brian.

**Review by Mikellorza — APPROVED** [review]

**Comment by Mikellorza** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:report:21118611

**Comment by marcogalluzzi** [comment]
ci:report:21131803

**Comment by marcogalluzzi** [comment]
ci:report:21118611

**Comment by marcogalluzzi** [comment]
ci:report:21118611

**Comment by marcogalluzzi** [comment]
ci:report:21131803

**Comment by marcogalluzzi** [comment]
The failing tests are not related. Forcing forward.

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
