### PR TITLE
Lps 197132 changed exception

### PR DESCRIPTION
**Pull request by manuelRives**
Changes requested on https://github.com/brianchandotcom/liferay-portal/pull/149500

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
ci:forward

**Comment by manuelRives** [comment]
ci:forward

**Pull request closed without merging**
