### PR TITLE
LPD-38720 Notifications for items shared from depots fail to show the item details

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38720

Notification details fail to load when the entry belongs to a depot.  The root problem is that notifications are always evaluated in the context of the control panel and it is not possible to connect the control panel with a depot.

# How am I fixing it?

By considering the control panel as implicitly connected with all depots.

# How can you verify that it works?

Run the included unit tests in `depot-web`:
```
$ gradlew -a test --tests '*DepotAssetRendererFactoryWrapperTest'
```

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:report:36340395

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Failures seem random. Rerunning stable/relevant.

**Comment by jkappler** [comment]
@adolfopa, test failures seem related :disappointed:

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
