### PR TITLE
LPD-28216

### PR DESCRIPTION
**Pull request by rijema**
What is this trying to solve?
I added a new test scenario for workflow tasks using Message Board Asset. 

How am I fixing it?
Adding some functions and locators on MessageBoard pages.

How can you verify that it works?
Run the test added on assignments.spec.ts file on modules/test/playwright 

Hi team, we're to add a second asset in our workflow tests. I modified some content in your module, so it's necessary a second validation from you. This PR is being opened after https://liferay.slack.com/archives/CLD39UKM5/p1721824462727129

This is not the main PR. It's also being evaluated from the BPM front-end team on https://github.com/liferay-workflow/liferay-portal/pull/1201. 

**For content management team it's only necessary to review the changes the MB modules on Playwright [Frontend review]**

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]
changes related to Message Board for playwrigth tests LGTM. Thanks!

**Comment by ambrinchaudhary** [comment]
@rijema should we forward this pull? Anyway there is a SF error...

**Comment by rijema** [comment]
Hi @ambrinchaudhary, thank you so much for reviewing it! Unfortunately the test [is not passing](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1009961/testReport/portal-workflow-task-web_assignments.spec/ts/logged_user_must_be_able_to_see_workflow_task_at_least_from_a_read_only_perspective/) when running through CI, so I think an additional validation (maybe an waitFor in some elements) must be done before submitting to master. Please let me know if you have any suggestion, being honest I'm adventuring on frontend tests.

**Comment by ambrinchaudhary** [comment]
ci:test:playwright

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
> Hi @ambrinchaudhary, thank you so much for reviewing it! Unfortunately the test [is not passing](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1009961/testReport/portal-workflow-task-web_assignments.spec/ts/logged_user_must_be_able_to_see_workflow_task_at_least_from_a_read_only_perspective/) when running through CI, so I think an additional validation (maybe an waitFor in some elements) must be done before submitting to master. Please let me know if you have any suggestion, being honest I'm adventuring on frontend tests.

Sorry I didn't see your message. I will have a deep look on monday for the test, anyway I run again the test to be sure that it fails.

**Comment by rijema** [comment]
Hi @ambrinchaudhary , I ran the playwright tests again and just received the results. In the other PR I pushed a New commit adding waitFor Locators... 

https://github.com/liferay-workflow/liferay-portal/pull/1201#issuecomment-2252857159

But the results are the same, what is really bad as it was escalated. 

Thank you for answering me.

**Comment by ambrinchaudhary** [comment]
Hey @rijema, 

what I see in the playwright logs is that the api calls are failing but I don't get why. Maybe it is better to ask to headless team or in playwright slack channel. 

I see another error in 
```
async publishNewThreadForWorkflow(subject: string, body: string) {
      await this.messageBoardsPage.newThreadButton.click(); 
      ....
}
```

That line should be changed to: 

```
async publishNewThreadForWorkflow(subject: string, body: string, siteUrl?: Site['friendlyUrlPath']) {
      await this.goto(siteUrl);
      ....
}
```
same as the existing function `publishNewBasicTread` does. I would say this is not related to the failures with the API calls, but who knows. Change this and run again playwright suite to check it.

**Comment by rijema** [comment]
Thanks, @ambrinchaudhary .

**Pull request closed without merging**
