### PR TITLE
LPD-24858 normalize the urls in blogs

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by adolfopa** [comment]
@robertoDiaz Can you add a test for the blogs case? Nothing fancy, just something to cover the basic case.

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
