### PR TITLE
LPD-38568 Workaround to enable deprecation feature flag LPD-35013

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38568

We have an issue to enable a deprecation feature flag using feature.flag.LPD-35013=true, see this slack thread: https://liferay.slack.com/archives/CD7939WBE/p1728060218920649?thread_ts=1727435003.757549&cid=CD7939WBE. There is an story to made deprecation enable  works, see: https://liferay.atlassian.net/browse/LPD-4283.

Meanwhile we need wiki tests working. So, with this PR we are adding a workaround to enable deprecation feature flag LPD-35013.

# How am I fixing it?

Add a Wiki macro inside WikiPortlet in order to enable wiki, and add these properties for the testcase file:

property custom.properties = "feature.flag.LPD-35013=false";
property osgi.modules.includes = "wiki";
property portal.release = "false";

# How can you verify that it works?

See in the execution that wiki tests and other tests related with wiki macros are working.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:content-management

**Comment by Mikellorza** [comment]
ci:test:content-management

**Comment by Mikellorza** [comment]
ci:report:34394858

**Comment by Mikellorza** [comment]
ci:report:35101683

**Comment by Mikellorza** [comment]
ci:report:35101683

**Comment by Mikellorza** [comment]
Workaround is working because we have now 106 failed tests [in this execution ](https://testray.liferay.com/#/project/35392/routines/45357/build/35101683?filter=%7B%22testrayTeamIds%22%3A%5B45383%5D%2C%22status%22%3A%5B%22FAILED%22%5D%7D&filterSchema=buildResults&page=1) and before this change we have had [213](https://testray.liferay.com/#/project/35392/routines/1021677/build/34822833?filter=%7B%22status%22%3A%5B%22FAILED%22%5D%7D&filterSchema=buildResults&page=1). So, I think that we can move forward with this solution.

**Review by ambrinchaudhary — APPROVED** [review]
LGTM! thank you @Mikellorza

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
