### PR TITLE
[Release Blocker]  LPD-44157 if parts has one element can have article, so only skip if there is none

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-44157 KB is not shown when accessing from FriendlyURL on Display Page

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-44157

On some cases (/web/site-name/k/knowledge-base-article-title) the friendlyURL comes this way and arrives as /knowledge-base-article-title.

# How am I fixing it?

Allow to search of the kbartricle if the url title can be divided on at least one direction

# How can you verify that it works?

Covered by: 
[LocalFile.KBDisplayPage#CanUpdateMaxNestingForArticleNavigation](https://testray.liferay.com/web/testray#/project/35392/routines/82964/build/85270592/case-result/85601045)

[LocalFile.KBDisplayPage#CanViewArticlesViaKBNavigation](https://testray.liferay.com/web/testray#/project/35392/routines/82964/build/85270592/case-result/85526421)

[LocalFile.KBDisplayPage#CanViewArticleWithDefaultTemplate](https://testray.liferay.com/web/testray#/project/35392/routines/82964/build/85270592/case-result/85534864)
and KBArticleLayoutDisplayPageProviderTest
 

- Steps to reproduce:

- Go to Design > Page Templates > Display Page Templates and create one for Knowledge Base
- Name: DPT for KB 
- Content Type: Knowledge Base Article
- Add a Knowledge Base Navigation fragment on it. 
- Go to Content & Data > Knowledge Base and create an article with the previous Display Page Template
- Title: KB Article (friendly url will be kb-article)
- Try to access http://localhost:8080/web/guest/k/kb-article 

# Commits

LPD-44157 if parts has one element can have article, so only skip if there is none

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hey @robertoDiaz

Can you check if my supposition is correct or we should find other way to fix it?

Thanks!

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
@robertoDiaz will double check that this is correct.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
