### PR TITLE
LPD-21570 Add get Field.CONTENT with defaultLocale

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi, 

May I ask to review this PR?

The issue is https://liferay.atlassian.net/browse/LPD-21570. 

Routcause that, if I change the language, the [content](https://github.com/liferay/liferay-portal/blob/9c928b1c2ffed8fb857db5441031ab72cd24032a/modules/apps/portal-search/portal-search-web/src/main/resources/com/liferay/portal/search/web/internal/search/results/web/portlet/display/template/dependencies/portlet_display_template_list.ftl#L78) of entry is empty. 

Root cause  [DLFileEntryModelSummaryContributor](https://github.com/liferay/liferay-portal/blob/886a3d8fa108885f2787438ca8d74a5d005cb65e/modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/search/spi/model/result/contributor/DLFileEntryModelSummaryContributor.java#L33) doesnt find the field name, because there is no localized value of the content and the field name is defaultLocale, prefix + Field.CONTENT, but it searches for other options only.

Solution: If it doesnt find localized value, it should check defaultLocale, prefix + Field.CONTENT before checking defaultLocale, prefix + Field.DESCRIPTION.

tested it locally.

Thanks in advance!

BR,
Gege

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:report:2557248990

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
