### PR TITLE
LPD-35434 Categorization is empty in content dashboard info panel

### PR DESCRIPTION
**Pull request by NemethNorbert**
# What is this trying to solve?

[LPD-34375](https://liferay.atlassian.net/browse/LPD-35434)

The order of the tabpanes are very important for the clay tabcomponent and we cannot have an effect on the indexes thru conditional statements as it will have an unwanted effect on the render of the tabs and their active state.

# How am I fixing it?

I made sure we use the same indexes for the tabs when we set `feature.flag.LPD-28830=true`

# How can you verify that it works?

Follow ticket description => [LPD-34375](https://liferay.atlassian.net/browse/LPD-35434)

# Why doesn't this include any test?
There are already tests that were failing due to this bug and they are sufficient to test this usecase. There is no need to modify or extend the tests.
Failing test => [LPD-35431](https://liferay.atlassian.net/browse/LPD-35431)

\cc  @interaminense  as this bug was introduced by [LPD-33169](https://liferay.atlassian.net/browse/LPD-33169) and I changed the order of the tab panels. If this change goes against the requirement of your story, you can render two different tab and tabplane conditionnaly as well.

### CODE REVIEW

**Review by ambrinchaudhary — CHANGES_REQUESTED** [review]
Changes LGTM!
Just one thing, the ticket and the commit number is wrong, the correct would be https://liferay.atlassian.net/browse/LPD-35434 isn't it?

**Comment by NemethNorbert** [comment]
> Changes LGTM! Just one thing, the ticket and the commit number is wrong, the correct would be https://liferay.atlassian.net/browse/LPD-35434 isn't it?

My bad, The correct ticket is this one : [LPD-35434](https://liferay.atlassian.net/browse/LPD-35434)

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:content-management-playwright

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by interaminense** [comment]
Hey @NemethNorbert, it is missing commit to update snapshot unit test, right?

**Comment by NemethNorbert** [comment]
Hey @ambrinchaudhary,

I pushed up the commit with the new snapshot, Srry I did not know I had to commit that as well.

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
