### PR TITLE
LPD-36818 Disable backwards compatibility markup processor

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-36818

This transformer was included back in the day, when Adaptive Media was introduced. Its purpose was to avoid the need for a costly upgrade.

All new content created since (fragments, web content and blogs) does no longer need to be processed, so this transfomer can be removed. As a first step, we're simply disabling it via configuration; in the future we'll deprecate and remove the feature.

# How am I fixing it?

I've added a company scoped configuration to enable the transformer. By default it will be disabled.

# How can you verify that it works?

Existing unit tests cover the feature. I've added an additional test to double check that it does nothing when disabled.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:report:14633835

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
