### PR TITLE
LPD-38828 Technical Task | Merge FF LPS-203351 (LPS-203351) with Configurable URLs for Asset Types (LPD-11147)

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38828

Merge FF LPS-203351 (LPS-203351) with Configurable URLs for Asset Types (LPD-11147)

# How am I fixing it?

Changing occurrences from LPS-203351 to LPD-11147

# How can you verify that it works?

No tests needed because it is a change from a feature flag to another.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:content:management

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:content:management

**Comment by Mikellorza** [comment]
ci:help

**Comment by Mikellorza** [comment]
ci:test:content-management

**Comment by Mikellorza** [comment]
ci:report:38857928

**Comment by Mikellorza** [comment]
There are two unique error in relevant suite but there are not related with this PR.

**Comment by Mikellorza** [comment]
ci:report:38928523

**Comment by jkappler** [comment]
@Mikellorza, checking the failures, they don't seem to be related. It's good to be forwarded

**Comment by Mikellorza** [comment]
Agree with you @jkappler. So, let's move to brian.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
