### PR TITLE
LPD-39287 Change ASTERISK_DATE_FIELD icon path, remove span

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi,
May I ask to review this PR?

This is for https://liferay.atlassian.net/browse/LPD-39287.

**Rootcause**: Asterisk Icon changed, probably <span> was removed.

**Solution**: appended an OR section to the locator to get without span.

Thank you in advance!

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Comment by gergelyszalay** [comment]
ci:test:available:suites

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:reevaluate:1287401_11397

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:stop

**Comment by gergelyszalay** [comment]
Hi @jkappler, I checked the test-suites, and I didn't find any related failure. Thx

**Comment by jkappler** [comment]
@gergelyszalay

**Comment by gergelyszalay** [comment]
ci:forward

**Pull request closed without merging**
