### PR TITLE
LPD-27402 OOTB Image - Adaptive Media doesn't render if map a PDF Preview Image

### PR DESCRIPTION
**Pull request by jkappler**
OOTB Image - Adaptive Media doesn't render if map a PDF Preview Image

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-27402)

When the content that arrives to BaseRegexStringContentTransformer contains a file entry that is not supported, the content is returned without replacing the values of the file entries that are supported.

# How am I fixing it?

Don't return the unprocessed content when an invalid file entry is found, just avoid processing it and treat this as the matcher

# How can you verify that it works?

Follow the steps provided in the ticket, or run the provided unit test

### CODE REVIEW

**Review by robertoDiaz — APPROVED** [review]
Good to go :)

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report: 9637904

**Comment by jkappler** [comment]
ci:report:9637904

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Test is not related to the PR

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
