### PR TITLE
[Playwright] LPD-35873 Fix 'displays second dropdown level for Size item with Small, Medium and Large options'

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-35873

We are fixing a failing test.
image

# How am I fixing it?

I'm making the locator selectors more explicit.

# How can you verify that it works?

1. Go to `/modules/test/playwright`
3. Run `npm install` (setup)
4. Run `npm run playwright -- test -g 'displays second dropdown level for Size item with Small, Medium and Large options'` to run the test

# Avoid flakiness by repeating 20 times

```sh
npm run playwright -- test -g 'displays second dropdown level for Size item with Small, Medium and Large options' --repeat-each 20
```
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
The playwright test passed in CI 
[[master] ci:test:content-management-playwright - boton > liferay-content-management - PR#5851 - 2024-09-10[03:57:23]](https://testray.liferay.com/#/project/35392/routines/45357/build/6470333)

image

**Review by Mikellorza — APPROVED** [review]
LGTM!

**Comment by Mikellorza** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
@Mikellorza the suite `ci:test:content-management-playwright` passed yesterday 😄 

https://github.com/liferay-content-management/liferay-portal/pull/5851#issuecomment-2340551584 https://github.com/liferay-content-management/liferay-portal/pull/5851#issuecomment-2340685122

**Comment by Mikellorza** [comment]
Ah, sorry @boton , normally we should not run the tests before we have the PR approved, for that reason I ran it, It's an automatism that I have jej

**Comment by boton** [comment]
It looks like it is passing https://testray.liferay.com/#/project/35392/routines/45357/build/7966362?filter=%7B%22testrayCaseName%22%3A%22filters.spec.ts%22%7D&filterSchema=buildResults&page=1
image
image

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
