### PR TITLE
LPD-17228 Update test/ci references to match new team name

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-17228

Lima is going to be known as "Content Management" from now on. Update the test/ci references to the old name.

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
@adolfopa I suppose we leave moving related Echo components to Content Management test suites for another PR, right?

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
There are many `test.properties` files in modules that references Lima components, like this:

```
    ##
    ## Relevant
    ##
    
        test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant]=\
            (testray.component.names == "Depot") AND \
            (testray.main.component.name == "Upgrades Lima")
    
    ##
    ## Testray
    ##
    
        testray.main.component.name=Depot
```

Also file  `poshi-ext.properties`

**Comment by austinchiang** [comment]
Thanks for the catch @marcogalluzzi, I will update them

**Review by austinchiang — APPROVED** [review]

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
@adolfopa @marcogalluzzi I have also created another PR in the Jenkins-EE repo to update Lima references there: https://github.com/pyoo47/liferay-jenkins-ee/pull/3065

**Pull request closed without merging**
