### PR TITLE
LPD-21578 revert "LPS-188471 Use the new method to obtain the other values"

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
We do not want that an unsaved Web Content had the default value on a new field of her structure. So if the WC was not modified since the change on the structure, the WC will have a BLANK value on the new field, although the latter has or does not have a default value.

https://liferay.atlassian.net/browse/LPD-21578

Steps to reproduce:

1) Create a new Web Content Structure with a text field
2) Go to Edit Default Values for that structure and click in the button Save.
3) Create a Web Content based off of this structure
4) Go to the Translate View of this Web Content (3-dot button of the Web Content > Translate)

Result:

- The text field appears only one time.

 

additionally we should test:

1) Create a Web Content Structure with a text field “Text1”
2) Create a Web Content based off of that Web Content Structure
3) Add a new field “Text2” to the Web Content Structure
4) Edit the default values of the Web Content Structure and set Text2 field to “My Default Value”
5) Map it to Text2 field of the Web Content created in step 2

Actual result:

The Heading fragment displays the value “”

### CODE REVIEW

**Comment by adolfopa** [comment]
@dacousalr We're reverting some changes that caused a regression. The original ticket may need some additional work on your part.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2558505873

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
