### PR TITLE
LPD-28317 Create test for LPP-48699 Paginator is lost when searching Web Content

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28317

It adds a test for the error found in LPP-48699 and solved in LPS-177189

# How am I fixing it?

I've added an integration test calling the `getSearchContainer` method of the `JournalDisplayContext` class.

# How can you verify that it works?

I had to revert changes in LPS-177189 to check that the test `testGetSearchContainerWithKeywordsAndDelta` fails.

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:report:16694942

**Comment by adolfopa** [comment]
Failures look unrelated. Rerunning stable.

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
