### PR TITLE
LPD-38992 Investigate test failures in Staging#PublishViaPortletWithoutContent

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38992

Fix staging failure :  Staging#PublishViaPortletWithoutContent 

There is a configuration to publish content for portlet display like web content display in staging config called : Publish Displayed Content By Default

# How am I fixing it?

Reverting changes of LPD-37071

# How can you verify that it works?

Run Staging#PublishViaPortletWithoutContent  test

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:37764050

**Comment by Mikellorza** [comment]
ci:report:37764050

**Comment by Mikellorza** [comment]
ci:report:37764050

**Comment by Mikellorza** [comment]
ci:report:37779908

**Comment by Mikellorza** [comment]
There are not unique failures on relevant suite: [[master] ci:test:relevant - Mikellorza > liferay-content-management - PR#5970 - 2024-10-10[01:26:30]](https://testray.liferay.com/#/project/35392/routines/45357/build/37779908). So, let's move to brian.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
