### PR TITLE
LPD-28453 Migrate some KBArticleSchedule.testcase to Integration-playwright test . add methods

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-28453 Migrate some KBArticleSchedule.testcase to Integration-playwright test > ADD methods

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28453

migrating some test to integration test and playwright 

# How can you verify that it works?

Run the included automated tests

# Commits

- **LPD-28453 POSHI test not needed, covered by playWright with minor changes CanAddArticleWithScheduledDate > 'can schedule and delete an article with scheduling enabled' CanPublishScheduledArticleImmediately > 'can publish and delete an article with scheduling enabled'**
- **LPD-28453 add some integration test that cover some no longer needed Poshi test**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:playwright

**Review by boton — APPROVED** [review]
The playwright part 9a01add9fa86386522153853fc2dc5fd9fe926b4 LGTM!

The integration test part ada12e4f305a41d5a84d7dcf2fef0f85e6696152 is missing from the review.

**Comment by boton** [comment]
Waiting for the `ci:test:playwright` results 👀  too.

**Comment by adolfopa** [comment]
ci:reevaluate:1277401_12127

**Comment by adolfopa** [comment]
Failures are unrelated.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
