### PR TITLE
LPD-39410 Add deprecation notice to message boards admin

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-39410

Add a deprecation notice to the message boards admin widget.
image

# How can you verify that it works?

Go to Content & Data > Message boards; assert that the deprecation badge appears in the top bar.

# Why doesn't this include any test?

This is a visual change, where a badge is displayed in the top bar.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by Mikellorza — APPROVED** [review]

**Comment by jkappler** [comment]
@Mikellorza, @adolfopa, I think it's good to fwd, failing test is a known issue

**Comment by Mikellorza** [comment]
ci:report:43002622

**Comment by adolfopa** [comment]
Ok. I'll forward it manually.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155211

**Pull request closed without merging**
