### PR TITLE
LPD-40520 Enable FF to execute wiki poshi tests

### PR DESCRIPTION
**Pull request by balazssk**
https://liferay.atlassian.net/browse/LPD-40520

### CODE REVIEW

**Comment by balazssk** [comment]
Updated based on https://github.com/liferay-content-management/liferay-portal/pull/5957

**Comment by balazssk** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:content:management

**Comment by Mikellorza** [comment]
ci:test:content-management

**Review by Mikellorza — APPROVED** [review]
Hey Balazs,

As we talked in slack, at least I think we have to add : `property custom.properties = "feature.flag.LPD-35013=false"; ` to the top of the test, and I am not clear if we have to add `property portal.release = "false";`. So take a look if it needed and move to brian when the test is passing.

**Comment by balazssk** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:report:53684372

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
SF and test is passing in CI. So I'm going to forward the pull. 
Screenshot 2024-10-29 at 10 05 39

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
