### PR TITLE
LPD-27912 Migrate POSHI tests to integration tests

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-27912

Migrate flaky POSHI tests to integration tests.

# How can you verify that it works?

Run the `DLAppServiceWhenGettingAFileEntryTest` integration test.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by adolfopa** [comment]
Test failures are unrelated.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
