### PR TITLE
LPD-19234 Web Content copy feature drops attached images if they are the same

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPD-19234)

Avoid copying the image when it's not in the journal repository. This is also a performance improvement since we don't want to create the image several times

## Change summary:

* Adds check so that only images from the resources forlder of web content are copied
* Adds integration test

## Notes

For the test we don't want to use a temporary file entry, since it will be stored in the web content repository, so use a normal file entry

## Test Scenario 1

* Add a new image to documents and media
* Create a new folder, and add the same image to the folder
* Create a new web content structure with 2 image fields and save
* Create a new web content based on the structure and select both images that were created in the previous steps (they have the same name but are in different folders)
* Click on the kebab of the web content and select "Make a copy"
* Open the new web content and you will see both images

## Test Scenario 1

* Create a new web content structure with 2 image fields and save
* Create a new web content based on the structure and for the first image select "Web Content Images" and upload a new image and select it
* Publish and edit the web content again
* Select the same image for the second image field and publish
* Click on the kebab of the web content and select "Make a copy"
* Open the new web content and you will see both images

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks for the review @AliciaGarciaGarcia ❤️

**Comment by jkappler** [comment]
ci:report:2546075188

**Comment by jkappler** [comment]
No unique failures for the PR

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2546107931

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
