### PR TITLE
LPD-19625 Change icon from lock to password-policies

### PR DESCRIPTION
**Pull request by jkappler**
subtask: https://liferay.atlassian.net/browse/LPD-19625

@Mikellorza

### CODE REVIEW

**Comment by jkappler** [comment]
ci:report:2550176125

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Comment by Mikellorza** [comment]
ci:forward:force

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
