### PR TITLE
LPD-30245 Fix [playwright] [flaky] LPD-6813: Make prefix URLs configurable

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-30245

Fixing broken test

# How am I fixing it?

The test is failing because we configured the `data-qa-id` globally 62fdc150aec50a70247fba9e00a0dbfe3f444960, I reverted it bb2de38ed2891470067105263f3592210e5e75aa.

It needed to fix the global performLogut to work without the `data-qa-id` global 1f3bc3e53a2a842bdcfd78485e2237257809c9ab.

Avoid the use of `data-testid` 55b9402649e40228abf2bdf11505811354d2a442 9db0c05986524488a121c25f1b35720efb27b033.

Avoid test flakiness because the reset click is only working sometimes 484b31a16e5ea9f38fb0871ee4b46f54b1843754.

# How can you verify that it works?

1. Go to `/modules/test/playwright`
3. Run `npm install` (setup)
4. Run `npm run playwright test -- -g "LPD-6813"` to run the test

# Avoid flakiness by repeating 10 times

```sh
npm run playwright test -- -g "LPD-6813" --reporter list --repeat-each 10
```

image

> [!NOTE]
> **Unrelated failure** at perfomLogin

### CODE REVIEW

**Comment by boton** [comment]
ci:test:playwright

**Comment by boton** [comment]
Some failures are related to test-id changes 🤦

**Comment by boton** [comment]
ci:test:playwright

**Comment by boton** [comment]
This commit 666296865be5d87033fd0867d67107b53135ceac fixes a several search-experiences-web and journal-web tests.

## Before commit
image
image

## After commit

image
> [!NOTE]
> Some not related selector that resolves in two still fail but look unrelated with **testId** changes


image

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
ci:test:playwright

**Comment by boton** [comment]
We must wait until `ci:test:playwright` finishes ⏳ .

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Relevant failures look unrelated.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
