### PR TITLE
LPD-36211 Message board thread attachment is deleted after clicking `Cancel` in the confirmation

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-36211

The message board thread attachment was deleted after clicking `Cancel` in the confirmation.

# How am I fixing it?

I use `href` attribute instead of `data-url`, and show the confirm modal if JS is enabled.
With JS disabled the attachment is deleted without confirmation. 

# How can you verify that it works?

Follow the steps described in https://liferay.atlassian.net/browse/LPD-36211

# Why doesn't this include any test?
I updated the old poshi d1970ebbf215b4c7b0926777a92a22f4507f7a9d

> [!CAUTION]
> Only the default value of property `trash.enabled=true` is covered by [RecycleBin#RecycleBinMBAttachment](https://github.com/boton/liferay-portal/blob/LPD-36211-BUG-MB-delete-attachment-cancel-confirm/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/trash/RecycleBin.testcase#L159) (recycle bin activated)
> PR doesn't contain automated tests covering the bug because the tests need to change the portal's default behavior disabling the trash in the test env.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:message-boards

**Review by ambrinchaudhary — APPROVED** [review]
Checking the code everything LGTM! It makes sense every change done. 

I didn't have time to download and test it, but I didn't want to postpone the review... let me know if you consider it necessary.

**Comment by ambrinchaudhary** [comment]
ci:report:11564424

**Comment by ambrinchaudhary** [comment]
No unique failures, I will forward this. 

```
Unique Failures
NONE,N/A,Unique,N/A

Common Failures
LocalFile.MBNotifications#NoWebsiteNotificationAppearsForUpdatedThreadInCategory,
LocalFile.MBNotifications#NoWebsiteNotificationAppearsForNewThreadInCategory,
```

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
