### PR TITLE
LPD-33473 Limit expansion size of PNG compressed chunks

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-33473

Put an upper limit to the amount of memory a compressed PNG chunk may consume on expansion.

# How am I fixing it?

By patching a third party library.  When expanding deflated PNG chunks, truncate those that exceed our established maximum (5 MiB).

# Why doesn't this include any test?

This affects memory usage, there's no significant behavior change.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
LGTM @adolfopa

**Comment by robertoDiaz** [comment]
ci:forward

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
