### PR TITLE
LPD-40544 Fix test DepotSharing#CanShareSameDocumentByDifferentUsers

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-40544

This test is failing: `DepotSharing#CanShareSameDocumentByDifferentUsers`

* A user cannot see the shared item.

# How am I fixing it?

Added missing connection between Asset Library and Site.

# How can you verify that it works?

Run `ant -f build-test.xml run-selenium-test -Dtest.class=DepotSharing#CanShareSameDocumentByDifferentUsers`

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
hey @marcogalluzzi could you check the SF error? once fixed you can forward this.

**Comment by marcogalluzzi** [comment]
@ambrinchaudhary thanks for having a look. The SF error seems odd. I've open a Slack thread to find the reason.

**Comment by ambrinchaudhary** [comment]
Seems to be the same: https://github.com/liferay-devtools/liferay-portal/pull/283

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
