### PR TITLE
LPD-16392 Exclude text plain to avoid modify it in some cases

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
Hi @robertoDiaz this faling test may be related to the PR: [LocalFile.SecurityUsecase#EscapeUrlRedirectWithGroovyScript](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/351012//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SecurityUsecase_EscapeUrlRedirectWithGroovyScript_)

**Comment by robertoDiaz** [comment]
Yes, @marcogalluzzi 

I had already seen that (since I'm monitoring the failures in all my PRs), anyway I have other priorities so I'll have a look once I have bandwidth.

Thanks!

**Comment by robertoDiaz** [comment]
This test should not be related.

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:report:2535460720

**Comment by robertoDiaz** [comment]
ci:forward:force

**Pull request closed without merging**
