### PR TITLE
LPD-27931 Status for documents are not being displayed correctly if they have multiple status

### PR DESCRIPTION
**Pull request by jkappler**
Expired documents with past versions still shown in Content Dahsboard even when filtering for status Approved

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-27931)

Labels for status are handled different for files than for web content. This PR addresses the issue

# How am I fixing it?

Retrieve the latest approved file version for checking

# How can you verify that it works?

Follow the steps in the ticket or execute the provided integration test

Screenshot 2024-06-06 at 15 00 15

### CODE REVIEW

**Review by Mikellorza — APPROVED** [review]
LGTM!

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:reevaluate:1337401_6126

**Comment by jkappler** [comment]
@Mikellorza, found the issue, but have some issues fixing it, will do it tomorrow

**Comment by Mikellorza** [comment]
Perfect @jkappler .

thanks for it

**Comment by jkappler** [comment]
@Mikellorza, added a new commit adapting the test as we talked

**Review by Mikellorza — APPROVED** [review]

**Comment by Mikellorza** [comment]
ci:forward

**Pull request closed without merging**
