### PR TITLE
LPD-31466 org.hibernate.StaleStateException occurs when deleting document with custom field in a publication

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
thanks @pei-jung!

**Comment by pei-jung** [comment]
That was a fast review! Thanks @jkappler! 😄

**Comment by jkappler** [comment]
I was looking at other PRs and noticed that you had send it @pei-jung. Also, I had taken a look at the one where you mentioned me 🫶.

Thanks again!

**Comment by pei-jung** [comment]
ci:report:38937995

**Comment by pei-jung** [comment]
ci:report:38937995

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
