### PR TITLE
LPD-28177 Change FF from LPS-141392 to LPD-11228

### PR DESCRIPTION
**Pull request by DiegoHu97**
Change FF from LPS-141392 to LPD-11228

# What is this trying to solve?

Change FF from LPS-141392 to LPD-11228 

[Link to ticket](https://liferay.atlassian.net/browse/LPD-28152)

# How am I fixing it?

Change FF

# Why this does not need tests?

This is just a change of FF, no need to create tests for it

### CODE REVIEW

**Comment by NemethNorbert** [comment]
Hey @DiegoHu97,

The FF should be `LPD-11228` instead of `LPS-11228,` isnt it?

**Review by ambrinchaudhary — CHANGES_REQUESTED** [review]
> Hey @DiegoHu97,
> The FF should be LPD-11228 instead of LPS-11228, isn't it?

Thanks @NemethNorbert! 🫶

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:report:14597841

**Comment by DiegoHu97** [comment]
ci:forward:force

**Pull request closed without merging**
