### PR TITLE
LPD-33986 Exceptions in WC Structures page are not handled correctly

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-33986

1) Exceptions raised during the “Import and Override” action of a Structure produces an error page:

image

2) Some exceptions have a specific message to show but a general one is shown instead (incorrect handling order)

# How am I fixing it?

1) I'm adding the exception object to the SessionError
2) Reording the handling of the exceptions in the JSP file

# How can you verify that it works?

Run: `npm run playwright -- test -g 'LPD-33986'`

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:content-management-playwright

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:report:30362950

**Comment by marcogalluzzi** [comment]
Playwright failures are not unique. Forcing forward.

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
