### PR TITLE
LPD-32250 Add ExternalReferenceCode to Document Metadata Sets (Part 1)

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-32250 Add ExternalReferenceCode to Document Metadata Sets (Part 1)

with added commits from https://github.com/brianchandotcom/liferay-portal/pull/153692#issuecomment-2315781724 with a no needed and an additional test

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-27619

Add ExternalReferenceCode to Document Metadata Sets

# What is this trying to solve?

Add external reference code to dl file entry type to internal api.

# How am I fixing it?

Update the underlying service builder API to use ERC

# How can you verify that it works?

Run the included automated tests.

- Clean bundle
- Create an External Video Shortcut
- see that on database there are the external reference code

# Commits

- **LPD-32250 add company external reference code (ERC) to DLFileEntryMetadata entity**
- **LPD-32250 buildService**
- **LPD-32250 Add upgrade process for ERC and DLFileEntryMetadata table**
- **LPD-32250 add External Reference Code to creation**
- **LPD-32250 modify updateFileEntryMetadata to take into account the external reference code**
- **LPD-32250 add the ERC to the calls of the updateFileEntryMetadata**
- **LPD-32250 Update DataFactory**
- **LPD-32250 add delete By External Reference Code**
- **LPD-32250 buildService**
- **LPD-32250 Add test for upgrade process**
- **LPD-32250 add test to deleteFileEntryMetadataByExternalReferenceCode and UpdateFileEntryMetadata with external reference code**
- **LPD-32250 invoke the service method**
- **LPD-34191 as used**
- **LPD-32250 Don't use ArrayUtil.toString for this**
- **LPD-32250 SF**
- **LPD-32250 not needed**
- **LPD-32250 test to check testUpdateFileEntryMetadataWithExistingExternalReferenceCode throws an  DuplicateDLFileEntryMetadataExternalReferenceCodeException**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
wrong ci.stop branch, my bad :D

**Comment by AliciaGarciaGarcia** [comment]
ci:report:74589382

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:76097724

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:77903451

**Comment by AliciaGarciaGarcia** [comment]
ci:report:77921008

**Comment by AliciaGarciaGarcia** [comment]
ci:report:77921008

**Comment by AliciaGarciaGarcia** [comment]
ci:report:77921008

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
