### PR TITLE
LPD-33707 if instance id of the node is not null, set the text content to random string to prevent duplicate or null data

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-33707 Duplicate Entries for IX_1BB20E75 in DDMField when instance id is null

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-33707

On the com.liferay.journal.internal.upgrade.v4_0_0.JournalArticleDDMFieldsUpgradeProcess, depending on the data of the database, the instance-id is null or empty or repeated giving 2 errors, a NPE and the IX_1BB20E75 .

# How am I fixing it?

If the field is not null and is repeated, the IX_1BB20E75 error can happen.
When the values is empty, the `instanceToFieldIdMap.get(ddmFieldInfo._parentInstanceId)` or `instanceToFieldIdMap.get(ddmFieldAttributeInfo._ddmFieldInfo._instanceId)` was throwing a NPE and was masked as a index failure by the batch. 

So set the text content to random string to prevent duplicate or null data solves this.

# How can you verify that it works?

The way to verify this is to reproduce the steps on https://liferay.atlassian.net/browse/LPP-55173

# Why doesn't this include any test?

without the client data and the upgrade from 6.2, I don't know how to reproduce it, **in addition** the failing upgrade is on a database version whose table have **2 columns** that master does not have.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:upgrade-all

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
looks good @AliciaGarciaGarcia! Please feel free to forward once upgrade tests finish

**Comment by jkappler** [comment]
@AliciaGarciaGarcia, if we can add a test, then that would be great

**Comment by AliciaGarciaGarcia** [comment]
ci:report:59907307

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
a lot of 
image
re-launching

**Comment by AliciaGarciaGarcia** [comment]
ci:test:upgrade

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
upgrade failures seems CI related :(

**Pull request closed without merging**
