### PR TITLE
LPD-21244 Add integration test

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: https://liferay.atlassian.net/browse/LPD-21244
story : https://liferay.atlassian.net/browse/LPD-19314

Description
-----------
Modify existing test to check that headless api returns new field : frienlyUrlPath

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
@Mikellorza, you can fw when you see fit :D

**Comment by Mikellorza** [comment]
ci:report:2555516986

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:reevaluate:1357401_5564

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:2555815703

**Comment by Mikellorza** [comment]
ci:report:2555681503

**Comment by Mikellorza** [comment]
Failed test is not related with this PR.

@AliciaGarciaGarcia see this fail because I think this is related with your recent changes : [com.liferay.document.library.web.internal.scheduler.test.CheckFileEntrySchedulerJobConfigurationTest](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1072014/testReport/com.liferay.document.library.web.internal.scheduler.test/CheckFileEntrySchedulerJobConfigurationTest) - [Failed 0 of last 23](https://testray.liferay.com/home/-/testray/case_results/2555106510/history)

So, let's move to brian.

**Comment by Mikellorza** [comment]
ci:forward:force

**Comment by Mikellorza** [comment]
Conflict in portal.properties file, see the fix : https://github.com/brianchandotcom/liferay-portal/pull/148607

**Pull request closed without merging**
