### PR TITLE
LPD-28461 Web content Display Page "Preview" button shows 404 error when there is an expired past version

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28461

Web content Display Page "Preview" button shows 404 error when there is an expired past version

# How am I fixing it?

In [JournalArticleAssetRendererFactory.getAssetRenderer](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalArticleAssetRendererFactory.java#L129) it prefers to fetch scheduled and expired articles prior to draft ones. To fix the current issue while avoiding breaking [LPS-178363](https://liferay.atlassian.net/browse/LPS-178363) I opted to pass in the article that we already have instead of fetching it again.

# How can you verify that it works?

Run the included test or manually test using the steps on https://liferay.atlassian.net/browse/LPD-28461

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1357401_5889

**Comment by adolfopa** [comment]
Looks unrelated; I'll try stable once more and forward.

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by jonathanmccann** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by jkappler** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
These three tests seem to be failing in general, not due to the changes here. Can we force this forward?

**Comment by jkappler** [comment]
Hi @jonathanmccann, yes, lets move forward, the failures don't seem to be related

**Comment by jonathanmccann** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
