### PR TITLE
LPD-39226 Review PR "Allow using directive script-src-attr 'none' by removing inline handlers"

### PR DESCRIPTION
**Pull request by izaera**
This is a rework of https://github.com/liferay-content-management/liferay-portal/pull/6007 using a newer approach that has already been merged to master.

In theory the code is equivalent to the original one, but it would probably be wise checking everything at CI again just in case...

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_18501

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_18501

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_18501

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_18501

**Comment by adolfopa** [comment]
ci:test:relevant

**Pull request closed without merging**
