### PR TITLE
LPD-39274 Check if parent group has enabled to share the content with child site

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-39274 A child site is displaying Web Content from the parent site, despite the configuration being set to prevent this

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-39274

On the case that the parent do not allow child site to access their content we should check it.

# How am I fixing it?

On the method that obtains the connected groups to accesing the article, pass a new parameter to check if we are allowed to see the parent content. For this we need new methods to pass the boolean to the portalImpl method.

# How can you verify that it works?

Run the included automated tests.

# Commits

- **LPD-39274 on the Site Connected Group Provider, add methods to check if between the ancestors we have the property Content Sharing With Children Enabled**
- **LPD-39274 baseline**
- **LPD-39274 add the new parameter on the methods as false when needed**
- **LPD-39274 check if accessing the article we have the content Sharing With Children Enabled**
- **LPD-39274 add test to check that the journal articles is shown or not depends on the property SITES_CONTENT_SHARING_WITH_CHILDREN_ENABLED**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:report:41700911

**Review by robertoDiaz — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Errors may be related. There are some log messages about `DepotAdminGroupSearchProvider`.

**Comment by AliciaGarciaGarcia** [comment]
after investigate, in my opinion the errors are not relevant with this PR

I created https://liferay.atlassian.net/browse/LPD-39779 about the logs on the depot tests

cc/ @adolfopa

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1307401_10310

**Comment by AliciaGarciaGarcia** [comment]
ci:report:47591854

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:47931706

**Comment by AliciaGarciaGarcia** [comment]
ci:report:47934458

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
