### PR TITLE
LPD-17556 publish document when reach display date

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Steps to test:

1) Change on System Settings > Documents and Media > Service > Check Interval : to 1 min
2) create a document with a schedule date now + 3 mins and publish
3) ensure the document has the schedule label
4) wait 3 mins
5) ensure the document is published (approved)

-- plus

6) modify the document with a schedule date now + 1 year and change the title, then publish 
7) ensure the document has the schedule label AND the approved on

Commits
- LPD-17556 update always the display date 
- LPD-17556 search between the previous date and that is not null 
- LPD-17556 add integration test

### CODE REVIEW

**Review by marcogalluzzi — COMMENTED** [review]
Hi @AliciaGarciaGarcia the "plus" steps don't work for me: I only see the "scheduled" label after modifying the publish date.

**Comment by AliciaGarciaGarcia** [comment]
> Hi @AliciaGarciaGarcia the "plus" steps don't work for me: I only see the "scheduled" label after modifying the publish date.

hey @marcogalluzzi , I changed a little the steps, can you recheck?

**Review by adolfopa — APPROVED** [review]

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2549606458

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2549976503

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
