### PR TITLE
[BLOCKER] LPD-26758  No AssetEntry exists with the key / My Workflow Tasks is temporarily unavailable

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-26758

Reverting a commit that prevent accessing DL File Entry assets in "My Workflow Tasks"

# How am I fixing it?

Don't repeat what the code already says, try to give a bird's eye perspective so that the code is easier to understand.

# How can you verify that it works?

Follow steps in issue.

Also a POSHI test exists and [it executes correctly in CI.](https://testray.liferay.com/home/-/testray/case_results/2572419374?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F2150442030%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D2150442030%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc) 
Also existing tests related to the reverted issue still works correctly.

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]
as talked on slack, we should revisit the creation of draft on a posterior ticket.

Thanks @marcogalluzzi

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
The [POSHI test](https://liferay.atlassian.net/browse/LPD-26520) that was failing now [works](https://testray.liferay.com/home/-/testray/case_results/2572419374?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F2150442030%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D2150442030%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc)

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
