### PR TITLE
LPD-25796 Missing Featured Images after upgrade.

### PR DESCRIPTION
**Pull request by manuelRives**
Featured images added from URL are missing after upgrade.

### CODE REVIEW

**Comment by jkappler** [comment]
@manuelRives

**Comment by jkappler** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by robertoDiaz** [comment]
Hey @manuelRives 

Could you add an integration test in order to test the upgrade?

**Review by robertoDiaz — CHANGES_REQUESTED** [review]
Can we add an integration test for this?

**Comment by manuelRives** [comment]
Test Added @jkappler, can you please check it out?, it's my first upgrade test.

**Comment by jkappler** [comment]
@manuelRives, the test still passes without your changes 😅. So it doesn't cover completely the problem

**Comment by manuelRives** [comment]
@jkappler Good catch, I missed setting the smallImageId as it happens when it is done from the interface.

That should be fixed now.

Thank you very much for reviewing it!

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
looks good from my side @manuelRives!

**Review by robertoDiaz — COMMENTED** [review]
LGTM :)

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
