### PR TITLE
LPD-15725 Add sections to "Recent" view

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPD-15725)

This task changes the way we show web content in "recent" view, that is, those articles that have been recently modified. It does not alter the articles and order of them, it just groups them in sections: today, seven days ago, thirty days ago, and older

## Change summary:

* Adds a new rowsplitter to take care of the sections that we are showing

## Test Scenario

* Enable Feature Flag LPS-202534
* Adds some web content (to test, I changed the modified the modified date of the web contents to reflect the dates of the sections)
* In the management toolbar select "Recent"

The articles should be grouped

Sections

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2538954885

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Failing tests are not related to the PR, so will try to fw again, if it fails, I will force it

**Comment by jkappler** [comment]
ci:report:2539149847

**Comment by jkappler** [comment]
failures are not related to the PR, so moving fw

**Pull request closed without merging**
