### PR TITLE
LPD-38525

### PR DESCRIPTION
**Pull request by NemethNorbert**
[LPD-38525](https://liferay.atlassian.net/browse/LPD-38525)

Issue and solution:
The root cause was the order of the events were fired when going to a specific history step. We need to fire the goto event for data-engine before we handle the undo or redo for the metadataFields. This is important, as if a locale change is happened in the history, Undo or Redo will change the locale, that will also fire an event for data-engine to update it's values. 

Test:
I updated our current test to include a locale change and cover this usecase as well.
Follow ticket description or run 'History button test'

Please review my changes

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Review by DiegoHu97 — CHANGES_REQUESTED** [review]
Reviewed! Just a minor chnage we discussed in slack, when clicking on undo all history, we should disable the button, the rest looks fine for me :smile:

**Review by ambrinchaudhary — APPROVED** [review]
Changes LGTM.

**Comment by NemethNorbert** [comment]
Hey @DiegoHu97 ,

I fixed the disabled state of the reset all button. I also modified the Undo/Redo logic to read the selectedLanguageId from the DOM instead of the scope due to the iterative implementation of selecting a step from the HistoryDropdown or using the reset all button.

Please review the changes

**Review by DiegoHu97 — APPROVED** [review]
LGTM!

**Comment by DiegoHu97** [comment]
The tests passes locally, I will run the suite again 
image

**Comment by DiegoHu97** [comment]
ci:test:content-management-playwright

**Comment by DiegoHu97** [comment]
ci:report:34520863

**Comment by DiegoHu97** [comment]
Test passes in CI, forwarding the PR 🎆

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:report:34849150

**Comment by DiegoHu97** [comment]
Failing test is a flaky one, forwarding pr

**Comment by DiegoHu97** [comment]
ci:forward:force

**Pull request closed without merging**
