### PR TITLE
LPD-37754 Save as Draft in journal with Permissions but without autosave

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
[Link to issue ](https://liferay.atlassian.net/browse/LPD-37754)

# Motivation

Web Content cannot be saved as draft, is published instead 

# How did I solve it
It was caused by https://github.com/liferay-content-management/liferay-portal/pull/5770/files#diff-6475ec503527e9273c8409ce7484ff9657814260d69480848d5d0524234d506aR303. I fixed it by not overriding the action, but receive it from the Publish modal. 

To test it, you can follow the steps described in the ticket, or run 
`npm run playwright -- test -g 'LPD-37754' --reporter list`
Screenshot 2024-10-01 at 13 05 28

I also fixed to other tests related to scheduling a web content. 
Screenshot 2024-10-01 at 13 25 03

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
ci:report:28368192

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
Related playwright tests passed but I'm worried about the amount of total failures, so I'm running again our suite. 

Screenshot 2024-10-02 at 09 02 08

**Comment by ambrinchaudhary** [comment]
ci:report:29043820

**Comment by ambrinchaudhary** [comment]
Last build failed. I've checked again the [previous build](https://github.com/liferay-content-management/liferay-portal/pull/5923#issuecomment-2386541896): Most of the unique failures are "failed prior to run test", just 3 new test failing but are not related to WC and could be probably flaky. 
So I'm going to assume the risk and forward this pull @DiegoHu97 ;-)

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1387401_11246

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
