### PR TITLE
LPD-21597 Quarantine failing content management tests

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Quarantine failing release tests to reduce impact on release testing analysis. Please unquarantine the tests as each fix is implemented in their respective follow up tickets.

**JIRA Ticket**
https://liferay.atlassian.net/browse/LPD-21597

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@john-co Looks good, but there's a conflict; can you take a look?

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
resolved conflict and rebased to master

**Comment by john-co** [comment]
sf test affected by known upstream issue: https://liferay.slack.com/archives/CLCD3DQLF/p1712553705143229?thread_ts=1712542257.214599&cid=CLCD3DQLF

**Comment by john-co** [comment]
ci:test:sf

**Pull request closed without merging**
