### PR TITLE
LPD-44784 Back button doesn't work in Documents and Media's View History 

### PR DESCRIPTION
**Pull request by DiegoHu97**
LPD-44784 Back button doesn't work in Documents and Media's View History
# What is this trying to solve?

[Link to ticket](https://liferay.atlassian.net/browse/LPD-44784)

# How am I fixing it?
Use redirect instead of getBackURL

# How can I test it?
Follow the steps in the bug
image

### CODE REVIEW

**Review by Mikellorza — APPROVED** [review]
LGTM!!

**Comment by Mikellorza** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:report:96436001

**Comment by DiegoHu97** [comment]
ci:report:96436001

**Comment by DiegoHu97** [comment]
ci:forward

**Pull request closed without merging**
