### PR TITLE
LPD-37727 MB showing empty page when changing page size

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-37727

When on the last page, changing the page size to a value that would leave the current page empty (but still show results in previous pages) will result in an empty page.

# How am I fixing it?

The `SearchContainer#setResultsAndTotal` method already handles this situation, but it does it by mutating the search container based on the `total` value and the page size.  In order for the query to get the correct start/end values, it needs to create the `QueryDefinition` /after/ the search container has been updated.  Here, I'm delaying the creation of the query definition until the last possible moment -- inside the supplier.

# How can you verify that it works?

Run the included playwright test:
```
$ npm run playwright -- test -g 'LPD-37727' --reporter list

> @liferay/playwright@1.0.0 playwright
> playwright test -g LPD-37727 --reporter list


Running 1 test using 1 worker

     1 [message-boards-web] › message-boards-web/message-boards-web.spec.ts:145:1 › LPD-37727 Change delta to a higher value when on last page
  ✓  1 [message-boards-web] › message-boards-web/message-boards-web.spec.ts:145:1 › LPD-37727 Change delta to a higher value when on last page (14.3s)
  1 passed (16.5s)
```

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:content-management-playwright

**Comment by adolfopa** [comment]
Playwright test failures not related.

**Comment by balazssk** [comment]
Hi @adolfopa ,
The code looks good, manually checked and found 1 question:
* Once the pagination is reset to 8 threads [1, 5] are displayed. If the pagination is changed to 4 again, thread [5] is displayed instead of thread [1,4]. This also happens in web contents, so I'd say it is okay for now. Right?

**Comment by adolfopa** [comment]
@balazssk That's the expected behavior. The "cur" parameter is preserved, that's why you're showed only one element when picking a size of 4 (the second page has only one element).

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1307401_10209

**Comment by adolfopa** [comment]
ci:test:report

**Comment by adolfopa** [comment]
ci:report:30537689

**Comment by adolfopa** [comment]
No unique failures.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
