### PR TITLE
 LPD-18328 Arabic localization causes issue with Web Content filtering on date with API

### PR DESCRIPTION
**Pull request by jkappler**
This is a follow up to https://github.com/liferay-content-management/liferay-portal/pull/5167

The idea is to keep using DateFormatFactoryUtil, but using the locale with which the content is indexed.

Added test for the bug, using Arabic language (where the bug happened) and English language

### CODE REVIEW

**Comment by jkappler** [comment]
@4lejandrito, thanks for the help with the tests ❤️

**Review by adolfopa — APPROVED** [review]

**Comment by jkappler** [comment]
ci:report:2543494951

**Comment by jkappler** [comment]
Added missing baseline

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Even though it was not a unique failure, we need to delete the structured content, otherwise the next tests will fail

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2543890049

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
There are no unique failures in the report

**Pull request closed without merging**
