### PR TITLE
LPD-35541 DM:  replace the deprecated google library js api

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
# What is this trying to solve?

[Link to issue](https://liferay.atlassian.net/browse/LPD-35045)

New OAuth Client IDs cannot use the deprecated google library js api

# How am I solving this

Using the new Google API

# How can be tested

This new API works with old API keys and new ones generated with OAuth 2.0. 

- For testing with old API Keys: get the credentials from 1Password
- For testing with new API Keys: follow the steps described in https://liferay.atlassian.net/browse/LPD-35045. Pending request to IT to get this credentials in our 1Password vault. 

Current functional tests are ignored due to google security issues while automating the authentication.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:documents

**Comment by ambrinchaudhary** [comment]
ci:test:document

**Review by boton — APPROVED** [review]
LGTM!! Nice work here @ambrinchaudhary ❤️ 

Tested and working 
image

> [!NOTE]
> I left some small inline suggestions 😄

**Comment by ambrinchaudhary** [comment]
Thank you for your review and your comments, I changed them in the last commit. 
I'm going to launch current google drive tests before forwarding...

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:document

**Comment by ambrinchaudhary** [comment]
ci:report:7138810

**Comment by ambrinchaudhary** [comment]
There is only one unique failure with test https://testray.liferay.com/#/project/35392/routines/45357/build/7138810/case-result/7154278 
```
LocalFile.DMCache#CanConfigureCacheControlAsPublic: 
java.lang.Exception: The cache control setting is incorrect
```

Looking at the test it doesn't seem related to the pull changes, so I will consider it as flaky. 

The rest of the functional test for documents passes successfully. 

@boton are you ok with forwarding this pull?

**Comment by ambrinchaudhary** [comment]
ci:test:document

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
