### PR TITLE
LPD-17827 Do not clear these maps as they aren't recalculated like the group mime type

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPD-17827

The issue is that upon saving the Instance Settings the group's settings are cleared from memory. This causes the group to fall back on the instance's settings. The fix is to simply not clear these maps to retain the information about the groups with specific configurations in place.

If there are any questions or concerns please let me know.

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
ci:reevaluate:1377401_16049

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:report:2542029246

**Comment by jkappler** [comment]
@jonathanmccann, there's a unique failure for the PR 

com.liferay.document.library.web.exportimport.data.handler.test.DLPortletDataHandlerTest,https://testray.liferay.com/home/-/testray/case_results/2542029740/history,Unique,testGetExportModelCount
 
but I don't think it has to do with your changes, not at first sight. Still, can you please take a look? And if you see fit and it's not related, we can change it to Brian.

Thanks!

**Comment by jonathanmccann** [comment]
Thanks for the help @jkappler. I ran the test locally using this branch and the test passed:

```
com.liferay.document.library.web.exportimport.data.handler.test.DLPortletDataHandlerTest > testGetExportModelCount STARTED
com.liferay.document.library.web.exportimport.data.handler.test.DLPortletDataHandlerTest > testGetExportModelCount PASSED
```

**Comment by jkappler** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
ci:forward

**Comment by jonathanmccann** [comment]
ci:report:2542760698

**Comment by jonathanmccann** [comment]
@jkappler It seems the unique failure is now gone from CI but it's still failing. Can we force forward these changes?

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
