### PR TITLE
LPD-39226 [content-management] Review PR "Allow using directive script-src-attr 'none' by removing inline handlers" 

### PR DESCRIPTION
**Pull request by izaera**
Comes from https://github.com/liferay-frontend/liferay-portal/pull/4473

Please refer to both https://liferay.atlassian.net/browse/LPD-39123 and https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/3245277533/LPD-36188+-+Allow+using+directive+script-src-attr+none+by+removing+inline+handlers to find out the motivation for this PR.

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:content-management

**Review by ambrinchaudhary — APPROVED** [review]
Changes LGTM. 
anyway I am running again our test suite, as in the previous one where unique failures for this pull but don't seem to be related.

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
ci:report:45893849

**Comment by adolfopa** [comment]
Failures not related to this PR.

**Comment by adolfopa** [comment]
ci:forward

**Comment by izaera** [comment]
I'm closing this per :point_right:  https://github.com/brianchandotcom/liferay-portal/pull/155357#issuecomment-2423742140

Will resend when we decide how to tackle that.

**Comment by izaera** [comment]
A rework for this has been sent at https://github.com/liferay-content-management/liferay-portal/pull/6047

**Pull request closed without merging**
