### PR TITLE
LPD-34159 | Headless API structured content response shows null instead of empty string values "" 

### PR DESCRIPTION
**Pull request by bakayattila**
### What is this trying to solve?
https://liferay.atlassian.net/browse/LPD-34159

### How am I fixing it?
The String.ValueOf did not handle the case well when the data field in the Value was null. It returned a "null" instead of an empty string. The GetterUtil.getString returns an empty string in case of null.

### How can you verify that it works?

To test run:
`gw testIntegration --tests StructuredContentResourceTest.testGetStructuredContent`

Or manually test based on the LPD steps

previous pull request: https://github.com/brianchandotcom/liferay-portal/pull/153724

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@bakayattila Everything looks good, but there's a rebase conflict. Can you fix the conflict and force-push the changes to this same pr? Thanks!

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
