### PR TITLE
LPD-43247 Move AP poshi tests to integration tests

### PR DESCRIPTION
**Pull request by jkappler**
Remove poshi tests in favor of integration tests

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-43247)

Tests related to Asset Publisher have been moved to integration tests

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:82113709

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:test:stable

**Comment by jkappler** [comment]
ci:report:82546366

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:test:stable

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
