### PR TITLE
LPD-31571 Technical Task | Index resolution and aspect ratio fields

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LPD-31571

# What is this trying to solve?

Index resolution and aspect ratio for images and videos to perform some filters about this epic : https://liferay.atlassian.net/browse/LPD-30087

# How am I fixing it?

Add image information to develop aspect ratio filter and resolution filter in content dashboard.

# How can you verify that it works?

Run added integration tests.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:38318937

**Comment by Mikellorza** [comment]
ci:report:38318937

**Comment by Mikellorza** [comment]
The unique failure is in com.liferay.commerce.product.util.test.CPDefinitionHelperTest and it seems to be not related, but to double check, let's go to run test-relevant suite again.

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:report:38550723

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
@Mikellorza, test failures don't seem to be related to the changes

**Pull request closed without merging**
