### PR TITLE
LPD-34910 Remove FF LPD-10701: test fix

### PR DESCRIPTION
**Pull request by robertoDiaz**
LPD-34910 Remove FF LPD-10701: test fix

### What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-34910

We want to fully release the https://liferay.atlassian.net/browse/LPD-10701 : Display date for D&M to all the customers without activate any Feature Flag

It has broke test and we are fixing them

### How am I fixing it?

Some test are fixed

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:content-management

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
this PR does not remove the FF :D

**Comment by AliciaGarciaGarcia** [comment]
ci:report:16856145

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:report:17189136

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
