### PR TITLE
LPD-27486 Impedibugs for Dates filter in Content Dashboard

### PR DESCRIPTION
**Pull request by jkappler**
Impedibugs for Dates filter in Content Dashboard

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-27486)

This PR addresses three issues found when reviewing the story for date filters in the content dashboard

This PR also addresses a bad commit, it shouldn't have been filed for LPD-27486, so I reverted two commits and updated the LPD correspondingly

# How am I fixing it?

There are three issues that are fixed

1. When the modal for selecting the date range is closed with cancel, nothing is clickable on the page
2. Cannot select a year higher than the current one
3. Cannot clear the selected date filter on "clear"

# How can you verify that it works?

1. Go to content dashboard
2. In filters, scroll to the end, and select custom date
3. Cancel
4. Checkpoint: see that you can click in the applications menu or any item in the content dashboard
5. Go again to filters, and select custom date again
6. Select any date type
7. Checkpoint: see that you can select 2025 or higher as a date
8. Accept the selection
9. Click on clear in the toolbar
10. The selection should be removed

@sandrodw3

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]
Frontend changes LGTM! Thanks @sandrodw3

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
thanks @ambrinchaudhary ❤️

**Comment by jkappler** [comment]
ci:report:10625476

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
