### PR TITLE
LPD-1394 Avoid NPE in back button by checking portlet name

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-1394 - NPE after clicking back button in Result Rankings portlet after viewing Document preview

This is a particular edge case from the Search team's Result Rankings module, it happens when:
- another portlet is using the asset taglib to display a document
- document has no size or preview
- there is no `redirect` value already established in the request

When the user clicks on the back button, it'll throw a null pointer exception since there is no view `document_library/view` or `document_library/view_folder` in the search module. These changes are just checking that the portlet is from Documents and Media. If it is not, the URL will be null and the back icon won't be shown.

Let me know any changes to make, thank you for taking a look!

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:reevaluate:1287401_9141

**Comment by oliv-yu** [comment]
ci:report:2548153937

**Comment by oliv-yu** [comment]
Failures on CI do not look related to these changes, so I'll try forwarding again.

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:report:2548751212

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:report:2548841602

**Comment by oliv-yu** [comment]
ci:forward:force

**Pull request closed without merging**
