### PR TITLE
LPD-20998 Fix TranslationOptions import

### PR DESCRIPTION
**Pull request by DiegoHu97**
\[Link to ticket\](https://liferay.atlassian.net/browse/LPD-20998)

I added the correct FF to TranslationsOptions.tsx component 

  
CC: @veroglez @NemethNorbert

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/148376

**Comment by sandrodw3** [comment]
ci:close

**Pull request closed without merging**
