### PR TITLE
LPD-25630 Show the status to guest user

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
