### PR TITLE
LPD-31059 [playwright] Fix LPD-24942: This is a test for translations filter button in web content

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-31059

We are fixing a broken test

# How am I fixing it?

Applying missing refactor/rename

# How can you verify that it works?

1. Go to `/modules/test/playwright`
3. Run `npm install` (setup)
4. Run `npm run playwright test -- -g "LPD-27995"` to run the test

# Avoid flakiness by repeating 10 times

```sh
npm run playwright test -- -g "LPD-27995" --reporter list --repeat-each 10
```

image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:playwright

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
Waiting for the playwright tests to pass before forwarding.

**Comment by boton** [comment]
[Failures](https://github.com/liferay-content-management/liferay-portal/pull/5673#issuecomment-2218014439) look unrelated 

image

The other journal flaky failure is unrelated [`LPD-26863: Undo/Redo buttons work with metadata fields`](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1151999//testReport/journal-web_journalArticle.spec/ts/LPD_26863__Undo_Redo_buttons_work_with_metadata_fields), @DiegoHu97 is working on it.

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
