### PR TITLE
LPD-32028 Apply ERC to relationships within Categories & Tags.

### PR DESCRIPTION
**Pull request by manuelRives**
### What is this trying to solve?
https://liferay.atlassian.net/browse/LPD-32028 Apply ERC to relationships within Categories & Tags.
### How am I fixing it?
Adding the corresponding attributes to the REST API.
### Which attributes have been modified?
- AssetCategory (TaxonomyCategory) Check Mark
  - groupId(Group) -> Implented on this pull
  - companyId(Company) -> Implented on this pull
  - userId(User) -> Implented on this pull
  - parentCategoryId(AssetCategory) -> Implemented on https://github.com/brianchandotcom/liferay-portal/pull/156803
  - treePath, see technical notes  -> Implemented on https://github.com/brianchandotcom/liferay-portal/pull/156803
  - vocabularyId(AssetVocabulary) -> Implemented on https://github.com/brianchandotcom/liferay-portal/pull/156803
- AssetTag (Keyword) Check Mark
  - groupId(Group) -> Implented on this pull
  - companyId(Company) -> Implented on this pull
  - userId(User) -> Implented on this pull
- AssetVocabulary (TaxonomyVocabulary) Check Mark
  - groupId(Group) -> Implented on this pull
  - companyId(Company) -> Implented on this pull
  - userId(User) -> Implented on this pull
### How can you verify that it works?
Running included tests or modifying those elements in the REST API.

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by manuelRives** [comment]
ci:reevaluate:1387401_11662

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by manuelRives** [comment]
The failing buildRest is failing in other builds so I think we can force forward it https://github.com/liferay-headless/liferay-portal/pull/2379

**Pull request closed without merging**
