### PR TITLE
Lpd 33602 2

### PR DESCRIPTION
**Pull request by SamZiemer**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-33602

Create a new endpoint for Headless API to delete DocumentMetadataSets

# How am I fixing it?

Added a new endpoint for the delete method

# How can you verify that it works?

Run the tests in DocumentMetadataSetResourceTest

Resending this PR after a minor refactor to remove not needed changes and discussing Brian's concerns from a [previous PR](https://github.com/brianchandotcom/liferay-portal/pull/154441#issuecomment-2368142960)
/cc @jkappler

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by SamZiemer** [comment]
ci:report:29739773

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:report:30140978

**Comment by SamZiemer** [comment]
@adolfopa, the failures do not look like they are related to my pull, do you agree? If so I will forward this on.

**Comment by jkappler** [comment]
ci:forward

**Comment by SamZiemer** [comment]
ci:report:30947750

**Comment by SamZiemer** [comment]
ci:report:30947750

**Comment by SamZiemer** [comment]
None of the failures look related to my pull and seem consistently failing. I am going to force forward this pull.

**Comment by SamZiemer** [comment]
ci:forward:force

**Pull request closed without merging**
