### PR TITLE
LPD-28898 Image added via rich text editor on Wiki tool losing reference.

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-28898

There is an error when we are adding an image using copy paste and we should take into account when we are parsing it using creole parser. So, this PR include the necessary  code to perform it. 

# How am I fixing it?

1. Take into account when we are parsing xhtml for image nodes that including images content in base64.
2. Take into account in creole ckeditor when we are parsing images in base64. I sent a [PR to frontent infra team](https://github.com/liferay-frontend/liferay-portal/pull/4272) to review that part of code but I also included here in order to do a functional test. 

# How can you verify that it works?

Run included tests and follow the steps to reproduce the LPD bug.

### CODE REVIEW

**Review by jkappler — APPROVED** [review]
Backend side looks good @Mikellorza

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:wiki

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_13627

**Comment by adolfopa** [comment]
ci:test:wiki

**Comment by adolfopa** [comment]
ci:reevaluate:1337401_6256

**Comment by Mikellorza** [comment]
ci:reevaluate:1337401_6256

**Comment by Mikellorza** [comment]
ci:report:1337401

**Comment by Mikellorza** [comment]
ci:test:wiki

**Comment by Mikellorza** [comment]
ci:reevaluate:1357401_5922

**Comment by Mikellorza** [comment]
ci:report:24891409

**Comment by Mikellorza** [comment]
Running ci:test:wiki again to do a triple check if the errors are related. For the moment they are not related with this PR.

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
This PR https://github.com/liferay-frontend/liferay-portal/pull/4272 is going to Brian, so, since failed wiki tests are not related and if the stable test suite pass we can move forward to Brian.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
