### PR TITLE
LPD-27664 Integration test

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi,
I am sending the integration test for : [Link to ticket](https://issues.liferay.com/browse/LPD-27664)
and the PR: https://github.com/liferay-content-management/liferay-portal/pull/5536

Thanks in advance!

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
