### PR TITLE
LPD-15901 Refactor: create a new module Locked Items

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Review can be started (UI tests will be created in another PR)

**What has been done?** 

Refactoring the locking of Pages, done by Echo team.
* Before: in Configuration we find "Locked Pages". 
* After: in Configuration we have "Locked Items", with a vertical list where "Pages" is selected.

See story for more info: https://liferay.atlassian.net/browse/LPD-16484

**How to test?**

* Edit a page, make a change so the Autosave is done
* From another admin user access Configuration -> Locked Items

Issue: https://liferay.atlassian.net/browse/LPD-15901

NOTE: the Locked Pages view could be refactored further by including more of it to the Locked Items view. When Locked KB Articles is added, this additional refactoring could be done (if needed)

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
@marcogalluzzi please rebase

image

**Comment by marcogalluzzi** [comment]
> @marcogalluzzi please rebase
> 

Rebased and conflicts resolved @AliciaGarciaGarcia . Thanks

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — COMMENTED** [review]
LGTM

The only thing is that maybe this table 
image
needs a little of love

It's only a suggestion

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
> LGTM
> 
> The only thing is that maybe this table image needs a little of love
> 
> It's only a suggestion

I agree. @ambrinchaudhary can you please have a look to it? This page is the combination of files:

* modules/apps/locked-items/locked-items-web/src/main/resources/META-INF/resources/view.jsp
* modules/apps/layout/layout-locked-layouts-web/src/main/resources/META-INF/resources/locked-items/view.jsp

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
All this must be under FF.

sorry

**Comment by marcogalluzzi** [comment]
> All this must be under FF.
> 
> sorry

Hi @AliciaGarciaGarcia in the last commit you can see how I mantain the previous Locked Pages view if FF is not enabled.

**Comment by AliciaGarciaGarcia** [comment]
As we talked on slack, check if you can leave the code as was and duplicate it till the FF removal.

**Comment by marcogalluzzi** [comment]
I will create a new PR and close this one because the new changes requested are significant.

**Pull request closed without merging**
