### PR TITLE
LPD-32586 Images not honouring file permissions when they are served from Adaptive Media

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPD-32586 Images not honouring file permissions when they are served from Adaptive Media

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-32586

If you can not see the image, it's reasonable that you cannot see the adaptive media image. So the permissions to see it (https://learn.liferay.com/web/guest/w/dxp/content-authoring-and-management/documents-and-media/publishing-and-sharing/managing-document-access/documents-and-media-permissions-reference) must be checked.

# How am I fixing it?

Checking the DOWNLOAD permission to get the adaptive media image, and if not pressent, do no show it.

# How can you verify that it works?

Steps to Reproduce
1) Add a new image and uncheck the Download permission for Guest users.
2) Edit home page and add the image on it
3) Open the page in an incognito window (not logged in) and check the result:
4) Minimize the browser window to a smaller width than the maximum defined in the adaptive media resolutions (you can see it by inspecting the element through the developer tools), so this way is served by AM.
5) The image should not be shown

Run the included automated tests.

# Commits

- **LPD-32586 check DOWNLOAD permission to know if we can see the file and return the adaptive media**
- **LPD-32586 fix test**
- **LPD-32586 add test to check that if no download permission there is no adaptive media returned**

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@AliciaGarciaGarcia, seems that tests are related to the changes 🤔

**Comment by jkappler** [comment]
ci:report:47321674

**Comment by AliciaGarciaGarcia** [comment]
solving failed test, relaunching and launching cm test to make sure other test does not fails because this PR, taking into account that test failures happened

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:report:47988126

**Comment by AliciaGarciaGarcia** [comment]
ci:test:blog

**Comment by AliciaGarciaGarcia** [comment]
ci:report:48050197

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
