### PR TITLE
LPD-28771 Remove Feature Flag for the Epic

### PR DESCRIPTION
**Pull request by Mikellorza**
### What is this trying to solve?
https://liferay.atlassian.net/browse/LPD-28771

Delete release feature Flag LPD-25680
 
### How am I fixing it?

Deleting feature flag

### How can you verify that it works?

Disabling or deleting all feature flags that you have in your bundle and going to content dashboard and also check if the requirement of the epic are working as expected:https://liferay.atlassian.net/browse/LPD-25680

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:20213193

**Comment by Mikellorza** [comment]
ci:report:20213193

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
