### PR TITLE
LPD-39230 [content-management] Review PR "Allow using directive script-src-attr 'none' by removing inline handlers" (part 2)

### PR DESCRIPTION
**Pull request by izaera**
Comes from liferay-frontend#4479

Please refer to both https://liferay.atlassian.net/browse/LPD-39123 and https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/3245277533/LPD-36188+-+Allow+using+directive+script-src-attr+none+by+removing+inline+handlers to find out the motivation for this PR.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:report:44533301

**Comment by adolfopa** [comment]
Test failures seem to be unrelated.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
