### PR TITLE
LPD-45131 The minute is not being taken into account in the scheduled content

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-45131

The minute is not being taken into account in the scheduled content

# How am I fixing it?

Replace displayDateMinutes to displayDateMinute

# How can you verify that it works?

Run the included automated tests.

# **Note**

There are some commits from other fix(LPD-44904) but there is not relevant to this PR, so ignore those commits

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:reevaluate:1277401_13439

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
@DiegoHu97  I 've just rebase against master and trying to pass suite again.

**Comment by Mikellorza** [comment]
ci:forward

**Review by DiegoHu97 — APPROVED** [review]

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:100156754

**Comment by Mikellorza** [comment]
There are not related issue to this PR. So, we can move forward.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
