### PR TITLE
LPD-37385 [playwright] DM refactor

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-37385

I'm trying to refactor some things like:

- Use IsolatedTest when is possible
    - Remove manual cleans
- Move LPD / LPS to tags
- Simplify the test creation - We don’t need different test functions if the Feature Flags don’t collision
- Remove dependencies (like moment)

>[!NOTE]
> I suspect some of the tests failed locally because they expect a clean portal for each run and my local postal became clean but later ran many tests.
> After refactor I will take a look at this cases and the flaky ones

# Before the PR

image

```
21 failed - master
    [document-library-web] › document-library-web/dmAICreator.spec.ts:17:1 › LPD-6717 Create AI Image option in Management Toolbar without API Key opens an alert
    [document-library-web] › document-library-web/dmAICreator.spec.ts:17:1 › LPD-6717 Create AI Image option in Management Toolbar without API Key opens an alert
    [document-library-web] › document-library-web/dmAICreator.spec.ts:17:1 › LPD-6717 Create AI Image option in Management Toolbar without API Key opens an alert
    [document-library-web] › document-library-web/dmAICreator.spec.ts:17:1 › LPD-6717 Create AI Image option in Management Toolbar without API Key opens an alert
    [document-library-web] › document-library-web/dmAICreator.spec.ts:41:1 › LPD-6677 Can add images to DM when API Key is provided
    [document-library-web] › document-library-web/dmAICreator.spec.ts:41:1 › LPD-6677 Can add images to DM when API Key is provided
    [document-library-web] › document-library-web/dmAICreator.spec.ts:41:1 › LPD-6677 Can add images to DM when API Key is provided
    [document-library-web] › document-library-web/dmAICreator.spec.ts:41:1 › LPD-6677 Can add images to DM when API Key is provided
    [document-library-web] › document-library-web/fileEntry.spec.ts:167:1  › LPD-16313 Show icon in the content admin and content editor
    [document-library-web] › document-library-web/fileEntry.spec.ts:192:1  › LPD-16313 Show icon in the DL item selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:192:1  › LPD-16313 Show icon in the DL item selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:192:1  › LPD-16313 Show icon in the DL item selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:192:1  › LPD-16313 Show icon in the DL item selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:318:1  › Replace option does not work on Categories Selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:318:1  › Replace option does not work on Categories Selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:318:1  › Replace option does not work on Categories Selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:318:1  › Replace option does not work on Categories Selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:39:1   › Check order by Relevance in Search of DL
    [document-library-web] › document-library-web/fileEntry.spec.ts:39:1   › Check order by Relevance in Search of DL
    [document-library-web] › document-library-web/fileEntry.spec.ts:39:1   › Check order by Relevance in Search of DL
    [document-library-web] › document-library-web/fileEntry.spec.ts:39:1   › Check order by Relevance in Search of DL
```

# After the PR

image

```
14 failed - LPD-37385-TEST-DM-playwright-refactor
    [document-library-web] › document-library-web/dmAICreator.spec.ts:61:1 › Can add images to DM when API Key is provided
    [document-library-web] › document-library-web/dmAICreator.spec.ts:61:1 › Can add images to DM when API Key is provided
    [document-library-web] › document-library-web/dmAICreator.spec.ts:61:1 › Can add images to DM when API Key is provided
    [document-library-web] › document-library-web/dmAICreator.spec.ts:61:1 › Can add images to DM when API Key is provided
    [document-library-web] › document-library-web/fileEntry.spec.ts:33:1 › Check order by Relevance in Search of DL
    [document-library-web] › document-library-web/fileEntry.spec.ts:192:1 › Show icon in the DL item selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:322:1 › Replace option does not work on Categories Selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:33:1 › Check order by Relevance in Search of DL
    [document-library-web] › document-library-web/fileEntry.spec.ts:322:1 › Replace option does not work on Categories Selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:33:1 › Check order by Relevance in Search of DL
    [document-library-web] › document-library-web/fileEntry.spec.ts:322:1 › Replace option does not work on Categories Selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:33:1 › Check order by Relevance in Search of DL
    [document-library-web] › document-library-web/fileEntry.spec.ts:192:1 › Show icon in the DL item selector
    [document-library-web] › document-library-web/fileEntry.spec.ts:322:1 › Replace option does not work on Categories Selector
```

### CODE REVIEW

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
I moved into a draft because I'm, trying to add some tests fiexes

**Comment by boton** [comment]
I fix some test but I prefer to merge this refactor and work on top of it to avoid conflicts.

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:content-management-playwright

**Comment by boton** [comment]
## Test is passing in the CI

image

**Comment by boton** [comment]
ci:test:sf

**Review by robertoDiaz — APPROVED** [review]
LGTM 👍

**Comment by robertoDiaz** [comment]
@boton, If you have done a full CI test run analysis and it's ok, please forward this pull

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
