### PR TITLE
LPD-16308 Use same logic to generate the description than used in MetaTagsTag.java

### PR DESCRIPTION
**Pull request by robertoDiaz**
In some cases the meta tag and the og:description have different values since they are generated using different logic.

In this pull this is fixed and both cases call the same logic in order to set the value of both tags

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:test:help

**Comment by marcogalluzzi** [comment]
@robertoDiaz Can you please check if this failing poshi test is related to your changes? `OpenGraph#CanMapSiteImageToDisplayPage` 
Thanks

**Comment by marcogalluzzi** [comment]
ci:test:seo

**Comment by robertoDiaz** [comment]
> @robertoDiaz Can you please check if this failing poshi test is related to your changes? `OpenGraph#CanMapSiteImageToDisplayPage` Thanks
> 
> Edit: running again SEO test, just in case it is flaky

It shouldn't (I' just adding another description that was missing, but let's see if the new test run also shows the error or if this is a flaky test)

Thanks for taking care

**Comment by robertoDiaz** [comment]
ci:report:2534033298

**Comment by robertoDiaz** [comment]
[CanMapBlogsToDisplayPage](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829557//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_OpenGraph_CanMapBlogsToDisplayPage_) and [CanMapDocumentToDisplayPage](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829557//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_OpenGraph_CanMapDocumentToDisplayPage_) seem related.

Analyzing

**Comment by robertoDiaz** [comment]
Close since I have to recheck the solution

**Pull request closed without merging**
