### PR TITLE
LPD-28152 Change to release FF

### PR DESCRIPTION
**Pull request by DiegoHu97**
Change to release FF

# What is this trying to solve?

Change to release FF as https://liferay.atlassian.net/browse/LPD-11253 is already done

[Link to ticket](https://liferay.atlassian.net/browse/LPD-28152)

# How am I fixing it?

Add release type in portal.properties and add title and description in Language.properties

# How can you verify that it works?

- Go to Control Menu > instance settings > Feature Flags > activate FF LPD-11253

# Why this does not need tests?

This is just a chnage of FF, no need to create tests for it

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:report:13999851

**Comment by DiegoHu97** [comment]
ci:forward.force

**Comment by DiegoHu97** [comment]
ci:forward:force

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:report:14602294

**Comment by DiegoHu97** [comment]
ci:forward:force

**Pull request closed without merging**
