### PR TITLE
LPD-22151 now the tags are case sensitive so we have to check it with capital letter

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
… capital letter

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:autotagging

**Comment by AliciaGarciaGarcia** [comment]
ci:test:auto-tagging

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by AliciaGarciaGarcia** [comment]
ci:test:auto-tagging

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2558304828

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2558312032

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2558331444

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:auto-tagging

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2558503668

**Comment by AliciaGarciaGarcia** [comment]
ci:test:auto-tagging

**Comment by AliciaGarciaGarcia** [comment]
ci:test:auto-tagging

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2558607917

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
