### PR TITLE
LPD-20705 create playwright tests - KB Article Locking

### PR DESCRIPTION
**Pull request by marcogalluzzi**
I've added the first Playwright tests for the [KB Article Lock epic](https://liferay.atlassian.net/browse/LPD-11003), so I had to work on:

* having 2 concurrent users
* adding a KB Article through API (to avoid manual navigation)
* providing direct URLs for KB pages (to avoid manual navigation)

I've just covered the test for this subtask: https://liferay.atlassian.net/browse/LPD-23801

:warning:  PLEASE NOTE - you need to run this command before running the tests, so we can login with other users: `npm run local:setup knowledge-base-web`

Put on hold until https://github.com/brianchandotcom/liferay-portal/pull/149899 is merged into master.

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
ci:test:playwright

**Comment by marcogalluzzi** [comment]
ci:test:playwright

**Comment by marcogalluzzi** [comment]
@boton confirmed, the new test passes also in CI: https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/870968/testReport/knowledge-base-web_knowledge-base-web.spec/ts/

**Comment by boton** [comment]
@marcogalluzzi I reassign the review to @AliciaGarciaGarcia, I have too much on my plate. Than you both ❤️

**Review by AliciaGarciaGarcia — APPROVED** [review]
some minor sf changes that can be done or not. talked on slack

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
