### PR TITLE
LPD-37407 Narrow down set of tests in content-management suite

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-37407

Narrow down the set of modules/tests that are evaluated in our content-management suite.

# How am I fixing it?

By including only the set of modules owned by the team. In the case of Js unit tests, I'm only including those modules that have Js unit tests.

# How can you verify that it works?

We'll need to manually check the build results to ensure that it doesn't include additional modules.

# Why doesn't this include any test?

This only changes the CI configuration.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
@adolfopa, looks good, want to fwd it?

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
