### PR TITLE
LPD-31699 Add ExternalReferenceCode to Document Shortcuts (Part 1 and 2)

### PR DESCRIPTION
**Pull request by adolfopa**
https://liferay.atlassian.net/browse/LPD-31699
https://liferay.atlassian.net/browse/LPD-31830

Needed to amend Part 1 LPD-31699 because Repository and DLApp were missing the necessary methods for headless to consume.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
