### PR TITLE
LPD-6962 update status and show info on the file

### PR DESCRIPTION
**Pull request by robertoDiaz**
I think that I was able to fix the problems that @AliciaGarciaGarcia mentioned in slack about the https://github.com/liferay-content-management/liferay-portal/pull/5146 and the version update.

Also, I did some changes in the markup in order to avoid https://github.com/liferay-content-management/liferay-portal/pull/5146/commits/f5a275666d36799c04f7c641bcfa110c955cde82 and duplicate the status label in some cases.

@boton the help message is a little bit misaligned with the status label so it has to be improved in further PRs

### CODE REVIEW

**Review by boton — APPROVED** [review]
The markup changes are good enough, status labels are misaligned 😓 . 
We are going to align it on https://liferay.atlassian.net/browse/LPD-16658

**Comment by robertoDiaz** [comment]
ci:report:2542096506

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
adding : 
image

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by AliciaGarciaGarcia** [comment]
ci:report:2543347320

**Comment by AliciaGarciaGarcia** [comment]
Case Name,Case History URL,Failure Type,Error Message
Unique Failures
LocalFile.DMFileEntry#CanRepublishDocumentAfterDisablingExpirationDate,https://testray.liferay.com/home/-/testray/case_results/2543490996/history,Unique,java.lang.Exception: Element is checked at "//label[contains(..'Never Expire')]//input[@type='checkbox']"
LocalFile.DMFileEntry#CanViewExpiredDocumentAsContentReviewer,https://testray.liferay.com/home/-/testray/case_results/2543491002/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'Document_5.txt')]//span[@class='workflow-status']"
LocalFile.DMFileEntry#CannotViewExpiredDocumentAsGuest,https://testray.liferay.com/home/-/testray/case_results/2543491011/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'Document_3.txt')]//span[@class='workflow-status']"
LocalFile.DMFileEntry#WildcardCanBeDefinedWithOtherFileExtensions,https://testray.liferay.com/home/-/testray/case_results/2543491039/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'Document_2.jpg')]//span[@class='workflow-status']"
LocalFile.DMFileEntry#CanViewExpiredDocument,https://testray.liferay.com/home/-/testray/case_results/2543491008/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'Document_1.txt')]//span[@class='workflow-status']"
LocalFile.DMFileEntry#CanRestoreExpiredDocument,https://testray.liferay.com/home/-/testray/case_results/2543490989/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'Document_1.txt')]//span[@class='workflow-status']"
LocalFile.DMFileEntry#BulkCopyDoesNotFactorInDocumentStatus,https://testray.liferay.com/home/-/testray/case_results/2543490864/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'Document_1.jpg')]//span[@class='workflow-status']"
LocalFile.DMWorkflow#CanRemoveWorkflowFromFolder,https://testray.liferay.com/home/-/testray/case_results/2543490900/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'Document_1.jpg')]//span[@class='workflow-status']"
LocalFile.DMWorkflow#CanResubmitRejectedDocument,https://testray.liferay.com/home/-/testray/case_results/2543490905/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'Document_1.doc')]//span[@class='workflow-status']"
LocalFile.DMFileEntry#CanCopyPendingDocumentToOtherSite,https://testray.liferay.com/home/-/testray/case_results/2543490861/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'DM Document Title')]//span[@class='workflow-status']"
LocalFile.DMFileEntry#CanCopyDraftDocumentToOtherSite,https://testray.liferay.com/home/-/testray/case_results/2543490860/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'DM Document Title')]//span[@class='workflow-status']"
LocalFile.DMFileEntry#CanCheckInAsMajorVersion,https://testray.liferay.com/home/-/testray/case_results/2543490946/history,Unique,com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//dd[contains(..'Check in as major version')]//span[@class='workflow-status']"

**Comment by AliciaGarciaGarcia** [comment]
closed in favor of https://github.com/liferay-content-management/liferay-portal/pull/5172

**Pull request closed without merging**
