### PR TITLE
LPD-25479 Migrate POSHI tests to integration test

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-25479

There are a lot of redundant upgrade tests for auto tagging.  These were trying to avoid a regression where the tensorflow jars weren't being downloaded correctly during the upgrade, but the same can be attained with a simpler and more direct integration test.

# How am I fixing it?

By writing an integration test that checks the original issue directly, instead of doing it indirectly through other applications.

# How can you verify that it works?

Run the integration test and see it passing.

### CODE REVIEW

**Comment by adolfopa** [comment]
Putting this on hold, as it depends on https://github.com/ling-alan-huang/liferay-portal/pull/2570.  Once the SF rule changes are merged, this can be forwarded.

**Comment by adolfopa** [comment]
Note that the SF failure is expected; I've sent changes to that rule in a different PR.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:upgrade

**Comment by adolfopa** [comment]
ci:report:2568889751

**Comment by adolfopa** [comment]
ci:report:2568889751

**Comment by adolfopa** [comment]
ci:test:upgrade

**Comment by adolfopa** [comment]
ci:reevaluate:1257401_5316

**Comment by adolfopa** [comment]
ci:test:upgrade

**Comment by adolfopa** [comment]
ci:report:2569955126

**Comment by adolfopa** [comment]
No unique upgrade failures; I'm going to give `relevant` another chance.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:report:2570034972

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
