### PR TITLE
LPD-27083 Create endpoint for deleting Document Shortcut

### PR DESCRIPTION
**Pull request by jonathanmccann**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-27083

Create endpoint for deleting Document Shortcut

# How am I fixing it?

Added a new `delete` method to the schema. This will most likely conflict with https://github.com/liferay-content-management/liferay-portal/pull/5544 so will be rebased once that is merged.

# How can you verify that it works?

Run the tests in `DocumentShortcutResourceTest` or manually call the delete method through the API explorer.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]
Looks good as always @jonathanmccann!

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
