### PR TITLE
LPD-19083 Show icon in the content admin and content  editor

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: 

1. https://liferay.atlassian.net/browse/LPD-19083 
2. https://liferay.atlassian.net/browse/LPD-19253

Description
--------
Show the lock icon when the articles does not have permission for guest user in :

1. Web content admin list view
3. Web content admin table view
4. Web content editor when editing an article
5. Item selector list view
6. Item selector table view

This PR also fix a bug to do not show the status header. [This commit](https://github.com/liferay-content-management/liferay-portal/pull/5188/commits/9a5346c2c5d427ea912bc6e612f1a87f68b8bb02) fix this: 

image

see the figma : https://www.figma.com/file/ClHyvl3Ay4PEHl9OtfmUno/LPD-15807-Identify-at-a-glance-if-a-WC-is-visible-for-guests?type=design&node-id=1-457&mode=design&t=mdeHpxT32kBEwesS-0

For the frontend revisor: I added some css classes to follow the figma but maybe I am wrong, please review that classes and so on.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:report:2546103625

**Comment by Mikellorza** [comment]
The unique failed tests are not related with the PR changes. So lets go forward with the PR.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
