### PR TITLE
[Draft] LPD-43386 Translation progress in Web Content

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @NemethNorbert @DiegoHu97, may I ask for your review here, before working on tests? 

You can see the issue details here: https://liferay.atlassian.net/browse/LPD-43386 
Let's imagine we fill: 

- For en_US: title and content field
- For es_ES: only title

So, the thing is that when saved as draft, we are not "cleaning" the content fields, just the [title and description](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/JournalPortlet.es.js#L327) (this is the reason why it doesn't fail when you fill just the content field, not the title) .Thus, when the WC is saved as draft, the content value for ES is not cleaned and the inputs present looks like: 

**en_US - Title**
`<input class="field form-control" id="_com_liferay_journal_web_portlet_JournalPortlet_titleMapAsXML_en_US" name="_com_liferay_journal_web_portlet_JournalPortlet_titleMapAsXML_en_US" type="hidden" value="english" data-languageid="en_US" dir="ltr" data-field-name="titleMapAsXML">`

**es_ES - Title**
`<input class="field form-control" id="_com_liferay_journal_web_portlet_JournalPortlet_titleMapAsXML_es_ES" name="_com_liferay_journal_web_portlet_JournalPortlet_titleMapAsXML_es_ES" type="hidden" value="español" data-languageid="es_ES" dir="ltr" data-field-name="titleMapAsXML">`

**en_US - Content**
`<input data-field-name="contento3qq1KRo" data-languageid="en_US" data-translated="false" type="hidden" name="_com_liferay_journal_web_portlet_JournalPortlet_ddm$$content$o3qq1KRo$0$$en_US" value="<p>content</p>">`

**es_ES - Content**
`<input data-field-name="contento3qq1KRo" data-languageid="es_ES" data-translated="false" type="hidden" value="<p>content</p>">`

And when calculating the translation progress, this was counting as a "translated" field, thus the label "Translated" was shown. With the current fix, I am first removing the inputs that has the attribute `data-translated=false` (but not the rest, title has not that attribute) 
**Note**: I just realised that for field en_US - Content, data-translated attribute is also set to false... So now, I'm a bit confused...

I kindly ask for your review as I am not yet familiar with all these components ;-) 

The other doubt I have, this happens only when saved as draft. While you are in the page editing the web content, everything works fine... 🤔, with autosave also works fine, and when saved as draft, if you go back to the list and open the WC, also the Translation Progess is correct... there are puzzle pieces that I'm still not able to connect, so I appreciate any feedback here.

### CODE REVIEW

**Comment by NemethNorbert** [comment]
Started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
Hey @ambrinchaudhary ,

I was testing the issue and I noticed a few things.

1. The language selector does not update to the new language. It keeps showing en_US
2. The issue only reproducible with the language you are saving the article as draft. Meaning if you modify ca_ES and then go to zh_CN language and modify the title and save it as draft, the translation count of ca_ES will be correct while zh_CN will be considered translated.
3. More over if we just select a new language and hit save as draft, the content field will become translated.

This is a behaviour that is known or at least it was working like this for a while now. I think we have to get rid of the behaviour where we automatically consider all ddm fields translated if we save the article. This is not an issue with the language selector and how we are calculating the translated fields, as those fields are actually become translated.
If you reproduce my 2. point than modify the default language translations, you will see that ca_ES content field values will be updated, while the fields in zh_CN remain as is.



JournalConverterImpl._addMissingFieldValues() Might be a good candidate for this behaviour

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by DiegoHu97 — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:content-management

**Comment by ambrinchaudhary** [comment]
Hey @NemethNorbert, @DiegoHu97 and I have been debugging more this issue, and it seems that this could fix could be valid for this LPP. Anyway, we are launching our test suite before to check it doesn't cause any regression while I work on a test to cover this case

**Comment by NemethNorbert** [comment]
started reviewing :)

**Comment by ambrinchaudhary** [comment]
UPDATE: 
Last commits related to the upgrade to react 18 solved this issue in master (not reproducible anymore). 

Could be that the fix is between commits `5977c0315328ad6c5de96321ee620f477919788b` 
 and `2170c5cdf2b2bb3ffaa545baf4b175be36672a27` . 
In part, this makes sense as I was starting tu suspect that it is not a bug in our components. On the other side... I really hope that the solution is not to update to react 18, as this cannot be delivered as a hotfix to the customer....

**Comment by ambrinchaudhary** [comment]
Closing this pull request, as this is not reproducible in master anymore so we don't need to send a fix there.

**Pull request closed without merging**
