### PR TITLE
LPD-30548 Convert LocalFile.WebContent#AddWebContentWithCategoryHiearchy to integration test

### PR DESCRIPTION
**Pull request by jkappler**
[Link to ticket](https://issues.liferay.com/browse/LPD-30548)

As part of the quality initiative we are converting LocalFile.WebContent#AddWebContentWithCategoryHiearchy to integration test

* Added a new test module for asset-taglib
* Added also Asset Framework to the test suit

### CODE REVIEW

**Comment by jkappler** [comment]
Sending on top of https://github.com/liferay-content-management/liferay-portal/pull/5654

**Review by adolfopa — APPROVED** [review]

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
