### PR TITLE
LPD-39667 Fix tests ImageEditor#CanSaveResizedImage and ImageEditor#CanSaveResizedImagePreview

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-39667

These POSHI tests are failing:

* ImageEditor#CanSaveResizedImage
* ImageEditor#CanSaveResizedImagePreview

# How am I fixing it?

In [LPD-39202](https://github.com/liferay/liferay-portal/commit/1e1aca8135f8224dee2dd2b25e778af829ff2a3b) the panel group has been changed, so I've fixed the locator.

# How can you verify that it works?

`ant -f build-test.xml run-selenium-test -Dtest.class=ImageEditor#CanSaveResizedImage`
`ant -f build-test.xml run-selenium-test -Dtest.class=ImageEditor#CanSaveResizedImagePreview`

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:content-management

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_14022

**Comment by marcogalluzzi** [comment]
ci:report:46333846

**Comment by marcogalluzzi** [comment]
All unique test failures are not related, they are related to Sharepoint. Forcing the forwarding.

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
