### PR TITLE
LPD-26752 TESTS Blogs friendlyURL categories

### PR DESCRIPTION
**Pull request by boton**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-26752

We are adding tests to Epic https://liferay.atlassian.net/browse/LPD-11147 use cases.

# How am I testing?

We are trying to test if a user adds categories to a blog entry via UI, 

- ✅ The addon URL preview is the expected.
- ✅ The redirect with the categories is created

# How can you verify that it works?

1. Go to `/modules/test/playwright`
3. Run `npm install` (setup)
4. Run `npm run test -- -g "LPD-26752|LPD-6813"` to only run the new test and affected test

image

# Avoid flakiness repeating 10 times

```sh
npm run test -- -g "LPD-26752" --reporter list --repeat-each 10
```

image

# Screenrecord tests execution

<details open>
  <summary>New test</summary>

[video.webm](https://github.com/liferay-content-management/liferay-portal/assets/67901/3358ba44-752d-4854-9bcc-525d7a3e0f37)

</details>

<details>
  <summary>Affected test</summary>
  
[video.webm](https://github.com/liferay-content-management/liferay-portal/assets/67901/15f2130e-a2b4-466f-8cbb-0de73ea1abb0)

</details>

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:playwright

**Comment by boton** [comment]
No failures related to this PR.

It's checkable here 
Testray Build:[[master] ci:test:playwright - boton > liferay-content-management - PR#5495 - 2024-05-29[05:17:13]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2573224238)

image

**Comment by boton** [comment]
this is the blogs report https://testray.liferay.com/reports/production/logs/2024-05/test-1-40/test-portal-acceptance-pullrequest(master)/9764/playwright-js-tomcat90-mysql57-jdk8/19/0/playwright-report/index.html?authuser=0

image

**Review by ambrinchaudhary — COMMENTED** [review]
Awesome work here! 

Just wondering, shouldn't the test remove all this vocabulary, categories, DPT created? 
Or is not necessary because it is created in a different site?

**Review by marcogalluzzi — COMMENTED** [review]
Impressive work  :clap: 

When testing in my machine, one test failed, do you know why?

```
1) [blogs-web] › blogs-web/blogEntry.spec.ts:68:1 › LPD-26752 Select categories for the custom friendly URL 

    Error: locator.isHidden: Error: strict mode violation: getByText('Dynamic') resolved to 3 elements:
        1) <label class="" for="_com_liferay_portlet_configuration…>…</label> aka getByText('Dynamic', { exact: true })
        2) <option class="" value="29931"> Dynamic Data Lists Record </option> aka getByLabel('Asset Type')
        3) <option class="" value="29931" data-selected="true"> Dynamic Data Lists Record </option> aka locator('[id="_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_currentClassNameIds"]')

```

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by boton** [comment]
> Awesome work here!
> 
> Just wondering, shouldn't the test remove all this vocabulary, categories, DPT created? Or is not necessary because it is created in a different site?

It's created using [isolatedSite](https://github.com/liferay/liferay-portal/blob/c18e5d4a56ca81c03910cedce660da0b50e0e641/modules/test/playwright/fixtures/isolatedSiteTest.ts) this implies that new site and all of their contents it 's created before the test run and removed before.

**Comment by boton** [comment]
> Impressive work 👏
> 
> When testing in my machine, one test failed, do you know why?
> 
> ```
> 1) [blogs-web] › blogs-web/blogEntry.spec.ts:68:1 › LPD-26752 Select categories for the custom friendly URL 
> 
>     Error: locator.isHidden: Error: strict mode violation: getByText('Dynamic') resolved to 3 elements:
>         1) <label class="" for="_com_liferay_portlet_configuration…>…</label> aka getByText('Dynamic', { exact: true })
>         2) <option class="" value="29931"> Dynamic Data Lists Record </option> aka getByLabel('Asset Type')
>         3) <option class="" value="29931" data-selected="true"> Dynamic Data Lists Record </option> aka locator('[id="_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_currentClassNameIds"]')
> ```

Nice catch I will try to reproduce in my local, looks like some locator found several concurrences 😞

**Comment by boton** [comment]
working on an issue detected with @marcogalluzzi

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
