### PR TITLE
LPD-30143 PropsUtil does not resolve correctly in a string literal, so extract to variable

### PR DESCRIPTION
**Pull request by jkappler**
PropsUtil.get("default.admin.password") does not resolve correctly in a string literal

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-30143)

Several poshi tests are failing with forbidden connection

# How am I fixing it?

Extract PropsUtil.get("default.admin.password") to a variable to let it resolve before using it in a string literal

# How can you verify that it works?

Deploy portal-web and check that poshi tests such as the following work

LocalFile.ExposeErcInWikiPageAttachment#CanReturenErcWithGetSiteWikiPagesByErc
LocalFile.ExposeErcInWikiPageAttachment#CanDeleteAttachmentByExternalReferenceCode
LocalFile.ExposeErcInWikiPageAttachment#CanReturenErcWithGetWikiPagesByWikiPageId
LocalFile.ExposeErcInWikiPageAttachment#CanReturenErcWithGetWikiPageAttachmentsByWikiPageId

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:report:27984803

**Review by jonathanmccann — APPROVED** [review]
Looks good to me!

**Comment by jkappler** [comment]
Thanks @jonathanmccann! It also seems that there is a SF test failure in upstream 😢 (not related to the changes)

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:content-management

**Comment by jkappler** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
