### PR TITLE
LPD-32288 PDF preview images have no alt attribute

### PR DESCRIPTION
**Pull request by balazssk**
# What is this trying to solve?
PDF previewer is not fully accessible, its is missing an alt attribute.
https://liferay.atlassian.net/browse/LPD-32288

# How am I fixing it?
Adding the fileVersion's description as the alt attribute, like how [ImagePreviewer](https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-preview-image/src/main/resources/META-INF/resources/preview/view.jsp#L46) does it

# How can you verify that it works?
Run the included automated tests.
`cd modules/apps/document-library/document-library-preview-document`
`npm run test`

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
