### PR TITLE
LPD-42641 When selecting web contents to display in the Web Content Display widget expired content is also displayed

### PR DESCRIPTION
**Pull request by bakayattila**
What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-42641

How am I fixing it?

The issue is that the selector also lists expired content. To avoid performance issues I created a new finder with the possibility to filter out the status that we want.

How can you verify that it works?

To test run:
gw testIntegration --tests JournalFolderFinderTest

@jkappler 

https://github.com/liferay-content-management/liferay-portal/pull/6152

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:reevaluate:1307401_10571

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
Tests are passing locally.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
