### PR TITLE
LPD-24608 Do not normalize on change

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]
Discussed this change with @robertoDiaz, friendly url in blogs needs to allow `/`, so we will not normalize it in frontend, just in backend. 
This is currently happening in master.

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
anyway, @robertoDiaz, check if this also needs to be removed https://github.com/ambrinchaudhary/liferay-portal/blame/master/modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/js/blogs/blogs.js#L201-L201

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
> anyway, @robertoDiaz, check if this also needs to be removed https://github.com/ambrinchaudhary/liferay-portal/blame/master/modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/js/blogs/blogs.js#L201-L201

I'm my tests it worked as a charm with my single change

**Comment by robertoDiaz** [comment]
ci:forward

**Pull request closed without merging**
